<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->string('name', 100);
            $table->string('m49', 3)->unique();
            $table->string('iso_alpha3', 3)->unique();
        });

        $data = [
            [ 'name' => 'Afghanistan', 'm49' => '004', 'iso_alpha3' => 'AFG' ],
            [ 'name' => 'Åland Islands', 'm49' => '248', 'iso_alpha3' => 'ALA' ],
            [ 'name' => 'Albania', 'm49' => '008', 'iso_alpha3' => 'ALB' ],
            [ 'name' => 'Algeria', 'm49' => '012', 'iso_alpha3' => 'DZA' ],
            [ 'name' => 'American Samoa', 'm49' => '016', 'iso_alpha3' => 'ASM' ],
            [ 'name' => 'Andorra', 'm49' => '020', 'iso_alpha3' => 'AND' ],
            [ 'name' => 'Angola', 'm49' => '024', 'iso_alpha3' => 'AGO' ],
            [ 'name' => 'Anguilla', 'm49' => '660', 'iso_alpha3' => 'AIA' ],
            [ 'name' => 'Antarctica', 'm49' => '010', 'iso_alpha3' => 'ATA' ],
            [ 'name' => 'Antigua and Barbuda', 'm49' => '028', 'iso_alpha3' => 'ATG' ],
            [ 'name' => 'Argentina', 'm49' => '032', 'iso_alpha3' => 'ARG' ],
            [ 'name' => 'Armenia', 'm49' => '051', 'iso_alpha3' => 'ARM' ],
            [ 'name' => 'Aruba', 'm49' => '533', 'iso_alpha3' => 'ABW' ],
            [ 'name' => 'Australia', 'm49' => '036', 'iso_alpha3' => 'AUS' ],
            [ 'name' => 'Austria', 'm49' => '040', 'iso_alpha3' => 'AUT' ],
            [ 'name' => 'Azerbaijan', 'm49' => '031', 'iso_alpha3' => 'AZE' ],
            [ 'name' => 'Bahamas', 'm49' => '044', 'iso_alpha3' => 'BHS' ],
            [ 'name' => 'Bahrain', 'm49' => '048', 'iso_alpha3' => 'BHR' ],
            [ 'name' => 'Bangladesh', 'm49' => '050', 'iso_alpha3' => 'BGD' ],
            [ 'name' => 'Barbados', 'm49' => '052', 'iso_alpha3' => 'BRB' ],
            [ 'name' => 'Belarus', 'm49' => '112', 'iso_alpha3' => 'BLR' ],
            [ 'name' => 'Belgium', 'm49' => '056', 'iso_alpha3' => 'BEL' ],
            [ 'name' => 'Belize', 'm49' => '084', 'iso_alpha3' => 'BLZ' ],
            [ 'name' => 'Benin', 'm49' => '204', 'iso_alpha3' => 'BEN' ],
            [ 'name' => 'Bermuda', 'm49' => '060', 'iso_alpha3' => 'BMU' ],
            [ 'name' => 'Bhutan', 'm49' => '064', 'iso_alpha3' => 'BTN' ],
            [ 'name' => 'Bolivia (Plurinational State of)', 'm49' => '068', 'iso_alpha3' => 'BOL' ],
            [ 'name' => 'Bonaire, Sint Eustatius and Saba', 'm49' => '535', 'iso_alpha3' => 'BES' ],
            [ 'name' => 'Bosnia and Herzegovina', 'm49' => '070', 'iso_alpha3' => 'BIH' ],
            [ 'name' => 'Botswana', 'm49' => '072', 'iso_alpha3' => 'BWA' ],
            [ 'name' => 'Bouvet Island', 'm49' => '074', 'iso_alpha3' => 'BVT' ],
            [ 'name' => 'Brazil', 'm49' => '076', 'iso_alpha3' => 'BRA' ],
            [ 'name' => 'British Indian Ocean Territory', 'm49' => '086', 'iso_alpha3' => 'IOT' ],
            [ 'name' => 'British Virgin Islands', 'm49' => '092', 'iso_alpha3' => 'VGB' ],
            [ 'name' => 'Brunei Darussalam', 'm49' => '096', 'iso_alpha3' => 'BRN' ],
            [ 'name' => 'Bulgaria', 'm49' => '100', 'iso_alpha3' => 'BGR' ],
            [ 'name' => 'Burkina Faso', 'm49' => '854', 'iso_alpha3' => 'BFA' ],
            [ 'name' => 'Burundi', 'm49' => '108', 'iso_alpha3' => 'BDI' ],
            [ 'name' => 'Cabo Verde', 'm49' => '132', 'iso_alpha3' => 'CPV' ],
            [ 'name' => 'Cambodia', 'm49' => '116', 'iso_alpha3' => 'KHM' ],
            [ 'name' => 'Cameroon', 'm49' => '120', 'iso_alpha3' => 'CMR' ],
            [ 'name' => 'Canada', 'm49' => '124', 'iso_alpha3' => 'CAN' ],
            [ 'name' => 'Cayman Islands', 'm49' => '136', 'iso_alpha3' => 'CYM' ],
            [ 'name' => 'Central African Republic', 'm49' => '140', 'iso_alpha3' => 'CAF' ],
            [ 'name' => 'Chad', 'm49' => '148', 'iso_alpha3' => 'TCD' ],
            [ 'name' => 'Chile', 'm49' => '152', 'iso_alpha3' => 'CHL' ],
            [ 'name' => 'China', 'm49' => '156', 'iso_alpha3' => 'CHN' ],
            [ 'name' => 'China, Hong Kong Special Administrative Region', 'm49' => '344', 'iso_alpha3' => 'HKG' ],
            [ 'name' => 'China, Macao Special Administrative Region', 'm49' => '446', 'iso_alpha3' => 'MAC' ],
            [ 'name' => 'Christmas Island', 'm49' => '162', 'iso_alpha3' => 'CXR' ],
            [ 'name' => 'Cocos (Keeling) Islands', 'm49' => '166', 'iso_alpha3' => 'CCK' ],
            [ 'name' => 'Colombia', 'm49' => '170', 'iso_alpha3' => 'COL' ],
            [ 'name' => 'Comoros', 'm49' => '174', 'iso_alpha3' => 'COM' ],
            [ 'name' => 'Congo', 'm49' => '178', 'iso_alpha3' => 'COG' ],
            [ 'name' => 'Cook Islands', 'm49' => '184', 'iso_alpha3' => 'COK' ],
            [ 'name' => 'Costa Rica', 'm49' => '188', 'iso_alpha3' => 'CRI' ],
            [ 'name' => 'Côte d’Ivoire', 'm49' => '384', 'iso_alpha3' => 'CIV' ],
            [ 'name' => 'Croatia', 'm49' => '191', 'iso_alpha3' => 'HRV' ],
            [ 'name' => 'Cuba', 'm49' => '192', 'iso_alpha3' => 'CUB' ],
            [ 'name' => 'Curaçao', 'm49' => '531', 'iso_alpha3' => 'CUW' ],
            [ 'name' => 'Cyprus', 'm49' => '196', 'iso_alpha3' => 'CYP' ],
            [ 'name' => 'Czechia', 'm49' => '203', 'iso_alpha3' => 'CZE' ],
            [ 'name' => 'Democratic People\'s Republic of Korea', 'm49' => '408', 'iso_alpha3' => 'PRK' ],
            [ 'name' => 'Democratic Republic of the Congo', 'm49' => '180', 'iso_alpha3' => 'COD' ],
            [ 'name' => 'Denmark', 'm49' => '208', 'iso_alpha3' => 'DNK' ],
            [ 'name' => 'Djibouti', 'm49' => '262', 'iso_alpha3' => 'DJI' ],
            [ 'name' => 'Dominica', 'm49' => '212', 'iso_alpha3' => 'DMA' ],
            [ 'name' => 'Dominican Republic', 'm49' => '214', 'iso_alpha3' => 'DOM' ],
            [ 'name' => 'Ecuador', 'm49' => '218', 'iso_alpha3' => 'ECU' ],
            [ 'name' => 'Egypt', 'm49' => '818', 'iso_alpha3' => 'EGY' ],
            [ 'name' => 'El Salvador', 'm49' => '222', 'iso_alpha3' => 'SLV' ],
            [ 'name' => 'Equatorial Guinea', 'm49' => '226', 'iso_alpha3' => 'GNQ' ],
            [ 'name' => 'Eritrea', 'm49' => '232', 'iso_alpha3' => 'ERI' ],
            [ 'name' => 'Estonia', 'm49' => '233', 'iso_alpha3' => 'EST' ],
            [ 'name' => 'Eswatini', 'm49' => '748', 'iso_alpha3' => 'SWZ' ],
            [ 'name' => 'Ethiopia', 'm49' => '231', 'iso_alpha3' => 'ETH' ],
            [ 'name' => 'Falkland Islands (Malvinas)', 'm49' => '238', 'iso_alpha3' => 'FLK' ],
            [ 'name' => 'Faroe Islands', 'm49' => '234', 'iso_alpha3' => 'FRO' ],
            [ 'name' => 'Fiji', 'm49' => '242', 'iso_alpha3' => 'FJI' ],
            [ 'name' => 'Finland', 'm49' => '246', 'iso_alpha3' => 'FIN' ],
            [ 'name' => 'France', 'm49' => '250', 'iso_alpha3' => 'FRA' ],
            [ 'name' => 'French Guiana', 'm49' => '254', 'iso_alpha3' => 'GUF' ],
            [ 'name' => 'French Polynesia', 'm49' => '258', 'iso_alpha3' => 'PYF' ],
            [ 'name' => 'French Southern Territories', 'm49' => '260', 'iso_alpha3' => 'ATF' ],
            [ 'name' => 'Gabon', 'm49' => '266', 'iso_alpha3' => 'GAB' ],
            [ 'name' => 'Gambia', 'm49' => '270', 'iso_alpha3' => 'GMB' ],
            [ 'name' => 'Georgia', 'm49' => '268', 'iso_alpha3' => 'GEO' ],
            [ 'name' => 'Germany', 'm49' => '276', 'iso_alpha3' => 'DEU' ],
            [ 'name' => 'Ghana', 'm49' => '288', 'iso_alpha3' => 'GHA' ],
            [ 'name' => 'Gibraltar', 'm49' => '292', 'iso_alpha3' => 'GIB' ],
            [ 'name' => 'Greece', 'm49' => '300', 'iso_alpha3' => 'GRC' ],
            [ 'name' => 'Greenland', 'm49' => '304', 'iso_alpha3' => 'GRL' ],
            [ 'name' => 'Grenada', 'm49' => '308', 'iso_alpha3' => 'GRD' ],
            [ 'name' => 'Guadeloupe', 'm49' => '312', 'iso_alpha3' => 'GLP' ],
            [ 'name' => 'Guam', 'm49' => '316', 'iso_alpha3' => 'GUM' ],
            [ 'name' => 'Guatemala', 'm49' => '320', 'iso_alpha3' => 'GTM' ],
            [ 'name' => 'Guernsey', 'm49' => '831', 'iso_alpha3' => 'GGY' ],
            [ 'name' => 'Guinea', 'm49' => '324', 'iso_alpha3' => 'GIN' ],
            [ 'name' => 'Guinea-Bissau', 'm49' => '624', 'iso_alpha3' => 'GNB' ],
            [ 'name' => 'Guyana', 'm49' => '328', 'iso_alpha3' => 'GUY' ],
            [ 'name' => 'Haiti', 'm49' => '332', 'iso_alpha3' => 'HTI' ],
            [ 'name' => 'Heard Island and McDonald Islands', 'm49' => '334', 'iso_alpha3' => 'HMD' ],
            [ 'name' => 'Holy See', 'm49' => '336', 'iso_alpha3' => 'VAT' ],
            [ 'name' => 'Honduras', 'm49' => '340', 'iso_alpha3' => 'HND' ],
            [ 'name' => 'Hungary', 'm49' => '348', 'iso_alpha3' => 'HUN' ],
            [ 'name' => 'Iceland', 'm49' => '352', 'iso_alpha3' => 'ISL' ],
            [ 'name' => 'India', 'm49' => '356', 'iso_alpha3' => 'IND' ],
            [ 'name' => 'Indonesia', 'm49' => '360', 'iso_alpha3' => 'IDN' ],
            [ 'name' => 'Iran (Islamic Republic of)', 'm49' => '364', 'iso_alpha3' => 'IRN' ],
            [ 'name' => 'Iraq', 'm49' => '368', 'iso_alpha3' => 'IRQ' ],
            [ 'name' => 'Ireland', 'm49' => '372', 'iso_alpha3' => 'IRL' ],
            [ 'name' => 'Isle of Man', 'm49' => '833', 'iso_alpha3' => 'IMN' ],
            [ 'name' => 'Israel', 'm49' => '376', 'iso_alpha3' => 'ISR' ],
            [ 'name' => 'Italy', 'm49' => '380', 'iso_alpha3' => 'ITA' ],
            [ 'name' => 'Jamaica', 'm49' => '388', 'iso_alpha3' => 'JAM' ],
            [ 'name' => 'Japan', 'm49' => '392', 'iso_alpha3' => 'JPN' ],
            [ 'name' => 'Jersey', 'm49' => '832', 'iso_alpha3' => 'JEY' ],
            [ 'name' => 'Jordan', 'm49' => '400', 'iso_alpha3' => 'JOR' ],
            [ 'name' => 'Kazakhstan', 'm49' => '398', 'iso_alpha3' => 'KAZ' ],
            [ 'name' => 'Kenya', 'm49' => '404', 'iso_alpha3' => 'KEN' ],
            [ 'name' => 'Kiribati', 'm49' => '296', 'iso_alpha3' => 'KIR' ],
            [ 'name' => 'Kuwait', 'm49' => '414', 'iso_alpha3' => 'KWT' ],
            [ 'name' => 'Kyrgyzstan', 'm49' => '417', 'iso_alpha3' => 'KGZ' ],
            [ 'name' => 'Lao People\'s Democratic Republic', 'm49' => '418', 'iso_alpha3' => 'LAO' ],
            [ 'name' => 'Latvia', 'm49' => '428', 'iso_alpha3' => 'LVA' ],
            [ 'name' => 'Lebanon', 'm49' => '422', 'iso_alpha3' => 'LBN' ],
            [ 'name' => 'Lesotho', 'm49' => '426', 'iso_alpha3' => 'LSO' ],
            [ 'name' => 'Liberia', 'm49' => '430', 'iso_alpha3' => 'LBR' ],
            [ 'name' => 'Libya', 'm49' => '434', 'iso_alpha3' => 'LBY' ],
            [ 'name' => 'Liechtenstein', 'm49' => '438', 'iso_alpha3' => 'LIE' ],
            [ 'name' => 'Lithuania', 'm49' => '440', 'iso_alpha3' => 'LTU' ],
            [ 'name' => 'Luxembourg', 'm49' => '442', 'iso_alpha3' => 'LUX' ],
            [ 'name' => 'Madagascar', 'm49' => '450', 'iso_alpha3' => 'MDG' ],
            [ 'name' => 'Malawi', 'm49' => '454', 'iso_alpha3' => 'MWI' ],
            [ 'name' => 'Malaysia', 'm49' => '458', 'iso_alpha3' => 'MYS' ],
            [ 'name' => 'Maldives', 'm49' => '462', 'iso_alpha3' => 'MDV' ],
            [ 'name' => 'Mali', 'm49' => '466', 'iso_alpha3' => 'MLI' ],
            [ 'name' => 'Malta', 'm49' => '470', 'iso_alpha3' => 'MLT' ],
            [ 'name' => 'Marshall Islands', 'm49' => '584', 'iso_alpha3' => 'MHL' ],
            [ 'name' => 'Martinique', 'm49' => '474', 'iso_alpha3' => 'MTQ' ],
            [ 'name' => 'Mauritania', 'm49' => '478', 'iso_alpha3' => 'MRT' ],
            [ 'name' => 'Mauritius', 'm49' => '480', 'iso_alpha3' => 'MUS' ],
            [ 'name' => 'Mayotte', 'm49' => '175', 'iso_alpha3' => 'MYT' ],
            [ 'name' => 'Mexico', 'm49' => '484', 'iso_alpha3' => 'MEX' ],
            [ 'name' => 'Micronesia (Federated States of)', 'm49' => '583', 'iso_alpha3' => 'FSM' ],
            [ 'name' => 'Monaco', 'm49' => '492', 'iso_alpha3' => 'MCO' ],
            [ 'name' => 'Mongolia', 'm49' => '496', 'iso_alpha3' => 'MNG' ],
            [ 'name' => 'Montenegro', 'm49' => '499', 'iso_alpha3' => 'MNE' ],
            [ 'name' => 'Montserrat', 'm49' => '500', 'iso_alpha3' => 'MSR' ],
            [ 'name' => 'Morocco', 'm49' => '504', 'iso_alpha3' => 'MAR' ],
            [ 'name' => 'Mozambique', 'm49' => '508', 'iso_alpha3' => 'MOZ' ],
            [ 'name' => 'Myanmar', 'm49' => '104', 'iso_alpha3' => 'MMR' ],
            [ 'name' => 'Namibia', 'm49' => '516', 'iso_alpha3' => 'NAM' ],
            [ 'name' => 'Nauru', 'm49' => '520', 'iso_alpha3' => 'NRU' ],
            [ 'name' => 'Nepal', 'm49' => '524', 'iso_alpha3' => 'NPL' ],
            [ 'name' => 'Netherlands (Kingdom of the)', 'm49' => '528', 'iso_alpha3' => 'NLD' ],
            [ 'name' => 'New Caledonia', 'm49' => '540', 'iso_alpha3' => 'NCL' ],
            [ 'name' => 'New Zealand', 'm49' => '554', 'iso_alpha3' => 'NZL' ],
            [ 'name' => 'Nicaragua', 'm49' => '558', 'iso_alpha3' => 'NIC' ],
            [ 'name' => 'Niger', 'm49' => '562', 'iso_alpha3' => 'NER' ],
            [ 'name' => 'Nigeria', 'm49' => '566', 'iso_alpha3' => 'NGA' ],
            [ 'name' => 'Niue', 'm49' => '570', 'iso_alpha3' => 'NIU' ],
            [ 'name' => 'Norfolk Island', 'm49' => '574', 'iso_alpha3' => 'NFK' ],
            [ 'name' => 'North Macedonia', 'm49' => '807', 'iso_alpha3' => 'MKD' ],
            [ 'name' => 'Northern Mariana Islands', 'm49' => '580', 'iso_alpha3' => 'MNP' ],
            [ 'name' => 'Norway', 'm49' => '578', 'iso_alpha3' => 'NOR' ],
            [ 'name' => 'Oman', 'm49' => '512', 'iso_alpha3' => 'OMN' ],
            [ 'name' => 'Pakistan', 'm49' => '586', 'iso_alpha3' => 'PAK' ],
            [ 'name' => 'Palau', 'm49' => '585', 'iso_alpha3' => 'PLW' ],
            [ 'name' => 'Panama', 'm49' => '591', 'iso_alpha3' => 'PAN' ],
            [ 'name' => 'Papua New Guinea', 'm49' => '598', 'iso_alpha3' => 'PNG' ],
            [ 'name' => 'Paraguay', 'm49' => '600', 'iso_alpha3' => 'PRY' ],
            [ 'name' => 'Peru', 'm49' => '604', 'iso_alpha3' => 'PER' ],
            [ 'name' => 'Philippines', 'm49' => '608', 'iso_alpha3' => 'PHL' ],
            [ 'name' => 'Pitcairn', 'm49' => '612', 'iso_alpha3' => 'PCN' ],
            [ 'name' => 'Poland', 'm49' => '616', 'iso_alpha3' => 'POL' ],
            [ 'name' => 'Portugal', 'm49' => '620', 'iso_alpha3' => 'PRT' ],
            [ 'name' => 'Puerto Rico', 'm49' => '630', 'iso_alpha3' => 'PRI' ],
            [ 'name' => 'Qatar', 'm49' => '634', 'iso_alpha3' => 'QAT' ],
            [ 'name' => 'Republic of Korea', 'm49' => '410', 'iso_alpha3' => 'KOR' ],
            [ 'name' => 'Republic of Moldova', 'm49' => '498', 'iso_alpha3' => 'MDA' ],
            [ 'name' => 'Réunion', 'm49' => '638', 'iso_alpha3' => 'REU' ],
            [ 'name' => 'Romania', 'm49' => '642', 'iso_alpha3' => 'ROU' ],
            [ 'name' => 'Russian Federation', 'm49' => '643', 'iso_alpha3' => 'RUS' ],
            [ 'name' => 'Rwanda', 'm49' => '646', 'iso_alpha3' => 'RWA' ],
            [ 'name' => 'Saint Barthélemy', 'm49' => '652', 'iso_alpha3' => 'BLM' ],
            [ 'name' => 'Saint Helena', 'm49' => '654', 'iso_alpha3' => 'SHN' ],
            [ 'name' => 'Saint Kitts and Nevis', 'm49' => '659', 'iso_alpha3' => 'KNA' ],
            [ 'name' => 'Saint Lucia', 'm49' => '662', 'iso_alpha3' => 'LCA' ],
            [ 'name' => 'Saint Martin (French Part)', 'm49' => '663', 'iso_alpha3' => 'MAF' ],
            [ 'name' => 'Saint Pierre and Miquelon', 'm49' => '666', 'iso_alpha3' => 'SPM' ],
            [ 'name' => 'Saint Vincent and the Grenadines', 'm49' => '670', 'iso_alpha3' => 'VCT' ],
            [ 'name' => 'Samoa', 'm49' => '882', 'iso_alpha3' => 'WSM' ],
            [ 'name' => 'San Marino', 'm49' => '674', 'iso_alpha3' => 'SMR' ],
            [ 'name' => 'Sao Tome and Principe', 'm49' => '678', 'iso_alpha3' => 'STP' ],
            [ 'name' => 'Saudi Arabia', 'm49' => '682', 'iso_alpha3' => 'SAU' ],
            [ 'name' => 'Senegal', 'm49' => '686', 'iso_alpha3' => 'SEN' ],
            [ 'name' => 'Serbia', 'm49' => '688', 'iso_alpha3' => 'SRB' ],
            [ 'name' => 'Seychelles', 'm49' => '690', 'iso_alpha3' => 'SYC' ],
            [ 'name' => 'Sierra Leone', 'm49' => '694', 'iso_alpha3' => 'SLE' ],
            [ 'name' => 'Singapore', 'm49' => '702', 'iso_alpha3' => 'SGP' ],
            [ 'name' => 'Sint Maarten (Dutch part)', 'm49' => '534', 'iso_alpha3' => 'SXM' ],
            [ 'name' => 'Slovakia', 'm49' => '703', 'iso_alpha3' => 'SVK' ],
            [ 'name' => 'Slovenia', 'm49' => '705', 'iso_alpha3' => 'SVN' ],
            [ 'name' => 'Solomon Islands', 'm49' => '090', 'iso_alpha3' => 'SLB' ],
            [ 'name' => 'Somalia', 'm49' => '706', 'iso_alpha3' => 'SOM' ],
            [ 'name' => 'South Africa', 'm49' => '710', 'iso_alpha3' => 'ZAF' ],
            [ 'name' => 'South Georgia and the South Sandwich Islands', 'm49' => '239', 'iso_alpha3' => 'SGS' ],
            [ 'name' => 'South Sudan', 'm49' => '728', 'iso_alpha3' => 'SSD' ],
            [ 'name' => 'Spain', 'm49' => '724', 'iso_alpha3' => 'ESP' ],
            [ 'name' => 'Sri Lanka', 'm49' => '144', 'iso_alpha3' => 'LKA' ],
            [ 'name' => 'State of Palestine', 'm49' => '275', 'iso_alpha3' => 'PSE' ],
            [ 'name' => 'Sudan', 'm49' => '729', 'iso_alpha3' => 'SDN' ],
            [ 'name' => 'Suriname', 'm49' => '740', 'iso_alpha3' => 'SUR' ],
            [ 'name' => 'Svalbard and Jan Mayen Islands', 'm49' => '744', 'iso_alpha3' => 'SJM' ],
            [ 'name' => 'Sweden', 'm49' => '752', 'iso_alpha3' => 'SWE' ],
            [ 'name' => 'Switzerland', 'm49' => '756', 'iso_alpha3' => 'CHE' ],
            [ 'name' => 'Syrian Arab Republic', 'm49' => '760', 'iso_alpha3' => 'SYR' ],
            [ 'name' => 'Tajikistan', 'm49' => '762', 'iso_alpha3' => 'TJK' ],
            [ 'name' => 'Thailand', 'm49' => '764', 'iso_alpha3' => 'THA' ],
            [ 'name' => 'Timor-Leste', 'm49' => '626', 'iso_alpha3' => 'TLS' ],
            [ 'name' => 'Togo', 'm49' => '768', 'iso_alpha3' => 'TGO' ],
            [ 'name' => 'Tokelau', 'm49' => '772', 'iso_alpha3' => 'TKL' ],
            [ 'name' => 'Tonga', 'm49' => '776', 'iso_alpha3' => 'TON' ],
            [ 'name' => 'Trinidad and Tobago', 'm49' => '780', 'iso_alpha3' => 'TTO' ],
            [ 'name' => 'Tunisia', 'm49' => '788', 'iso_alpha3' => 'TUN' ],
            [ 'name' => 'Türkiye', 'm49' => '792', 'iso_alpha3' => 'TUR' ],
            [ 'name' => 'Turkmenistan', 'm49' => '795', 'iso_alpha3' => 'TKM' ],
            [ 'name' => 'Turks and Caicos Islands', 'm49' => '796', 'iso_alpha3' => 'TCA' ],
            [ 'name' => 'Tuvalu', 'm49' => '798', 'iso_alpha3' => 'TUV' ],
            [ 'name' => 'Uganda', 'm49' => '800', 'iso_alpha3' => 'UGA' ],
            [ 'name' => 'Ukraine', 'm49' => '804', 'iso_alpha3' => 'UKR' ],
            [ 'name' => 'United Arab Emirates', 'm49' => '784', 'iso_alpha3' => 'ARE' ],
            [ 'name' => 'United Kingdom of Great Britain and Northern Ireland', 'm49' => '826', 'iso_alpha3' => 'GBR' ],
            [ 'name' => 'United Republic of Tanzania', 'm49' => '834', 'iso_alpha3' => 'TZA' ],
            [ 'name' => 'United States Minor Outlying Islands', 'm49' => '581', 'iso_alpha3' => 'UMI' ],
            [ 'name' => 'United States of America', 'm49' => '840', 'iso_alpha3' => 'USA' ],
            [ 'name' => 'United States Virgin Islands', 'm49' => '850', 'iso_alpha3' => 'VIR' ],
            [ 'name' => 'Uruguay', 'm49' => '858', 'iso_alpha3' => 'URY' ],
            [ 'name' => 'Uzbekistan', 'm49' => '860', 'iso_alpha3' => 'UZB' ],
            [ 'name' => 'Vanuatu', 'm49' => '548', 'iso_alpha3' => 'VUT' ],
            [ 'name' => 'Venezuela (Bolivarian Republic of)', 'm49' => '862', 'iso_alpha3' => 'VEN' ],
            [ 'name' => 'Viet Nam', 'm49' => '704', 'iso_alpha3' => 'VNM' ],
            [ 'name' => 'Wallis and Futuna Islands', 'm49' => '876', 'iso_alpha3' => 'WLF' ],
            [ 'name' => 'Western Sahara', 'm49' => '732', 'iso_alpha3' => 'ESH' ],
            [ 'name' => 'Yemen', 'm49' => '887', 'iso_alpha3' => 'YEM' ],
            [ 'name' => 'Zambia', 'm49' => '894', 'iso_alpha3' => 'ZMB' ],
            [ 'name' => 'Zimbabwe', 'm49' => '716', 'iso_alpha3' => 'ZWE' ],
        ];
        App\Models\Country::insert($data);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('countries');
    }
};
