<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    protected $database_tag = 'core_db';

    /**
     * Run the migrations.
     */
    public function up(): void
    {
        if (empty(config('app.' . $this->database_tag))) {
            throw new \Exception('app.'.$this->database_tag.' not defined in config\app.php file '
                . ' or CORE_DB_DATABASE not defined in .env file.'
            );
        }

        Schema::connection($this->database_tag)->create('countries', function (Blueprint $table) {
            $table->id();
            $table->string('name', 100)->unique();
            $table->string('m49', 3)->unique();
            $table->string('iso_alpha3', 3)->unique();
        });

        $data = [
            [ 'id' => 1,   'name' => 'Afghanistan',                        'm49' => '004', 'iso_alpha3' => 'AFG' ],
            [ 'id' => 2,   'name' => 'Åland Islands',                      'm49' => '248', 'iso_alpha3' => 'ALA' ],
            [ 'id' => 3,   'name' => 'Albania',                            'm49' => '008', 'iso_alpha3' => 'ALB' ],
            [ 'id' => 4,   'name' => 'Algeria',                            'm49' => '012', 'iso_alpha3' => 'DZA' ],
            [ 'id' => 5,   'name' => 'American Samoa',                     'm49' => '016', 'iso_alpha3' => 'ASM' ],
            [ 'id' => 6,   'name' => 'Andorra',                            'm49' => '020', 'iso_alpha3' => 'AND' ],
            [ 'id' => 7,   'name' => 'Angola',                             'm49' => '024', 'iso_alpha3' => 'AGO' ],
            [ 'id' => 8,   'name' => 'Anguilla',                           'm49' => '660', 'iso_alpha3' => 'AIA' ],
            [ 'id' => 9,   'name' => 'Antarctica',                         'm49' => '010', 'iso_alpha3' => 'ATA' ],
            [ 'id' => 10,  'name' => 'Antigua and Barbuda',                'm49' => '028', 'iso_alpha3' => 'ATG' ],
            [ 'id' => 11,  'name' => 'Argentina',                          'm49' => '032', 'iso_alpha3' => 'ARG' ],
            [ 'id' => 12,  'name' => 'Armenia',                            'm49' => '051', 'iso_alpha3' => 'ARM' ],
            [ 'id' => 13,  'name' => 'Aruba',                              'm49' => '533', 'iso_alpha3' => 'ABW' ],
            [ 'id' => 14,  'name' => 'Australia',                          'm49' => '036', 'iso_alpha3' => 'AUS' ],
            [ 'id' => 15,  'name' => 'Austria',                            'm49' => '040', 'iso_alpha3' => 'AUT' ],
            [ 'id' => 16,  'name' => 'Azerbaijan',                         'm49' => '031', 'iso_alpha3' => 'AZE' ],
            [ 'id' => 17,  'name' => 'Bahamas',                            'm49' => '044', 'iso_alpha3' => 'BHS' ],
            [ 'id' => 18,  'name' => 'Bahrain',                            'm49' => '048', 'iso_alpha3' => 'BHR' ],
            [ 'id' => 19,  'name' => 'Bangladesh',                         'm49' => '050', 'iso_alpha3' => 'BGD' ],
            [ 'id' => 20,  'name' => 'Barbados',                           'm49' => '052', 'iso_alpha3' => 'BRB' ],
            [ 'id' => 21,  'name' => 'Belarus',                            'm49' => '112', 'iso_alpha3' => 'BLR' ],
            [ 'id' => 22,  'name' => 'Belgium',                            'm49' => '056', 'iso_alpha3' => 'BEL' ],
            [ 'id' => 23,  'name' => 'Belize',                             'm49' => '084', 'iso_alpha3' => 'BLZ' ],
            [ 'id' => 24,  'name' => 'Benin',                              'm49' => '204', 'iso_alpha3' => 'BEN' ],
            [ 'id' => 25,  'name' => 'Bermuda',                            'm49' => '060', 'iso_alpha3' => 'BMU' ],
            [ 'id' => 26,  'name' => 'Bhutan',                             'm49' => '064', 'iso_alpha3' => 'BTN' ],
            [ 'id' => 27,  'name' => 'Bolivia (Plurinational State of)',   'm49' => '068', 'iso_alpha3' => 'BOL' ],
            [ 'id' => 28,  'name' => 'Bonaire, Sint Eustatius and Saba',   'm49' => '535', 'iso_alpha3' => 'BES' ],
            [ 'id' => 29,  'name' => 'Bosnia and Herzegovina',             'm49' => '070', 'iso_alpha3' => 'BIH' ],
            [ 'id' => 30,  'name' => 'Botswana',                           'm49' => '072', 'iso_alpha3' => 'BWA' ],
            [ 'id' => 31,  'name' => 'Bouvet Island',                      'm49' => '074', 'iso_alpha3' => 'BVT' ],
            [ 'id' => 32,  'name' => 'Brazil',                             'm49' => '076', 'iso_alpha3' => 'BRA' ],
            [ 'id' => 33,  'name' => 'British Indian Ocean Territory',     'm49' => '086', 'iso_alpha3' => 'IOT' ],
            [ 'id' => 34,  'name' => 'British Virgin Islands',             'm49' => '092', 'iso_alpha3' => 'VGB' ],
            [ 'id' => 35,  'name' => 'Brunei Darussalam',                  'm49' => '096', 'iso_alpha3' => 'BRN' ],
            [ 'id' => 36,  'name' => 'Bulgaria',                           'm49' => '100', 'iso_alpha3' => 'BGR' ],
            [ 'id' => 37,  'name' => 'Burkina Faso',                       'm49' => '854', 'iso_alpha3' => 'BFA' ],
            [ 'id' => 38,  'name' => 'Burundi',                            'm49' => '108', 'iso_alpha3' => 'BDI' ],
            [ 'id' => 39,  'name' => 'Cabo Verde',                         'm49' => '132', 'iso_alpha3' => 'CPV' ],
            [ 'id' => 40,  'name' => 'Cambodia',                           'm49' => '116', 'iso_alpha3' => 'KHM' ],
            [ 'id' => 41,  'name' => 'Cameroon',                           'm49' => '120', 'iso_alpha3' => 'CMR' ],
            [ 'id' => 42,  'name' => 'Canada',                             'm49' => '124', 'iso_alpha3' => 'CAN' ],
            [ 'id' => 43,  'name' => 'Cayman Islands',                     'm49' => '136', 'iso_alpha3' => 'CYM' ],
            [ 'id' => 44,  'name' => 'Central African Republic',           'm49' => '140', 'iso_alpha3' => 'CAF' ],
            [ 'id' => 45,  'name' => 'Chad',                               'm49' => '148', 'iso_alpha3' => 'TCD' ],
            [ 'id' => 46,  'name' => 'Chile',                              'm49' => '152', 'iso_alpha3' => 'CHL' ],
            [ 'id' => 47,  'name' => 'China',                              'm49' => '156', 'iso_alpha3' => 'CHN' ],
            [ 'id' => 48,  'name' => 'China, Hong Kong Special Administrative Region', 'm49' => '344', 'iso_alpha3' => 'HKG' ],
            [ 'id' => 49,  'name' => 'China, Macao Special Administrative Region', 'm49' => '446', 'iso_alpha3' => 'MAC' ],
            [ 'id' => 50,  'name' => 'Christmas Island',                   'm49' => '162', 'iso_alpha3' => 'CXR' ],
            [ 'id' => 51,  'name' => 'Cocos (Keeling) Islands',            'm49' => '166', 'iso_alpha3' => 'CCK' ],
            [ 'id' => 52,  'name' => 'Colombia',                           'm49' => '170', 'iso_alpha3' => 'COL' ],
            [ 'id' => 53,  'name' => 'Comoros',                            'm49' => '174', 'iso_alpha3' => 'COM' ],
            [ 'id' => 54,  'name' => 'Congo',                              'm49' => '178', 'iso_alpha3' => 'COG' ],
            [ 'id' => 55,  'name' => 'Cook Islands',                       'm49' => '184', 'iso_alpha3' => 'COK' ],
            [ 'id' => 56,  'name' => 'Costa Rica',                         'm49' => '188', 'iso_alpha3' => 'CRI' ],
            [ 'id' => 57,  'name' => 'Côte d’Ivoire',                      'm49' => '384', 'iso_alpha3' => 'CIV' ],
            [ 'id' => 58,  'name' => 'Croatia',                            'm49' => '191', 'iso_alpha3' => 'HRV' ],
            [ 'id' => 59,  'name' => 'Cuba',                               'm49' => '192', 'iso_alpha3' => 'CUB' ],
            [ 'id' => 60,  'name' => 'Curaçao',                            'm49' => '531', 'iso_alpha3' => 'CUW' ],
            [ 'id' => 61,  'name' => 'Cyprus',                             'm49' => '196', 'iso_alpha3' => 'CYP' ],
            [ 'id' => 62,  'name' => 'Czechia',                            'm49' => '203', 'iso_alpha3' => 'CZE' ],
            [ 'id' => 63,  'name' => 'Democratic People\'s Republic of Korea', 'm49' => '408', 'iso_alpha3' => 'PRK' ],
            [ 'id' => 64,  'name' => 'Democratic Republic of the Congo',   'm49' => '180', 'iso_alpha3' => 'COD' ],
            [ 'id' => 65,  'name' => 'Denmark',                            'm49' => '208', 'iso_alpha3' => 'DNK' ],
            [ 'id' => 66,  'name' => 'Djibouti',                           'm49' => '262', 'iso_alpha3' => 'DJI' ],
            [ 'id' => 67,  'name' => 'Dominica',                           'm49' => '212', 'iso_alpha3' => 'DMA' ],
            [ 'id' => 68,  'name' => 'Dominican Republic',                 'm49' => '214', 'iso_alpha3' => 'DOM' ],
            [ 'id' => 69,  'name' => 'Ecuador',                            'm49' => '218', 'iso_alpha3' => 'ECU' ],
            [ 'id' => 70,  'name' => 'Egypt',                              'm49' => '818', 'iso_alpha3' => 'EGY' ],
            [ 'id' => 71,  'name' => 'El Salvador',                        'm49' => '222', 'iso_alpha3' => 'SLV' ],
            [ 'id' => 72,  'name' => 'Equatorial Guinea',                  'm49' => '226', 'iso_alpha3' => 'GNQ' ],
            [ 'id' => 73,  'name' => 'Eritrea',                            'm49' => '232', 'iso_alpha3' => 'ERI' ],
            [ 'id' => 74,  'name' => 'Estonia',                            'm49' => '233', 'iso_alpha3' => 'EST' ],
            [ 'id' => 75,  'name' => 'Eswatini',                           'm49' => '748', 'iso_alpha3' => 'SWZ' ],
            [ 'id' => 76,  'name' => 'Ethiopia',                           'm49' => '231', 'iso_alpha3' => 'ETH' ],
            [ 'id' => 77,  'name' => 'Falkland Islands (Malvinas)',        'm49' => '238', 'iso_alpha3' => 'FLK' ],
            [ 'id' => 78,  'name' => 'Faroe Islands',                      'm49' => '234', 'iso_alpha3' => 'FRO' ],
            [ 'id' => 79,  'name' => 'Fiji',                               'm49' => '242', 'iso_alpha3' => 'FJI' ],
            [ 'id' => 80,  'name' => 'Finland',                            'm49' => '246', 'iso_alpha3' => 'FIN' ],
            [ 'id' => 81,  'name' => 'France',                             'm49' => '250', 'iso_alpha3' => 'FRA' ],
            [ 'id' => 82,  'name' => 'French Guiana',                      'm49' => '254', 'iso_alpha3' => 'GUF' ],
            [ 'id' => 83,  'name' => 'French Polynesia',                   'm49' => '258', 'iso_alpha3' => 'PYF' ],
            [ 'id' => 84,  'name' => 'French Southern Territories',        'm49' => '260', 'iso_alpha3' => 'ATF' ],
            [ 'id' => 85,  'name' => 'Gabon',                              'm49' => '266', 'iso_alpha3' => 'GAB' ],
            [ 'id' => 86,  'name' => 'Gambia',                             'm49' => '270', 'iso_alpha3' => 'GMB' ],
            [ 'id' => 87,  'name' => 'Georgia',                            'm49' => '268', 'iso_alpha3' => 'GEO' ],
            [ 'id' => 88,  'name' => 'Germany',                            'm49' => '276', 'iso_alpha3' => 'DEU' ],
            [ 'id' => 89,  'name' => 'Ghana',                              'm49' => '288', 'iso_alpha3' => 'GHA' ],
            [ 'id' => 90,  'name' => 'Gibraltar',                          'm49' => '292', 'iso_alpha3' => 'GIB' ],
            [ 'id' => 91,  'name' => 'Greece',                             'm49' => '300', 'iso_alpha3' => 'GRC' ],
            [ 'id' => 92,  'name' => 'Greenland',                          'm49' => '304', 'iso_alpha3' => 'GRL' ],
            [ 'id' => 93,  'name' => 'Grenada',                            'm49' => '308', 'iso_alpha3' => 'GRD' ],
            [ 'id' => 94,  'name' => 'Guadeloupe',                         'm49' => '312', 'iso_alpha3' => 'GLP' ],
            [ 'id' => 95,  'name' => 'Guam',                               'm49' => '316', 'iso_alpha3' => 'GUM' ],
            [ 'id' => 96,  'name' => 'Guatemala',                          'm49' => '320', 'iso_alpha3' => 'GTM' ],
            [ 'id' => 97,  'name' => 'Guernsey',                           'm49' => '831', 'iso_alpha3' => 'GGY' ],
            [ 'id' => 98,  'name' => 'Guinea',                             'm49' => '324', 'iso_alpha3' => 'GIN' ],
            [ 'id' => 99,  'name' => 'Guinea-Bissau',                      'm49' => '624', 'iso_alpha3' => 'GNB' ],
            [ 'id' => 100, 'name' => 'Guyana',                             'm49' => '328', 'iso_alpha3' => 'GUY' ],
            [ 'id' => 101, 'name' => 'Haiti',                              'm49' => '332', 'iso_alpha3' => 'HTI' ],
            [ 'id' => 102, 'name' => 'Heard Island and McDonald Islands',  'm49' => '334', 'iso_alpha3' => 'HMD' ],
            [ 'id' => 103, 'name' => 'Holy See',                           'm49' => '336', 'iso_alpha3' => 'VAT' ],
            [ 'id' => 104, 'name' => 'Honduras',                           'm49' => '340', 'iso_alpha3' => 'HND' ],
            [ 'id' => 105, 'name' => 'Hungary',                            'm49' => '348', 'iso_alpha3' => 'HUN' ],
            [ 'id' => 106, 'name' => 'Iceland',                            'm49' => '352', 'iso_alpha3' => 'ISL' ],
            [ 'id' => 107, 'name' => 'India',                              'm49' => '356', 'iso_alpha3' => 'IND' ],
            [ 'id' => 108, 'name' => 'Indonesia',                          'm49' => '360', 'iso_alpha3' => 'IDN' ],
            [ 'id' => 109, 'name' => 'Iran (Islamic Republic of)',         'm49' => '364', 'iso_alpha3' => 'IRN' ],
            [ 'id' => 110, 'name' => 'Iraq',                               'm49' => '368', 'iso_alpha3' => 'IRQ' ],
            [ 'id' => 111, 'name' => 'Ireland',                            'm49' => '372', 'iso_alpha3' => 'IRL' ],
            [ 'id' => 112, 'name' => 'Isle of Man',                        'm49' => '833', 'iso_alpha3' => 'IMN' ],
            [ 'id' => 113, 'name' => 'Israel',                             'm49' => '376', 'iso_alpha3' => 'ISR' ],
            [ 'id' => 114, 'name' => 'Italy',                              'm49' => '380', 'iso_alpha3' => 'ITA' ],
            [ 'id' => 115, 'name' => 'Jamaica',                            'm49' => '388', 'iso_alpha3' => 'JAM' ],
            [ 'id' => 116, 'name' => 'Japan',                              'm49' => '392', 'iso_alpha3' => 'JPN' ],
            [ 'id' => 117, 'name' => 'Jersey',                             'm49' => '832', 'iso_alpha3' => 'JEY' ],
            [ 'id' => 118, 'name' => 'Jordan',                             'm49' => '400', 'iso_alpha3' => 'JOR' ],
            [ 'id' => 119, 'name' => 'Kazakhstan',                         'm49' => '398', 'iso_alpha3' => 'KAZ' ],
            [ 'id' => 120, 'name' => 'Kenya',                              'm49' => '404', 'iso_alpha3' => 'KEN' ],
            [ 'id' => 121, 'name' => 'Kiribati',                           'm49' => '296', 'iso_alpha3' => 'KIR' ],
            [ 'id' => 122, 'name' => 'Kuwait',                             'm49' => '414', 'iso_alpha3' => 'KWT' ],
            [ 'id' => 123, 'name' => 'Kyrgyzstan',                         'm49' => '417', 'iso_alpha3' => 'KGZ' ],
            [ 'id' => 124, 'name' => 'Lao People\'s Democratic Republic',  'm49' => '418', 'iso_alpha3' => 'LAO' ],
            [ 'id' => 125, 'name' => 'Latvia',                             'm49' => '428', 'iso_alpha3' => 'LVA' ],
            [ 'id' => 126, 'name' => 'Lebanon',                            'm49' => '422', 'iso_alpha3' => 'LBN' ],
            [ 'id' => 127, 'name' => 'Lesotho',                            'm49' => '426', 'iso_alpha3' => 'LSO' ],
            [ 'id' => 128, 'name' => 'Liberia',                            'm49' => '430', 'iso_alpha3' => 'LBR' ],
            [ 'id' => 129, 'name' => 'Libya',                              'm49' => '434', 'iso_alpha3' => 'LBY' ],
            [ 'id' => 130, 'name' => 'Liechtenstein',                      'm49' => '438', 'iso_alpha3' => 'LIE' ],
            [ 'id' => 131, 'name' => 'Lithuania',                          'm49' => '440', 'iso_alpha3' => 'LTU' ],
            [ 'id' => 132, 'name' => 'Luxembourg',                         'm49' => '442', 'iso_alpha3' => 'LUX' ],
            [ 'id' => 133, 'name' => 'Madagascar',                         'm49' => '450', 'iso_alpha3' => 'MDG' ],
            [ 'id' => 134, 'name' => 'Malawi',                             'm49' => '454', 'iso_alpha3' => 'MWI' ],
            [ 'id' => 135, 'name' => 'Malaysia',                           'm49' => '458', 'iso_alpha3' => 'MYS' ],
            [ 'id' => 136, 'name' => 'Maldives',                           'm49' => '462', 'iso_alpha3' => 'MDV' ],
            [ 'id' => 137, 'name' => 'Mali',                               'm49' => '466', 'iso_alpha3' => 'MLI' ],
            [ 'id' => 138, 'name' => 'Malta',                              'm49' => '470', 'iso_alpha3' => 'MLT' ],
            [ 'id' => 139, 'name' => 'Marshall Islands',                   'm49' => '584', 'iso_alpha3' => 'MHL' ],
            [ 'id' => 140, 'name' => 'Martinique',                         'm49' => '474', 'iso_alpha3' => 'MTQ' ],
            [ 'id' => 141, 'name' => 'Mauritania',                         'm49' => '478', 'iso_alpha3' => 'MRT' ],
            [ 'id' => 142, 'name' => 'Mauritius',                          'm49' => '480', 'iso_alpha3' => 'MUS' ],
            [ 'id' => 143, 'name' => 'Mayotte',                            'm49' => '175', 'iso_alpha3' => 'MYT' ],
            [ 'id' => 144, 'name' => 'Mexico',                             'm49' => '484', 'iso_alpha3' => 'MEX' ],
            [ 'id' => 145, 'name' => 'Micronesia (Federated States of)',   'm49' => '583', 'iso_alpha3' => 'FSM' ],
            [ 'id' => 146, 'name' => 'Monaco',                             'm49' => '492', 'iso_alpha3' => 'MCO' ],
            [ 'id' => 147, 'name' => 'Mongolia',                           'm49' => '496', 'iso_alpha3' => 'MNG' ],
            [ 'id' => 148, 'name' => 'Montenegro',                         'm49' => '499', 'iso_alpha3' => 'MNE' ],
            [ 'id' => 149, 'name' => 'Montserrat',                         'm49' => '500', 'iso_alpha3' => 'MSR' ],
            [ 'id' => 150, 'name' => 'Morocco',                            'm49' => '504', 'iso_alpha3' => 'MAR' ],
            [ 'id' => 151, 'name' => 'Mozambique',                         'm49' => '508', 'iso_alpha3' => 'MOZ' ],
            [ 'id' => 152, 'name' => 'Myanmar',                            'm49' => '104', 'iso_alpha3' => 'MMR' ],
            [ 'id' => 153, 'name' => 'Namibia',                            'm49' => '516', 'iso_alpha3' => 'NAM' ],
            [ 'id' => 154, 'name' => 'Nauru',                              'm49' => '520', 'iso_alpha3' => 'NRU' ],
            [ 'id' => 155, 'name' => 'Nepal',                              'm49' => '524', 'iso_alpha3' => 'NPL' ],
            [ 'id' => 156, 'name' => 'Netherlands (Kingdom of the)',       'm49' => '528', 'iso_alpha3' => 'NLD' ],
            [ 'id' => 157, 'name' => 'New Caledonia',                      'm49' => '540', 'iso_alpha3' => 'NCL' ],
            [ 'id' => 158, 'name' => 'New Zealand',                        'm49' => '554', 'iso_alpha3' => 'NZL' ],
            [ 'id' => 159, 'name' => 'Nicaragua',                          'm49' => '558', 'iso_alpha3' => 'NIC' ],
            [ 'id' => 160, 'name' => 'Niger',                              'm49' => '562', 'iso_alpha3' => 'NER' ],
            [ 'id' => 161, 'name' => 'Nigeria',                            'm49' => '566', 'iso_alpha3' => 'NGA' ],
            [ 'id' => 162, 'name' => 'Niue',                               'm49' => '570', 'iso_alpha3' => 'NIU' ],
            [ 'id' => 163, 'name' => 'Norfolk Island',                     'm49' => '574', 'iso_alpha3' => 'NFK' ],
            [ 'id' => 164, 'name' => 'North Macedonia',                    'm49' => '807', 'iso_alpha3' => 'MKD' ],
            [ 'id' => 165, 'name' => 'Northern Mariana Islands',           'm49' => '580', 'iso_alpha3' => 'MNP' ],
            [ 'id' => 166, 'name' => 'Norway',                             'm49' => '578', 'iso_alpha3' => 'NOR' ],
            [ 'id' => 167, 'name' => 'Oman',                               'm49' => '512', 'iso_alpha3' => 'OMN' ],
            [ 'id' => 168, 'name' => 'Pakistan',                           'm49' => '586', 'iso_alpha3' => 'PAK' ],
            [ 'id' => 169, 'name' => 'Palau',                              'm49' => '585', 'iso_alpha3' => 'PLW' ],
            [ 'id' => 170, 'name' => 'Panama',                             'm49' => '591', 'iso_alpha3' => 'PAN' ],
            [ 'id' => 171, 'name' => 'Papua New Guinea',                   'm49' => '598', 'iso_alpha3' => 'PNG' ],
            [ 'id' => 172, 'name' => 'Paraguay',                           'm49' => '600', 'iso_alpha3' => 'PRY' ],
            [ 'id' => 173, 'name' => 'Peru',                               'm49' => '604', 'iso_alpha3' => 'PER' ],
            [ 'id' => 174, 'name' => 'Philippines',                        'm49' => '608', 'iso_alpha3' => 'PHL' ],
            [ 'id' => 175, 'name' => 'Pitcairn',                           'm49' => '612', 'iso_alpha3' => 'PCN' ],
            [ 'id' => 176, 'name' => 'Poland',                             'm49' => '616', 'iso_alpha3' => 'POL' ],
            [ 'id' => 177, 'name' => 'Portugal',                           'm49' => '620', 'iso_alpha3' => 'PRT' ],
            [ 'id' => 178, 'name' => 'Puerto Rico',                        'm49' => '630', 'iso_alpha3' => 'PRI' ],
            [ 'id' => 179, 'name' => 'Qatar',                              'm49' => '634', 'iso_alpha3' => 'QAT' ],
            [ 'id' => 180, 'name' => 'Republic of Korea',                  'm49' => '410', 'iso_alpha3' => 'KOR' ],
            [ 'id' => 181, 'name' => 'Republic of Moldova',                'm49' => '498', 'iso_alpha3' => 'MDA' ],
            [ 'id' => 182, 'name' => 'Réunion',                            'm49' => '638', 'iso_alpha3' => 'REU' ],
            [ 'id' => 183, 'name' => 'Romania',                            'm49' => '642', 'iso_alpha3' => 'ROU' ],
            [ 'id' => 184, 'name' => 'Russian Federation',                 'm49' => '643', 'iso_alpha3' => 'RUS' ],
            [ 'id' => 185, 'name' => 'Rwanda',                             'm49' => '646', 'iso_alpha3' => 'RWA' ],
            [ 'id' => 186, 'name' => 'Saint Barthélemy',                   'm49' => '652', 'iso_alpha3' => 'BLM' ],
            [ 'id' => 187, 'name' => 'Saint Helena',                       'm49' => '654', 'iso_alpha3' => 'SHN' ],
            [ 'id' => 188, 'name' => 'Saint Kitts and Nevis',              'm49' => '659', 'iso_alpha3' => 'KNA' ],
            [ 'id' => 189, 'name' => 'Saint Lucia',                        'm49' => '662', 'iso_alpha3' => 'LCA' ],
            [ 'id' => 190, 'name' => 'Saint Martin (French Part)',         'm49' => '663', 'iso_alpha3' => 'MAF' ],
            [ 'id' => 191, 'name' => 'Saint Pierre and Miquelon',          'm49' => '666', 'iso_alpha3' => 'SPM' ],
            [ 'id' => 192, 'name' => 'Saint Vincent and the Grenadines',   'm49' => '670', 'iso_alpha3' => 'VCT' ],
            [ 'id' => 193, 'name' => 'Samoa',                              'm49' => '882', 'iso_alpha3' => 'WSM' ],
            [ 'id' => 194, 'name' => 'San Marino',                         'm49' => '674', 'iso_alpha3' => 'SMR' ],
            [ 'id' => 195, 'name' => 'Sao Tome and Principe',              'm49' => '678', 'iso_alpha3' => 'STP' ],
            [ 'id' => 196, 'name' => 'Saudi Arabia',                       'm49' => '682', 'iso_alpha3' => 'SAU' ],
            [ 'id' => 197, 'name' => 'Senegal',                            'm49' => '686', 'iso_alpha3' => 'SEN' ],
            [ 'id' => 198, 'name' => 'Serbia',                             'm49' => '688', 'iso_alpha3' => 'SRB' ],
            [ 'id' => 199, 'name' => 'Seychelles',                         'm49' => '690', 'iso_alpha3' => 'SYC' ],
            [ 'id' => 200, 'name' => 'Sierra Leone',                       'm49' => '694', 'iso_alpha3' => 'SLE' ],
            [ 'id' => 201, 'name' => 'Singapore',                          'm49' => '702', 'iso_alpha3' => 'SGP' ],
            [ 'id' => 202, 'name' => 'Sint Maarten (Dutch part)',          'm49' => '534', 'iso_alpha3' => 'SXM' ],
            [ 'id' => 203, 'name' => 'Slovakia',                           'm49' => '703', 'iso_alpha3' => 'SVK' ],
            [ 'id' => 204, 'name' => 'Slovenia',                           'm49' => '705', 'iso_alpha3' => 'SVN' ],
            [ 'id' => 205, 'name' => 'Solomon Islands',                    'm49' => '090', 'iso_alpha3' => 'SLB' ],
            [ 'id' => 206, 'name' => 'Somalia',                            'm49' => '706', 'iso_alpha3' => 'SOM' ],
            [ 'id' => 207, 'name' => 'South Africa',                       'm49' => '710', 'iso_alpha3' => 'ZAF' ],
            [ 'id' => 208, 'name' => 'South Georgia and the South Sandwich Islands', 'm49' => '239', 'iso_alpha3' => 'SGS' ],
            [ 'id' => 209, 'name' => 'South Sudan',                        'm49' => '728', 'iso_alpha3' => 'SSD' ],
            [ 'id' => 210, 'name' => 'Spain',                              'm49' => '724', 'iso_alpha3' => 'ESP' ],
            [ 'id' => 211, 'name' => 'Sri Lanka',                          'm49' => '144', 'iso_alpha3' => 'LKA' ],
            [ 'id' => 212, 'name' => 'State of Palestine',                 'm49' => '275', 'iso_alpha3' => 'PSE' ],
            [ 'id' => 213, 'name' => 'Sudan',                              'm49' => '729', 'iso_alpha3' => 'SDN' ],
            [ 'id' => 214, 'name' => 'Suriname',                           'm49' => '740', 'iso_alpha3' => 'SUR' ],
            [ 'id' => 215, 'name' => 'Svalbard and Jan Mayen Islands',     'm49' => '744', 'iso_alpha3' => 'SJM' ],
            [ 'id' => 216, 'name' => 'Sweden',                             'm49' => '752', 'iso_alpha3' => 'SWE' ],
            [ 'id' => 217, 'name' => 'Switzerland',                        'm49' => '756', 'iso_alpha3' => 'CHE' ],
            [ 'id' => 218, 'name' => 'Syrian Arab Republic',               'm49' => '760', 'iso_alpha3' => 'SYR' ],
            [ 'id' => 219, 'name' => 'Tajikistan',                         'm49' => '762', 'iso_alpha3' => 'TJK' ],
            [ 'id' => 220, 'name' => 'Thailand',                           'm49' => '764', 'iso_alpha3' => 'THA' ],
            [ 'id' => 221, 'name' => 'Timor-Leste',                        'm49' => '626', 'iso_alpha3' => 'TLS' ],
            [ 'id' => 222, 'name' => 'Togo',                               'm49' => '768', 'iso_alpha3' => 'TGO' ],
            [ 'id' => 223, 'name' => 'Tokelau',                            'm49' => '772', 'iso_alpha3' => 'TKL' ],
            [ 'id' => 224, 'name' => 'Tonga',                              'm49' => '776', 'iso_alpha3' => 'TON' ],
            [ 'id' => 225, 'name' => 'Trinidad and Tobago',                'm49' => '780', 'iso_alpha3' => 'TTO' ],
            [ 'id' => 226, 'name' => 'Tunisia',                            'm49' => '788', 'iso_alpha3' => 'TUN' ],
            [ 'id' => 227, 'name' => 'Türkiye',                            'm49' => '792', 'iso_alpha3' => 'TUR' ],
            [ 'id' => 228, 'name' => 'Turkmenistan',                       'm49' => '795', 'iso_alpha3' => 'TKM' ],
            [ 'id' => 229, 'name' => 'Turks and Caicos Islands',           'm49' => '796', 'iso_alpha3' => 'TCA' ],
            [ 'id' => 230, 'name' => 'Tuvalu',                             'm49' => '798', 'iso_alpha3' => 'TUV' ],
            [ 'id' => 231, 'name' => 'Uganda',                             'm49' => '800', 'iso_alpha3' => 'UGA' ],
            [ 'id' => 232, 'name' => 'Ukraine',                            'm49' => '804', 'iso_alpha3' => 'UKR' ],
            [ 'id' => 233, 'name' => 'United Arab Emirates',               'm49' => '784', 'iso_alpha3' => 'ARE' ],
            [ 'id' => 234, 'name' => 'United Kingdom of Great Britain and Northern Ireland', 'm49' => '826', 'iso_alpha3' => 'GBR' ],
            [ 'id' => 235, 'name' => 'United Republic of Tanzania',        'm49' => '834', 'iso_alpha3' => 'TZA' ],
            [ 'id' => 236, 'name' => 'United States Minor Outlying Islands', 'm49' => '581', 'iso_alpha3' => 'UMI' ],
            [ 'id' => 237, 'name' => 'United States of America',           'm49' => '840', 'iso_alpha3' => 'USA' ],
            [ 'id' => 238, 'name' => 'United States Virgin Islands',       'm49' => '850', 'iso_alpha3' => 'VIR' ],
            [ 'id' => 239, 'name' => 'Uruguay',                            'm49' => '858', 'iso_alpha3' => 'URY' ],
            [ 'id' => 240, 'name' => 'Uzbekistan',                         'm49' => '860', 'iso_alpha3' => 'UZB' ],
            [ 'id' => 241, 'name' => 'Vanuatu',                            'm49' => '548', 'iso_alpha3' => 'VUT' ],
            [ 'id' => 242, 'name' => 'Venezuela (Bolivarian Republic of)', 'm49' => '862', 'iso_alpha3' => 'VEN' ],
            [ 'id' => 243, 'name' => 'Viet Nam',                           'm49' => '704', 'iso_alpha3' => 'VNM' ],
            [ 'id' => 244, 'name' => 'Wallis and Futuna Islands',          'm49' => '876', 'iso_alpha3' => 'WLF' ],
            [ 'id' => 245, 'name' => 'Western Sahara',                     'm49' => '732', 'iso_alpha3' => 'ESH' ],
            [ 'id' => 246, 'name' => 'Yemen',                              'm49' => '887', 'iso_alpha3' => 'YEM' ],
            [ 'id' => 247, 'name' => 'Zambia',                             'm49' => '894', 'iso_alpha3' => 'ZMB' ],
            [ 'id' => 248, 'name' => 'Zimbabwe',                           'm49' => '716', 'iso_alpha3' => 'ZWE' ],
        ];

        \App\Models\System\Country::insert($data);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::connection($this->database_tag)->dropIfExists('countries');
    }
};
