<?php

use App\Models\Admin;
use App\Models\Resource;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('resources', function (Blueprint $table) {
            $table->id();
            $table->foreignIdFor(\App\Models\Database::class);
            $table->string('name', 50);
            $table->string('table', 50);
            $table->string('title', 50);
            $table->string('plural', 50);
            $table->tinyInteger('guest')->default(0);
            $table->tinyInteger('user')->default(0);
            $table->tinyInteger('admin')->default(0);
            $table->string('icon', 50)->nullable();
            $table->integer('sequence')->default(0);
            $table->tinyInteger('public')->default(1);
            $table->tinyInteger('readonly')->default(0);
            $table->tinyInteger('root')->default(1);
            $table->tinyInteger('disabled')->default(0);
            $table->foreignIdFor( Admin::class);
            $table->timestamps();
        });

        $data = [
            /*
             * core database
             */
            [
                'database_id' => 1,
                'name'        => 'admin',
                'table'       => 'admins',
                'title'       => 'Admin',
                'plural'      => 'Admins',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-user-plus',
                'sequence'    => 1010,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 1,
                'name'        => 'user',
                'table'       => 'users',
                'title'       => 'User',
                'plural'      => 'Users',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-user',
                'sequence'    => 1020,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 1,
                'name'        => 'message',
                'table'       => 'messages',
                'title'       => 'Message',
                'plural'      => 'Messages',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-envelope',
                'sequence'    => 1030,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],

            /*
             * dictionary database
             */
            [
                'database_id' => 2,
                'name'        => 'category',
                'table'       => 'categories',
                'title'       => 'Category',
                'plural'      => 'Categories',
                'guest'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'icon'        => 'fa-chevron-circle-right',
                'sequence'    => 2010,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 2,
                'name'        => 'database',
                'table'       => 'databases',
                'title'       => 'Database',
                'plural'      => 'Databases',
                'guest'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'icon'        => 'fa-chevron-circle-right',
                'sequence'    => 2020,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 2,
                'name'        => 'framework',
                'table'       => 'frameworks',
                'title'       => 'Framework',
                'plural'      => 'Frameworks',
                'guest'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'icon'        => 'fa-chevron-circle-right',
                'sequence'    => 2030,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 2,
                'name'        => 'language',
                'table'       => 'languages',
                'title'       => 'Language',
                'plural'      => 'Languages',
                'guest'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'icon'        => 'fa-chevron-circle-right',
                'sequence'    => 2040,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 2,
                'name'        => 'library',
                'table'       => 'libraries',
                'title'       => 'Library',
                'plural'      => 'Libraries',
                'guest'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'icon'        => 'fa-chevron-circle-right',
                'sequence'    => 2050,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 2,
                'name'        => 'operating-system',
                'table'       => 'operating_systems',
                'title'       => 'Operating System',
                'plural'      => 'Operating Systems',
                'guest'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'icon'        => 'fa-chevron-circle-right',
                'sequence'    => 2060,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 2,
                'name'        => 'server',
                'table'       => 'servers',
                'title'       => 'Server',
                'plural'      => 'Servers',
                'guest'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'icon'        => 'fa-chevron-circle-right',
                'sequence'    => 2070,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 2,
                'name'        => 'stack',
                'table'       => 'stacks',
                'title'       => 'Stack',
                'plural'      => 'Stacks',
                'guest'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'icon'        => 'fa-chevron-circle-right',
                'sequence'    => 2080,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],

            /*
             * career database
             */
            [
                'database_id' => 3,
                'name'        => 'application',
                'table'       => 'applications',
                'title'       => 'Application',
                'plural'      => 'Applications',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-thumbtack',
                'sequence'    => 3010,
                'public'      => 0,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'name'        => 'communication',
                'table'       => 'communications',
                'title'       => 'Communication',
                'plural'      => 'Communications',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-phone',
                'sequence'    => 3020,
                'public'      => 0,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'name'        => 'company',
                'table'       => 'companies',
                'title'       => 'Company',
                'plural'      => 'Companies',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-chart-line',
                'sequence'    => 3030,
                'public'      => 0,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'name'        => 'contact',
                'table'       => 'contacts',
                'title'       => 'Contact',
                'plural'      => 'Contacts',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-address-book',
                'sequence'    => 3040,
                'public'      => 0,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'name'        => 'cover-letter',
                'table'       => 'cover_letters',
                'title'       => 'Cover Letter',
                'plural'      => 'Cover Letters',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-file-text',
                'sequence'    => 3050,
                'public'      => 0,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'name'        => 'industry',
                'table'       => 'industries',
                'title'       => 'Industry',
                'plural'      => 'Industries',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-industry',
                'sequence'    => 3060,
                'public'      => 0,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'name'        => 'job',
                'table'       => 'jobs',
                'title'       => 'Job',
                'plural'      => 'Jobs',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-briefcase',
                'sequence'    => 3070,
                'public'      => 0,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'name'        => 'job-coworker',
                'table'       => 'job_coworkers',
                'title'       => 'Job Coworker',
                'plural'      => 'Job Coworkers',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-users',
                'sequence'    => 3080,
                'public'      => 0,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'name'        => 'job-task',
                'table'       => 'job_tasks',
                'title'       => 'Job Task',
                'plural'      => 'Job Tasks',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-cogs',
                'sequence'    => 3090,
                'public'      => 0,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'name'        => 'job-board',
                'table'       => 'job_boards',
                'title'       => 'Job Board',
                'plural'      => 'Job Boards',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-clipboard',
                'sequence'    => 3100,
                'public'      => 0,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'name'        => 'note',
                'table'       => 'notes',
                'title'       => 'Note',
                'plural'      => 'Notes',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-sticky-note',
                'sequence'    => 3090,
                'public'      => 0,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'name'        => 'reference',
                'table'       => 'references',
                'title'       => 'Reference',
                'plural'      => 'References',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-address-card',
                'sequence'    => 3100,
                'public'      => 0,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'name'        => 'resume',
                'table'       => 'resumes',
                'title'       => 'Resume',
                'plural'      => 'Resumes',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-file',
                'sequence'    => 3110,
                'public'      => 0,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'name'        => 'skill',
                'table'       => 'skills',
                'title'       => 'Skill',
                'plural'      => 'Skills',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-certificate',
                'sequence'    => 3120,
                'public'      => 0,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],

            /*
             * portfolio database
             */
            [
                'database_id' => 4,
                'name'        => 'academy',
                'table'       => 'academies',
                'title'       => 'Academy',
                'plural'      => 'Academies',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-school',
                'sequence'    => 4010,
                'public'      => 0,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'name'        => 'art',
                'table'       => 'art',
                'title'       => 'Art',
                'plural'      => 'Art',
                'guest'       => 1,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-image',
                'sequence'    => 4020,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'name'        => 'certification',
                'table'       => 'certifications',
                'title'       => 'Certification',
                'plural'      => 'Certifications',
                'guest'       => 1,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-graduation-cap',
                'sequence'    => 4030,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'name'        => 'course',
                'table'       => 'courses',
                'title'       => 'Course',
                'plural'      => 'Courses',
                'guest'       => 1,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-chalkboard',
                'sequence'    => 4040,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'name'        => 'ingredient',
                'table'       => 'ingredients',
                'title'       => 'Ingredient',
                'plural'      => 'Ingredients',
                'guest'       => 1,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-pizza-slice',
                'sequence'    => 4050,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'name'        => 'link',
                'table'       => 'links',
                'title'       => 'Link',
                'plural'      => 'Links',
                'guest'       => 1,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-link',
                'sequence'    => 4060,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'name'        => 'music',
                'table'       => 'music',
                'title'       => 'Music',
                'plural'      => 'Music',
                'guest'       => 1,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-music',
                'sequence'    => 4070,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'name'        => 'project',
                'table'       => 'projects',
                'title'       => 'Project',
                'plural'      => 'Projects',
                'guest'       => 1,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-wrench',
                'sequence'    => 4080,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'name'        => 'reading',
                'table'       => 'readings',
                'title'       => 'Reading',
                'plural'      => 'Readings',
                'guest'       => 1,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-book',
                'sequence'    => 4090,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'name'        => 'recipe',
                'table'       => 'recipes',
                'title'       => 'Recipe',
                'plural'      => 'Recipes',
                'guest'       => 1,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-cutlery',
                'sequence'    => 4100,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'name'        => 'unit',
                'table'       => 'units',
                'title'       => 'Unit',
                'plural'      => 'Units',
                'guest'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-video-camera',
                'sequence'    => 4110,
                'public'      => 0,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'name'        => 'video',
                'table'       => 'videos',
                'title'       => 'Video',
                'plural'      => 'Videos',
                'guest'       => 1,
                'user'        => 0,
                'admin'       => 1,
                'icon'        => 'fa-video-camera',
                'sequence'    => 4120,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
        ];

        for ($i=0; $i<count($data); $i++) {
            Resource::insert($data[$i]);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('resources');
    }
};
