<?php

use App\Models\Admin;
use App\Models\Resource;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('resources', function (Blueprint $table) {
            $table->id();
            $table->foreignIdFor(\App\Models\Database::class);
            $table->string('type', 50);
            $table->string('name', 50);
            $table->string('plural', 50);
            $table->tinyInteger('front')->default(0);
            $table->tinyInteger('user')->default(0);
            $table->tinyInteger('admin')->default(0);
            $table->string('section', 50);
            $table->string('icon', 50)->nullable();
            $table->integer('sequence')->default(0);
            $table->tinyInteger('public')->default(1);
            $table->tinyInteger('readonly')->default(0);
            $table->tinyInteger('root')->default(1);
            $table->tinyInteger('disabled')->default(0);
            $table->foreignIdFor( Admin::class);
            $table->timestamps();
        });

        $data = [
            // core database
            [
                'database_id' => 1,
                'type'        => 'admin',
                'name'        => 'Admin',
                'plural'      => 'Admins',
                'front'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'section'     => 'System',
                'icon'        => 'fa-user-plus',
                'sequence'    => 1010,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 1,
                'type'        => 'user',
                'name'        => 'User',
                'plural'      => 'Users',
                'front'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'section'     => 'System',
                'icon'        => 'fa-user',
                'sequence'    => 1020,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 1,
                'type'        => 'message',
                'name'        => 'Message',
                'plural'      => 'Messages',
                'front'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'section'     => 'System',
                'icon'        => 'fa-user',
                'sequence'    => 1030,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],

            // dictionary database
            [
                'database_id' => 2,
                'type'        => 'category',
                'name'        => 'Category',
                'plural'      => 'Categories',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Dictionary',
                'icon'        => 'fa-chevron-circle-right',
                'sequence'    => 2010,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 2,
                'type'        => 'database',
                'name'        => 'Database',
                'plural'      => 'Databases',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Dictionary',
                'icon'        => 'fa-chevron-circle-right',
                'sequence'    => 2020,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 2,
                'type'        => 'framework',
                'name'        => 'Framework',
                'plural'      => 'Frameworks',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Dictionary',
                'icon'        => 'fa-chevron-circle-right',
                'sequence'    => 2030,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 2,
                'type'        => 'language',
                'name'        => 'Language',
                'plural'      => 'Languages',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Dictionary',
                'icon'        => 'fa-chevron-circle-right',
                'sequence'    => 2040,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 2,
                'type'        => 'library',
                'name'        => 'Library',
                'plural'      => 'Libraries',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Dictionary',
                'icon'        => 'fa-chevron-circle-right',
                'sequence'    => 2050,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 2,
                'type'        => 'operating-system',
                'name'        => 'Operating System',
                'plural'      => 'Operating Systems',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Dictionary',
                'icon'        => 'fa-chevron-circle-right',
                'sequence'    => 2060,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 2,
                'type'        => 'server',
                'name'        => 'Server',
                'plural'      => 'Servers',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Dictionary',
                'icon'        => 'fa-chevron-circle-right',
                'sequence'    => 2070,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 2,
                'type'        => 'stack',
                'name'        => 'Stack',
                'plural'      => 'Stacks',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Dictionary',
                'icon'        => 'fa-chevron-circle-right',
                'sequence'    => 2080,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],

            // career database
            [
                'database_id' => 3,
                'type'        => 'application',
                'name'        => 'Application',
                'plural'      => 'Applications',
                'front'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'section'     => 'Career',
                'icon'        => 'fa-thumbtack',
                'sequence'    => 3010,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'type'        => 'communication',
                'name'        => 'Communication',
                'plural'      => 'Communications',
                'front'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'section'     => 'Career',
                'icon'        => 'fa-phone',
                'sequence'    => 3020,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'type'        => 'company',
                'name'        => 'Company',
                'plural'      => 'Companies',
                'front'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'section'     => 'Career',
                'icon'        => 'fa-chart-line',
                'sequence'    => 3030,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'type'        => 'contact',
                'name'        => 'Contact',
                'plural'      => 'Contacts',
                'front'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'section'     => 'Career',
                'icon'        => 'fa-address-book',
                'sequence'    => 3040,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'type'        => 'cover-letter',
                'name'        => 'Cover Letter',
                'plural'      => 'Cover Letters',
                'front'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'section'     => 'Career',
                'icon'        => 'fa-file-text',
                'sequence'    => 3050,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'type'        => 'industry',
                'name'        => 'Industry',
                'plural'      => 'Industries',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Career',
                'icon'        => 'fa-industry',
                'sequence'    => 3060,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'type'        => 'job-board',
                'name'        => 'Job Board',
                'plural'      => 'Job Boards',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Career',
                'icon'        => 'fa-clipboard',
                'sequence'    => 3070,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'type'        => 'job',
                'name'        => 'Job',
                'plural'      => 'Jobs',
                'front'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'section'     => 'Career',
                'icon'        => 'fa-briefcase',
                'sequence'    => 3080,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'type'        => 'note',
                'name'        => 'Note',
                'plural'      => 'Notes',
                'front'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'section'     => 'Career',
                'icon'        => 'fa-sticky-note',
                'sequence'    => 3090,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'type'        => 'reference',
                'name'        => 'Reference',
                'plural'      => 'References',
                'front'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'section'     => 'Career',
                'icon'        => 'fa-address-card',
                'sequence'    => 3100,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'type'        => 'resume',
                'name'        => 'Resume',
                'plural'      => 'Resumes',
                'front'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'section'     => 'Career',
                'icon'        => 'fa-file',
                'sequence'    => 3110,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 3,
                'type'        => 'skill',
                'name'        => 'Skill',
                'plural'      => 'Skills',
                'front'       => 0,
                'user'        => 0,
                'admin'       => 1,
                'section'     => 'Career',
                'icon'        => 'fa-certificate',
                'sequence'    => 3120,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],

            // portfolio database
            [
                'database_id' => 4,
                'type'        => 'academy',
                'name'        => 'Academy',
                'plural'      => 'Academies',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Portfolio',
                'icon'        => 'fa-school',
                'sequence'    => 4010,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'type'        => 'art',
                'name'        => 'Art',
                'plural'      => 'Art',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Portfolio',
                'icon'        => 'fa-image',
                'sequence'    => 4020,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'type'        => 'certification',
                'name'        => 'Certification',
                'plural'      => 'Certifications',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Portfolio',
                'icon'        => 'fa-graduation-cap',
                'sequence'    => 4030,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'type'        => 'course',
                'name'        => 'Course',
                'plural'      => 'Courses',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Portfolio',
                'icon'        => 'fa-chalkboard',
                'sequence'    => 4040,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'type'        => 'link',
                'name'        => 'Link',
                'plural'      => 'Links',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Portfolio',
                'icon'        => 'fa-link',
                'sequence'    => 4050,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'type'        => 'music',
                'name'        => 'Music',
                'plural'      => 'Music',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Portfolio',
                'icon'        => 'fa-music',
                'sequence'    => 4060,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'type'        => 'project',
                'name'        => 'Project',
                'plural'      => 'Projects',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Portfolio',
                'icon'        => 'fa-wrench',
                'sequence'    => 4070,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'type'        => 'reading',
                'name'        => 'Reading',
                'plural'      => 'Readings',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Portfolio',
                'icon'        => 'fa-book',
                'sequence'    => 4080,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'type'        => 'recipe',
                'name'        => 'Recipe',
                'plural'      => 'Recipes',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Portfolio',
                'icon'        => 'fa-cutlery',
                'sequence'    => 4090,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'type'        => 'ingredient',
                'name'        => 'Ingredient',
                'plural'      => 'Ingredients',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Portfolio',
                'icon'        => 'fa-pizza-slice',
                'sequence'    => 4100,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
            [
                'database_id' => 4,
                'type'        => 'video',
                'name'        => 'Video',
                'plural'      => 'Videos',
                'front'       => 1,
                'user'        => 1,
                'admin'       => 1,
                'section'     => 'Portfolio',
                'icon'        => 'fa-video-camera',
                'sequence'    => 4110,
                'public'      => 1,
                'readonly'    => 0,
                'root'        => 1,
                'disabled'    => 0,
                'admin_id'    => 1,
            ],
        ];
        Resource::insert($data);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('resources');
    }
};
