<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::connection('dictionary_db')->create('frameworks', function (Blueprint $table) {
            $table->id();
            $table->string('full_name')->unique();
            $table->string('name', 100)->unique();
            $table->string('slug', 100)->unique();
            $table->string('abbreviation', 100)->nullable();
            $table->tinyInteger('open_source')->default(0);
            $table->tinyInteger('proprietary')->default(0);
            $table->string('owner', 100)->nullable();
            $table->string('website')->nullable();
            $table->string('wiki_page')->nullable();
            $table->text('description')->nullable();
        });

        $data = [
            [ 'id' => 1,   'name' => 'Angular',                  'full_name' => 'Angular',                  'slug' => 'angular',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://angular.dev/',                               'wiki_page' => 'https://en.wikipedia.org/wiki/Angular_(web_framework)' ],
            [ 'id' => 2,   'name' => 'ASP.NET',                  'full_name' => 'ASP.NET',                  'slug' => 'asp-net',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => 'Microsoft', 'website' => 'https://dotnet.microsoft.com/en-us/apps/aspnet',     'wiki_page' => 'https://en.wikipedia.org/wiki/ASP.NET' ],
            [ 'id' => 3,   'name' => 'AWS IAM',                  'full_name' => 'AWS Identity and Access Management', 'slug' => 'aws-iam', 'abbreviation' => 'AWS IAM', 'open_source' => 0, 'proprietary' => 0, 'owner' => 'Amazon',   'website' => 'https://aws.amazon.com/iam/',                        'wiki_page' => null ],
            [ 'id' => 4,   'name' => 'Backbone.js',              'full_name' => 'Backbone.js',              'slug' => 'backbone-js',       'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://backbonejs.org/',                            'wiki_page' => 'https://en.wikipedia.org/wiki/Backbone.js' ],
            [ 'id' => 5,   'name' => 'Bootstrap',                'full_name' => 'Bootstrap',                'slug' => 'bootstrap',         'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://getbootstrap.com/docs/5.0/getting-started/introduction/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)' ],
            [ 'id' => 6,   'name' => 'CakePHP',                  'full_name' => 'CakePHP',                  'slug' => 'cakephp',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://cakephp.org/',                               'wiki_page' => 'https://en.wikipedia.org/wiki/CakePHP' ],
            [ 'id' => 7,   'name' => 'CodeIgniter',              'full_name' => 'CodeIgniter',              'slug' => 'codeigniter',       'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://www.codeigniter.com/',                       'wiki_page' => 'https://en.wikipedia.org/wiki/CodeIgniter' ],
            [ 'id' => 8,   'name' => 'Cypress',                  'full_name' => 'Cypress',                  'slug' => 'cypress',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://www.cypress.io/',                            'wiki_page' => 'https://en.wikipedia.org/wiki/Cypress_(software)' ],
            [ 'id' => 9,   'name' => 'Django',                   'full_name' => 'Django',                   'slug' => 'django',            'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://www.djangoproject.com/',                     'wiki_page' => 'https://en.wikipedia.org/wiki/Django_(web_framework)' ],
            [ 'id' => 10,  'name' => 'Eclipse Jersey',           'full_name' => 'Eclipse Jersey',           'slug' => 'eclipse-jersey',    'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://eclipse-ee4j.github.io/jersey/',             'wiki_page' => 'https://en.wikipedia.org/wiki/Eclipse_Jersey' ],
            [ 'id' => 11,  'name' => 'Electron',                 'full_name' => 'Electron',                 'slug' => 'electron',          'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://www.electronjs.org/',                        'wiki_page' => 'https://en.wikipedia.org/wiki/Electron_(software_framework)' ],
            [ 'id' => 12,  'name' => 'Ember.js',                 'full_name' => 'Ember.js',                 'slug' => 'ember-js',          'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://emberjs.com/',                               'wiki_page' => 'https://en.wikipedia.org/wiki/Ember.js' ],
            [ 'id' => 13,  'name' => 'Express.js',               'full_name' => 'Express.js',               'slug' => 'express-js',        'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://expressjs.com/',                             'wiki_page' => 'https://en.wikipedia.org/wiki/Express.js' ],
            [ 'id' => 14,  'name' => 'FastAPI',                  'full_name' => 'FastAPI',                  'slug' => 'fastapi',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://fastapi.tiangolo.com/',                      'wiki_page' => 'https://en.wikipedia.org/wiki/FastAPI' ],
            [ 'id' => 15,  'name' => 'Flask',                    'full_name' => 'Flask',                    'slug' => 'flask',             'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://flask.palletsprojects.com/en/stable/',       'wiki_page' => 'https://en.wikipedia.org/wiki/Flask_(web_framework)' ],
            [ 'id' => 16,  'name' => 'Foundation',               'full_name' => 'Foundation',               'slug' => 'foundation',        'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://get.foundation/',                            'wiki_page' => 'https://en.wikipedia.org/wiki/Foundation_(framework)' ],
            [ 'id' => 17,  'name' => 'FuelPHP',                  'full_name' => 'FuelPHP',                  'slug' => 'fuelphp',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://fuelphp.com/',                               'wiki_page' => 'https://en.wikipedia.org/wiki/FuelPHP' ],
            [ 'id' => 18,  'name' => 'gRPC',                     'full_name' => 'gRPC',                     'slug' => 'grpc',              'abbreviation' => 'gRPC',   'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://grpc.io/',                                   'wiki_page' => 'https://en.wikipedia.org/wiki/GRPC' ],
            [ 'id' => 19,  'name' => 'Hibernate',                'full_name' => 'Hibernate',                'slug' => 'hibernate',         'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://hibernate.org/',                             'wiki_page' => 'https://en.wikipedia.org/wiki/Hibernate_(framework)' ],
            [ 'id' => 20,  'name' => 'InertiaJS',                'full_name' => 'InertiaJS',                'slug' => 'inertiajs',         'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://inertiajs.com/',                             'wiki_page' => null ],
            [ 'id' => 21,  'name' => 'Jest',                     'full_name' => 'Jest',                     'slug' => 'jest',              'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://jestjs.io/',                                 'wiki_page' => null ],
            [ 'id' => 22,  'name' => 'Jetpack',                  'full_name' => 'Jetpack Compose',          'slug' => 'jetpack',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://en.wikipedia.org/wiki/Jetpack_Compose',      'wiki_page' => 'https://developer.android.com/compose' ],
            [ 'id' => 23,  'name' => 'JUnit',                    'full_name' => 'JUnit',                    'slug' => 'junit',             'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://junit.org/',                                 'wiki_page' => 'https://en.wikipedia.org/wiki/Junit' ],
            [ 'id' => 24,  'name' => 'Jupyter',                  'full_name' => 'Jupyter',                  'slug' => 'jupyter',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://jupyter.org/',                               'wiki_page' => 'https://en.wikipedia.org/wiki/Project_Jupyter' ],
            [ 'id' => 25,  'name' => 'Laminas',                  'full_name' => 'Laminas',                  'slug' => 'laminas',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://getlaminas.org/',                            'wiki_page' => 'https://en.wikipedia.org/wiki/Laminas' ],
            [ 'id' => 26,  'name' => 'LangChain',                'full_name' => 'LangChain',                'slug' => 'langchain',         'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://www.langchain.com/langgraph',                'wiki_page' => null ],
            [ 'id' => 27,  'name' => 'LangGraph',                'full_name' => 'LangGraph',                'slug' => 'langgrah',          'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://laravel.com/',                               'wiki_page' => null ],
            [ 'id' => 28,  'name' => 'Laravel',                  'full_name' => 'Laravel',                  'slug' => 'laravel',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => null,                                                 'wiki_page' => 'https://en.wikipedia.org/wiki/Laravel' ],
            [ 'id' => 29,  'name' => 'Laravel Livewire',         'full_name' => 'Laravel Livewire',         'slug' => 'laravel-livewire',  'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://laravel-livewire.com/',                      'wiki_page' => null ],
            [ 'id' => 30,  'name' => 'Lightning Web Components', 'full_name' => 'Lightning Web Components', 'slug' => 'lwc',               'abbreviation' => 'LWC',    'open_source' => 0, 'proprietary' => 0, 'owner' => 'Salesforce','website' => 'https://developer.salesforce.com/developer-centers/lightning-web-components', 'wiki_page' => null ],
            [ 'id' => 31,  'name' => 'Materialize',              'full_name' => 'Materialize',              'slug' => 'materialize',       'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://materializecss.com/',                        'wiki_page' => null ],
            [ 'id' => 32,  'name' => 'Mocha',                    'full_name' => 'Mocha',                    'slug' => 'mocha',             'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://mochajs.org/',                               'wiki_page' => null ],
            [ 'id' => 33,  'name' => 'Mockito',                  'full_name' => 'Mockito',                  'slug' => 'mockito',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://site.mockito.org/',                          'wiki_page' => 'https://en.wikipedia.org/wiki/Mockito' ],
            [ 'id' => 34,  'name' => 'Mono',                     'full_name' => 'Mono',                     'slug' => 'mono',              'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://www.mono-project.com/',                      'wiki_page' => 'https://en.wikipedia.org/wiki/Mono_(software)' ],
            [ 'id' => 35,  'name' => 'NestJS',                   'full_name' => 'NestJS',                   'slug' => 'nestjs',            'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://nestjs.com/',                                'wiki_page' => 'https://en.wikipedia.org/wiki/NestJS' ],
            [ 'id' => 36,  'name' => 'Next.js',                  'full_name' => 'Next.js',                  'slug' => 'next-js',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => 'Vercel',    'website' => 'https://nextjs.org/',                                'wiki_page' => 'https://en.wikipedia.org/wiki/Next.js' ],
            [ 'id' => 37,  'name' => 'Nightwatch',               'full_name' => 'Nightwatch',               'slug' => 'nightwatch',        'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://nightwatchjs.org/',                          'wiki_page' => null ],
            [ 'id' => 38,  'name' => 'Phalcon',                  'full_name' => 'Phalcon',                  'slug' => 'phalcon',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://phalcon.io/en-us',                           'wiki_page' => 'https://en.wikipedia.org/wiki/Phalcon_(framework)' ],
            [ 'id' => 39,  'name' => 'Phoenix',                  'full_name' => 'Phoenix',                  'slug' => 'phoenix',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://www.phoenixframework.org/',                  'wiki_page' => 'https://en.wikipedia.org/wiki/Phoenix_(web_framework)' ],
            [ 'id' => 40,  'name' => 'PHPUnit',                  'full_name' => 'PHPUnit',                  'slug' => 'phpunit',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://phpunit.de/index.html',                      'wiki_page' => 'https://en.wikipedia.org/wiki/PHPUnit' ],
            [ 'id' => 41,  'name' => 'pytest',                   'full_name' => 'pytest',                   'slug' => 'pytest',            'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://docs.pytest.org/en/stable/',                 'wiki_page' => 'https://en.wikipedia.org/wiki/Pytest' ],
            [ 'id' => 42,  'name' => 'PyTorch',                  'full_name' => 'PyTorch',                  'slug' => 'pytorch',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://pytorch.org/',                               'wiki_page' => 'https://en.wikipedia.org/wiki/PyTorch' ],
            [ 'id' => 43,  'name' => 'React Native',             'full_name' => 'React Native',             'slug' => 'react-native',      'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://reactnative.dev/',                           'wiki_page' => 'https://en.wikipedia.org/wiki/React_Native' ],
            [ 'id' => 44,  'name' => 'Remix',                    'full_name' => 'Remix',                    'slug' => 'remix',             'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://remix.run/',                                 'wiki_page' => null ],
            [ 'id' => 45,  'name' => 'Slim',                     'full_name' => 'Slim',                     'slug' => 'slim',              'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://www.slimframework.com/',                     'wiki_page' => null ],
            [ 'id' => 46,  'name' => 'Spring Boot',              'full_name' => 'Spring Boot',              'slug' => 'spring-boot',       'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://spring.io/projects/spring-boot',             'wiki_page' => 'https://en.wikipedia.org/wiki/Spring_Boot' ],
            [ 'id' => 47,  'name' => 'Spring Framework',         'full_name' => 'Spring Framework',         'slug' => 'sprint-framework',  'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://spring.io/projects/spring-framework',        'wiki_page' => 'https://en.wikipedia.org/wiki/Spring_Framework' ],
            [ 'id' => 48,  'name' => 'Svelte',                   'full_name' => 'Svelte',                   'slug' => 'svelte',            'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://svelte.dev/',                                'wiki_page' => 'https://en.wikipedia.org/wiki/Svelte' ],
            [ 'id' => 49,  'name' => 'SwiftUI',                  'full_name' => 'SwiftUI',                  'slug' => 'swiftfui',          'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => 'Apple',     'website' => 'https://developer.apple.com/swiftui/',               'wiki_page' => 'https://en.wikipedia.org/wiki/SwiftUI' ],
            [ 'id' => 50,  'name' => 'Symfony',                  'full_name' => 'Symfony',                  'slug' => 'symfony',           'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://symfony.com/',                               'wiki_page' => 'https://en.wikipedia.org/wiki/Symfony' ],
            [ 'id' => 51,  'name' => 'Tailwind CSS',             'full_name' => 'Tailwind CSS',             'slug' => 'tailwind-css',      'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://tailwindcss.com/',                           'wiki_page' => 'https://en.wikipedia.org/wiki/Tailwind_CSS' ],
            [ 'id' => 52,  'name' => 'TestCafe',                 'full_name' => 'TestCafe',                 'slug' => 'testcafe',          'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://testcafe.io/',                               'wiki_page' => null ],
            [ 'id' => 53,  'name' => 'Vue.js',                   'full_name' => 'Vue.js',                   'slug' => 'vue-js',            'abbreviation' => 'Vue',    'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://vuejs.org/',                                 'wiki_page' => 'https://en.wikipedia.org/wiki/Vue.js' ],
            [ 'id' => 54,  'name' => 'Yii',                      'full_name' => 'Yii',                      'slug' => 'yii',               'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://www.yiiframework.com/',                      'wiki_page' => null ],
            [ 'id' => 55,  'name' => 'Bulma',                    'full_name' => 'Bulma',                    'slug' => 'bulma',             'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://bulma.io/',                                  'wiki_page' => null ],
            [ 'id' => 56,  'name' => 'Delta Lake',               'full_name' => 'Delta Lake',               'slug' => 'delta-lake',        'abbreviation' => null,     'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'website' => 'https://delta.io/',                                  'wiki_page' => null ],
            [ 'id' => 57,  'name' => 'AWS CDK',                  'full_name' => 'AWS Cloud Development Kit', 'slug' => 'aws-cloud-development-kit', 'abbreviation' => 'AWS CDK', 'open_source' => 0, 'proprietary' => 0, 'owner' => null, 'website' => 'https://aws.amazon.com/cdk/',                      'wiki_page' => 'https://en.wikipedia.org/wiki/AWS_Cloud_Development_Kit' ],
        ];
        \App\Models\Dictionary\Framework::insert($data);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::connection('dictionary_db')->dropIfExists('frameworks');
    }
};
