<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::connection('dictionary_db')->create('languages', function (Blueprint $table) {
            $table->id();
            $table->string('full_name')->unique();
            $table->string('name', 100)->unique();
            $table->string('slug', 100)->unique();
            $table->string('abbreviation', 20)->nullable();
            $table->tinyInteger('open_source')->default(0);
            $table->tinyInteger('proprietary')->default(0);
            $table->tinyInteger('compiled')->default(0);
            $table->string('owner', 100)->nullable();
            $table->string('wikipedia')->nullable();
            $table->string('link')->nullable();
            $table->string('link_name')->nullable();
            $table->text('description')->nullable();
            $table->string('image')->nullable();
            $table->string('thumbnail')->nullable();
            $table->integer('sequence')->default(0);
            $table->tinyInteger('public')->default(1);
            $table->integer('readonly')->default(0);
            $table->integer('root')->default(0);
            $table->tinyInteger('disabled')->default(0);
            $table->timestamps();
            $table->softDeletes();
        });

        $data = [
            [ 'id' => 1,  'full_name' => 'Active Server Pages',                           'name' => 'ASP',          'slug' => 'active-server-pages',      'abbreviation' => 'ASP',     'open_source' => 0, 'proprietary' => 1, 'compiled' => 1, 'owner' => 'Microsoft',  'link' => 'https://dotnet.microsoft.com/en-us/apps/aspnet',                                                                                     'wikipedia' => 'https://en.wikipedia.org/wiki/Active_Server_Pages'               ],
            [ 'id' => 2,  'full_name' => 'Apex',                                          'name' => 'Apex',         'slug' => 'apex',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 1, 'compiled' => 0, 'owner' => 'Salesforce', 'link' => 'https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_intro_what_is_apex.htm',                               'wikipedia' => 'https://en.wikipedia.org/wiki/Apex'                              ],
            [ 'id' => 3,  'full_name' => 'AppleScript',                                   'name' => 'AppleScript',  'slug' => 'applescript',              'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => 'Apple',      'link' => 'https://developer.apple.com/library/archive/documentation/AppleScript/Conceptual/AppleScriptLangGuide/introduction/ASLR_intro.html', 'wikipedia' => 'https://en.wikipedia.org/wiki/AppleScript'                       ],
            [ 'id' => 4,  'full_name' => 'AspectJ',                                       'name' => 'AspectJ',      'slug' => 'aspectj',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 1, 'owner' => null,         'link' => 'http://eclipse.dev/aspectj/',                                                                                                        'wikipedia' => 'https://en.wikipedia.org/wiki/AspectJ'                           ],
            [ 'id' => 5,  'full_name' => 'assembly language',                             'name' => 'assembly',     'slug' => 'assembly-language',        'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 1, 'owner' => null,         'link' => null,                                                                                                                                 'wikipedia' => 'https://en.wikipedia.org/wiki/Assembly_language'                 ],
            [ 'id' => 6,  'full_name' => 'C',                                             'name' => 'C',            'slug' => 'c',                        'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 1, 'owner' => null,         'link' => 'https://en.cppreference.com/w/c/language.html',                                                                                      'wikipedia' => 'https://en.wikipedia.org/wiki/C_(programming_language)'          ],
            [ 'id' => 7,  'full_name' => 'C++',                                           'name' => 'C++',          'slug' => 'c-plus-plus',              'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 1, 'owner' => null,         'link' => 'https://isocpp.org/',                                                                                                                'wikipedia' => 'https://en.wikipedia.org/wiki/C%2B%2B'                           ],
            [ 'id' => 8,  'full_name' => 'C#',                                            'name' => 'C#',           'slug' => 'c-sharp',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 1, 'owner' => null,         'link' => 'https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/',                                                                    'wikipedia' => 'https://en.wikipedia.org/wiki/C_Sharp_(programming_language)'    ],
            [ 'id' => 9,  'full_name' => 'Cascading Style Sheets',                        'name' => 'CSS',          'slug' => 'css',                      'abbreviation' => 'CSS',     'open_source' => 1, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://developer.mozilla.org/en-US/docs/Web/CSS',                                                                                   'wikipedia' => 'https://en.wikipedia.org/wiki/CSS'                               ],
            [ 'id' => 10, 'full_name' => 'COBOL',                                         'name' => 'COBOL',        'slug' => 'cobol',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 1, 'owner' => null,         'link' => 'https://www.ibm.com/think/topics/cobol',                                                                                             'wikipedia' => 'https://en.wikipedia.org/wiki/COBOL'                             ],
            [ 'id' => 11, 'full_name' => 'CoffeeScript',                                  'name' => 'CoffeeScript', 'slug' => 'coffeescript',             'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 1, 'owner' => null,         'link' => 'https://coffeescript.org/',                                                                                                          'wikipedia' => 'https://en.wikipedia.org/wiki/CoffeeScript'                      ],
            [ 'id' => 12, 'full_name' => 'ColdFusion',                                    'name' => 'ColdFusion',   'slug' => 'coldfusion',               'abbreviation' => 'CFML',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => 'Adobe',      'link' => 'https://www.adobe.com/products/coldfusion-family.html',                                                                              'wikipedia' => 'https://en.wikipedia.org/wiki/Adobe_ColdFusion'                  ],
            [ 'id' => 13, 'full_name' => 'Curl',                                          'name' => 'Curl',         'slug' => 'curl',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.curl.com/',                                                                                                              'wikipedia' => 'https://en.wikipedia.org/wiki/Curl_(programming_language)'       ],
            [ 'id' => 14, 'full_name' => 'D',                                             'name' => 'D',            'slug' => 'd',                        'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://dlang.org/',                                                                                                                 'wikipedia' => 'https://simple.wikipedia.org/wiki/D_(programming_language)'      ],
            [ 'id' => 15, 'full_name' => 'Dart',                                          'name' => 'Dart',         'slug' => 'dart',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://dart.dev/',                                                                                                                  'wikipedia' => 'https://en.wikipedia.org/wiki/Dart_(programming_language)'       ],
            [ 'id' => 16, 'full_name' => 'DIGITAL Command Language',                      'name' => 'DCL',          'slug' => 'digital-command-language', 'abbreviation' => 'DCL',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => null,                                                                                                                                 'wikipedia' => 'https://en.wikipedia.org/wiki/DIGITAL_Command_Language'          ],
            [ 'id' => 17, 'full_name' => 'ECMAScript',                                    'name' => 'ECMAScript',   'slug' => 'ecmascript',               'abbreviation' => null,      'open_source' => 1, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://developer.mozilla.org/en-US/docs/Glossary/ECMAScript',                                                                       'wikipedia' => 'https://en.wikipedia.org/wiki/ECMAScript'                        ],
            [ 'id' => 18, 'full_name' => 'Embeddable Common Lisp',                        'name' => 'ECL',          'slug' => 'embeddable-common-lisp',   'abbreviation' => 'ECL',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://ecl.common-lisp.dev/',                                                                                                       'wikipedia' => 'https://en.wikipedia.org/wiki/Embeddable_Common_Lisp'            ],
            [ 'id' => 19, 'full_name' => 'Elixir',                                        'name' => 'Elixir',       'slug' => 'elixir',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://elixir-lang.org/',                                                                                                           'wikipedia' => 'https://en.wikipedia.org/wiki/Elixir_(programming_language)'     ],
            [ 'id' => 20, 'full_name' => 'Erlang',                                        'name' => 'Erlang',       'slug' => 'erlang',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.erlang.org/',                                                                                                            'wikipedia' => 'https://en.wikipedia.org/wiki/Erlang_(programming_language)'     ],
            [ 'id' => 21, 'full_name' => 'Extensible HyperText Markup Language',          'name' => 'XHTML',        'slug' => 'xhtml',                    'abbreviation' => 'XHTML',   'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://developer.mozilla.org/en-US/docs/Glossary/XHTML',                                                                            'wikipedia' => 'https://en.wikipedia.org/wiki/XHTML#:~:text=Extensible%20HyperText%20Markup%20Language%20(XHTML,Filename%20extension' ],
            [ 'id' => 22, 'full_name' => 'Extensible Markup Language',                    'name' => 'XML',          'slug' => 'xml',                      'abbreviation' => 'XML',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.w3.org/TR/xml/',                                                                                                         'wikipedia' => 'https://en.wikipedia.org/wiki/XML'                               ],
            [ 'id' => 23, 'full_name' => 'Extensible Stylesheet Language Transformation', 'name' => 'XSLT',         'slug' => 'xslt',                     'abbreviation' => 'XSLT',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.w3.org/TR/xslt-30/',                                                                                                     'wikipedia' => 'https://en.wikipedia.org/wiki/XSLT'                              ],
            [ 'id' => 24, 'full_name' => 'Fortran',                                       'name' => 'Fortran',      'slug' => 'fortran',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://fortran-lang.org/',                                                                                                          'wikipedia' => 'https://en.wikipedia.org/wiki/Fortran'                           ],
            [ 'id' => 25, 'full_name' => 'Go',                                            'name' => 'Go',           'slug' => 'go',                       'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://go.dev/',                                                                                                                    'wikipedia' => 'https://en.wikipedia.org/wiki/Go_(programming_language)'         ],
            [ 'id' => 26, 'full_name' => 'Graphic Query Language',                        'name' => 'GQL',          'slug' => 'gql',                      'abbreviation' => 'GQL',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://graphql.org/',                                                                                                               'wikipedia' => 'https://en.wikipedia.org/wiki/Graph_Query_Language'              ],
            [ 'id' => 27, 'full_name' => 'Groovy',                                        'name' => 'Groovy',       'slug' => 'groovy',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://groovy-lang.org/',                                                                                                           'wikipedia' => 'https://en.wikipedia.org/wiki/Apache_Groovy'                     ],
            [ 'id' => 28, 'full_name' => 'Hack',                                          'name' => 'Hack',         'slug' => 'hack',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://hacklang.org/',                                                                                                              'wikipedia' => 'https://en.wikipedia.org/wiki/Hack_(programming_language)'       ],
            [ 'id' => 29, 'full_name' => 'Haskell',                                       'name' => 'Haskell',      'slug' => 'haskell',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.haskell.org/',                                                                                                           'wikipedia' => 'https://en.wikipedia.org/wiki/Haskell'                           ],
            [ 'id' => 30, 'full_name' => 'HyperText Markup Language',                     'name' => 'HTML',         'slug' => 'html',                     'abbreviation' => 'HTML',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://developer.mozilla.org/en-US/docs/Web/HTML',                                                                                  'wikipedia' => 'https://en.wikipedia.org/wiki/HTML'                              ],
            [ 'id' => 31, 'full_name' => 'HyperText Markup Language 5',                   'name' => 'HTML5',        'slug' => 'html5',                    'abbreviation' => 'HTML5',   'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://developer.mozilla.org/en-US/docs/Glossary/HTML5',                                                                            'wikipedia' => 'https://en.wikipedia.org/wiki/HTML5'                             ],
            [ 'id' => 32, 'full_name' => 'Java',                                          'name' => 'Java',         'slug' => 'java',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 1, 'owner' => 'Oracle',     'link' => 'https://www.java.com/en/',                                                                                                           'wikipedia' => 'https://en.wikipedia.org/wiki/Java_(programming_language)'       ],
            [ 'id' => 33, 'full_name' => 'JavaScript',                                    'name' => 'JavaScript',   'slug' => 'javascript',               'abbreviation' => 'JS',      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',                                                                            'wikipedia' => 'https://en.wikipedia.org/wiki/JavaScript'                        ],
            [ 'id' => 34, 'full_name' => 'Job Control Language',                          'name' => 'JCL',          'slug' => 'job-control-language',     'abbreviation' => 'JCL',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => null,                                                                                                                                 'wikipedia' => 'https://en.wikipedia.org/wiki/Job_Control_Language'              ],
            [ 'id' => 35, 'full_name' => 'Julia',                                         'name' => 'Julia',        'slug' => 'julia',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://julialang.org/',                                                                                                             'wikipedia' => 'https://en.wikipedia.org/wiki/Julia_(programming_language)'      ],
            [ 'id' => 36, 'full_name' => 'Kotlin',                                        'name' => 'Kotlin',       'slug' => 'kotlin',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://kotlinlang.org/',                                                                                                            'wikipedia' => 'https://en.wikipedia.org/wiki/Kotlin_(programming_language)'     ],
            [ 'id' => 37, 'full_name' => 'LESS',                                          'name' => 'LESS',         'slug' => 'less',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://lesscss.org/',                                                                                                               'wikipedia' => 'https://en.wikipedia.org/wiki/Less_(style_sheet_language)'       ],
            [ 'id' => 38, 'full_name' => 'Lisp',                                          'name' => 'Lisp',         'slug' => 'lisp',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://lisp-lang.org/',                                                                                                             'wikipedia' => 'https://en.wikipedia.org/wiki/Lisp_(programming_language'        ],
            [ 'id' => 39, 'full_name' => 'Lua',                                           'name' => 'Lua',          'slug' => 'lua',                      'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.lua.org/',                                                                                                               'wikipedia' => 'https://en.wikipedia.org/wiki/Lua'                               ],
            [ 'id' => 40, 'full_name' => 'm4',                                            'name' => 'm4',           'slug' => 'm4',                       'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => null,                                                                                                                                 'wikipedia' => 'https://en.wikipedia.org/wiki/M4_(computer_language)'            ],
            [ 'id' => 41, 'full_name' => 'Markdown',                                      'name' => 'Markdown',     'slug' => 'markdown',                 'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.markdownguide.org/',                                                                                                     'wikipedia' => 'https://en.wikipedia.org/wiki/Markdown'                          ],
            [ 'id' => 42, 'full_name' => 'NetRexx',                                       'name' => 'NetRexx',      'slug' => 'netrexx',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.netrexx.org/',                                                                                                           'wikipedia' => 'https://en.wikipedia.org/wiki/NetRexx'                           ],
            [ 'id' => 43, 'full_name' => 'NoSQL',                                         'name' => 'NoSQL',        'slug' => 'nosql',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => null,                                                                                                                                 'wikipedia' => 'https://en.wikipedia.org/wiki/NoSQL'                             ],
            [ 'id' => 44, 'full_name' => 'OpenGL Shading Language',                       'name' => 'GLSL',         'slug' => 'glsl',                     'abbreviation' => 'GLSL',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://learnopengl.com/Getting-started/Shaders',                                                                                    'wikipedia' => 'https://en.wikipedia.org/wiki/OpenGL_Shading_Language'           ],
            [ 'id' => 45, 'full_name' => 'Pascal',                                        'name' => 'Pascal',       'slug' => 'pascal',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => null,                                                                                                                                 'wikipedia' => 'https://en.wikipedia.org/wiki/Pascal_(programming_language)'     ],
            [ 'id' => 46, 'full_name' => 'Personal Home Page',                            'name' => 'PHP',          'slug' => 'php',                      'abbreviation' => 'PHP',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.php.net/',                                                                                                               'wikipedia' => 'https://en.wikipedia.org/wiki/PHP'                               ],
            [ 'id' => 47, 'full_name' => 'PowerShell',                                    'name' => 'PowerShell',   'slug' => 'powershell',               'abbreviation' => null,      'open_source' => 1, 'proprietary' => 0, 'compiled' => 0, 'owner' => 'Microsoft',  'link' => 'https://learn.microsoft.com/en-us/powershell/',                                                                                      'wikipedia' => 'https://en.wikipedia.org/wiki/PowerShell'                        ],
            [ 'id' => 48, 'full_name' => 'Preact',                                        'name' => 'Preact',       'slug' => 'preact',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://preactjs.com/',                                                                                                              'wikipedia' => null                                                              ],
            [ 'id' => 49, 'full_name' => 'Pure',                                          'name' => 'Pure',         'slug' => 'pure',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://agraef.github.io/pure-lang/',                                                                                                'wikipedia' => 'https://en.wikipedia.org/wiki/Pure_(programming_language)'       ],
            [ 'id' => 50, 'full_name' => 'Python',                                        'name' => 'Python',       'slug' => 'python',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.python.org/',                                                                                                            'wikipedia' => 'https://en.wikipedia.org/wiki/Python'                            ],
            [ 'id' => 51, 'full_name' => 'R',                                             'name' => 'R',            'slug' => 'r',                        'abbreviation' => 'R',       'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.r-project.org/',                                                                                                         'wikipedia' => 'https://en.wikipedia.org/wiki/R_(programming_language)'          ],
            [ 'id' => 52, 'full_name' => 'Raku',                                          'name' => 'Raku',         'slug' => 'raku',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://raku.org/',                                                                                                                  'wikipedia' => 'https://en.wikipedia.org/wiki/Raku_(programming_language)'       ],
            [ 'id' => 53, 'full_name' => 'Rebol',                                         'name' => 'Rebol',        'slug' => 'rebol',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.rebol.com/',                                                                                                             'wikipedia' => 'https://en.wikipedia.org/wiki/Rebol'                             ],
            [ 'id' => 54, 'full_name' => 'Red',                                           'name' => 'Red',          'slug' => 'red',                      'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.red-lang.org/',                                                                                                          'wikipedia' => 'https://en.wikipedia.org/wiki/Red_(programming_language)'        ],
            [ 'id' => 55, 'full_name' => 'RESTful API Modeling Language',                 'name' => 'RAML',         'slug' => 'raml',                     'abbreviation' => 'RAML',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://raml.org/',                                                                                                                  'wikipedia' => 'https://en.wikipedia.org/wiki/RAML_(software)'                   ],
            [ 'id' => 56, 'full_name' => 'Rexx',                                          'name' => 'Rexx',         'slug' => 'rexx',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://en.wikibooks.org/wiki/Rexx_Programming',                                                                                     'wikipedia' => 'https://en.wikipedia.org/wiki/Rexx'                              ],
            [ 'id' => 57, 'full_name' => 'Rspec',                                         'name' => 'Rspec',        'slug' => 'rpsec',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://rspec.info/',                                                                                                                'wikipedia' => 'https://en.wikipedia.org/wiki/Rspec'                             ],
            [ 'id' => 58, 'full_name' => 'Ruby',                                          'name' => 'Ruby',         'slug' => 'ruby',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.ruby-lang.org/en/',                                                                                                      'wikipedia' => 'https://en.wikipedia.org/wiki/Ruby'                              ],
            [ 'id' => 59, 'full_name' => 'Rust',                                          'name' => 'Rust',         'slug' => 'rust',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.rust-lang.org/',                                                                                                         'wikipedia' => 'https://en.wikipedia.org/wiki/Rust_(programming_language)'       ],
            [ 'id' => 60, 'full_name' => 'Statistical Analysis System',                   'name' => 'SAS',          'slug' => 'sas',                      'abbreviation' => 'SAS',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.sas.com/en_us/software/base-sas.html',                                                                                   'wikipedia' => 'https://en.wikipedia.org/wiki/SAS_language'                      ],
            [ 'id' => 61, 'full_name' => 'Sassy CSS',                                     'name' => 'Sassy CSS',    'slug' => 'sassy-css',                'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://medium.com/@jgoz/sassy-css-scss-quick-guide-b38f51c6868a',                                                                   'wikipedia' => null                                                              ],
            [ 'id' => 62, 'full_name' => 'Scala',                                         'name' => 'Scala',        'slug' => 'scala',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.scala-lang.org/',                                                                                                        'wikipedia' => 'https://en.wikipedia.org/wiki/Scala_(programming_language)'      ],
            [ 'id' => 63, 'full_name' => 'Scheme',                                        'name' => 'Scheme',       'slug' => 'scheme',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.scheme.org/',                                                                                                            'wikipedia' => 'https://en.wikipedia.org/wiki/Scheme_(programming_language)'     ],
            [ 'id' => 64, 'full_name' => 'Scribe',                                        'name' => 'Scribe',       'slug' => 'scribe',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => null,                                                                                                                                 'wikipedia' => 'https://en.wikipedia.org/wiki/Scribe_(markup_language)'          ],
            [ 'id' => 65, 'full_name' => 'Standard Generalized Markup Language',          'name' => 'SGML',         'slug' => 'sgml',                     'abbreviation' => 'SGML',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => null,                                                                                                                                 'wikipedia' => 'https://developer.mozilla.org/en-US/docs/Glossary/SGML'          ],
            [ 'id' => 66, 'full_name' => 'Structured Query Language',                     'name' => 'SQL',          'slug' => 'sql',                      'abbreviation' => 'SQL',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => null,                                                                                                                                 'wikipedia' => 'https://en.wikipedia.org/wiki/SQL'                               ],
            [ 'id' => 67, 'full_name' => 'Swift',                                         'name' => 'Swift',        'slug' => 'swift',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.swift.org/',                                                                                                             'wikipedia' => 'https://en.wikipedia.org/wiki/Swift_(programming_language)'      ],
            [ 'id' => 68, 'full_name' => 'Syntactically Awesome Style Sheets',            'name' => 'SASS',         'slug' => 'sass',                     'abbreviation' => 'SASS',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://sass-lang.com/',                                                                                                             'wikipedia' => 'https://en.wikipedia.org/wiki/Sass_(style_sheet_language)'       ],
            [ 'id' => 69, 'full_name' => 'Tool Command Language',                         'name' => 'TCL',          'slug' => 'tool-command-language',    'abbreviation' => 'TCL',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.tcl-lang.org/',                                                                                                          'wikipedia' => 'https://en.wikipedia.org/wiki/Tcl'                               ],
            [ 'id' => 70, 'full_name' => 'TypeScript',                                    'name' => 'TypeScript',   'slug' => 'typescript',               'abbreviation' => 'TS',      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.typescriptlang.org/',                                                                                                    'wikipedia' => 'https://en.wikipedia.org/wiki/TypeScript'                        ],
            [ 'id' => 71, 'full_name' => 'VBScript',                                      'name' => 'VBScript',     'slug' => 'VBScript',                 'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => 'Microsoft',  'link' => null,                                                                                                                                 'wikipedia' => 'https://en.wikipedia.org/wiki/VBScript'                          ],
            [ 'id' => 72, 'full_name' => 'Visual Basic',                                  'name' => 'Visual Basic', 'slug' => 'visual-basic',             'abbreviation' => 'VB',      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://learn.microsoft.com/en-us/dotnet/visual-basic/',                                                                             'wikipedia' => 'https://en.wikipedia.org/wiki/Visual_Basic_(.NET)'               ],
            [ 'id' => 73, 'full_name' => 'Web Services Description Language',             'name' => 'WSDL',         'slug' => 'wsdl',                     'abbreviation' => 'WSDL',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.w3.org/TR/2007/REC-wsdl20-20070626/',                                                                                    'wikipedia' => 'https://en.wikipedia.org/wiki/Web_Services_Description_Language' ],
            [ 'id' => 74, 'full_name' => 'Wolfram Mathematica',                           'name' => 'Wolfram',      'slug' => 'wolfram-mathematica',      'abbreviation' => 'Wolfram', 'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.wolfram.com/language/',                                                                                                  'wikipedia' => 'https://en.wikipedia.org/wiki/Wolfram_Mathematica'               ],
            [ 'id' => 75, 'full_name' => 'Work Flow Language',                            'name' => 'WFL',          'slug' => 'work-flow-language',       'abbreviation' => 'WFL',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => null,                                                                                                                                 'wikipedia' => 'https://en.wikipedia.org/wiki/Work_Flow_Language'                ],
            [ 'id' => 76, 'full_name' => 'YAML',                                          'name' => 'YAML',         'slug' => 'yaml',                     'abbreviation' => 'YAML',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://yaml.org/',                                                                                                                  'wikipedia' => 'https://en.wikipedia.org/wiki/YAML'                              ],
            [ 'id' => 77, 'full_name' => 'PL/SQL',                                        'name' => 'PL/SQL',       'slug' => 'pl-sql',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.oracle.com/database/technologies/appdev/plsql.html',                                                                     'wikipedia' => 'https://en.wikipedia.org/wiki/PL/SQL'                            ],
            [ 'id' => 78, 'full_name' => 'Perl',                                          'name' => 'Perl',         'slug' => 'perl',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => 'https://www.perl.org/',                                                                                                              'wikipedia' => 'https://en.wikipedia.org/wiki/Perl'                              ],
            [ 'id' => 79, 'full_name' => 'other',                                         'name' => 'other',        'slug' => 'other',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,         'link' => null,                                                                                                                                 'wikipedia' => null                                                              ],
        ];
        \App\Models\Dictionary\Language::insert($data);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::connection('dictionary_db')->dropIfExists('languages');
    }
};
