<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::connection('dictionary_db')->create('frameworks', function (Blueprint $table) {
            $table->id();
            $table->string('full_name')->unique();
            $table->string('name', 100)->unique();
            $table->string('slug', 100)->unique();
            $table->string('abbreviation', 100)->nullable();
            $table->tinyInteger('open_source')->default(0);
            $table->tinyInteger('proprietary')->default(0);
            $table->string('owner', 100)->nullable();
            $table->string('wiki_page')->nullable();
            $table->string('link')->nullable();
            $table->string('link_name')->nullable();
            $table->text('description')->nullable();
            $table->string('image')->nullable();
            $table->string('thumbnail')->nullable();
            $table->integer('sequence')->default(0);
            $table->tinyInteger('public')->default(1);
            $table->integer('readonly')->default(0);
            $table->integer('root')->default(0);
            $table->tinyInteger('disabled')->default(0);
            $table->timestamps();
            $table->softDeletes();
        });

        $data = [
            [ 'id' => 1,   'full_name' => 'Angular',                            'name' => 'Angular',                  'slug' => 'angular',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://angular.dev/',                                                        'wiki_page' => 'https://en.wikipedia.org/wiki/Angular_(web_framework)'         ],
            [ 'id' => 2,   'full_name' => 'ASP.NET',                            'name' => 'ASP.NET',                  'slug' => 'asp-net',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => 'Microsoft',  'link' => 'https://dotnet.microsoft.com/en-us/apps/aspnet',                              'wiki_page' => 'https://en.wikipedia.org/wiki/ASP.NET'                         ],
            [ 'id' => 3,   'full_name' => 'AWS Identity and Access Management', 'name' => 'AWS IAM',                  'slug' => 'aws-iam',                   'abbreviation' => 'AWS IAM', 'open_source' => 0, 'proprietary' => 0, 'owner' => 'Amazon',     'link' => 'https://aws.amazon.com/iam/',                                                 'wiki_page' =>  null                                                           ],
            [ 'id' => 4,   'full_name' => 'Backbone.js',                        'name' => 'Backbone.js',              'slug' => 'backbone-js',               'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://backbonejs.org/',                                                     'wiki_page' => 'https://en.wikipedia.org/wiki/Backbone.js'                     ],
            [ 'id' => 5,   'full_name' => 'Bootstrap',                          'name' => 'Bootstrap',                'slug' => 'bootstrap',                 'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://getbootstrap.com/docs/5.0/getting-started/introduction/',             'wiki_page' => 'https://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)' ],
            [ 'id' => 6,   'full_name' => 'CakePHP',                            'name' => 'CakePHP',                  'slug' => 'cakephp',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://cakephp.org/',                                                        'wiki_page' => 'https://en.wikipedia.org/wiki/CakePHP'                         ],
            [ 'id' => 7,   'full_name' => 'CodeIgniter',                        'name' => 'CodeIgniter',              'slug' => 'codeigniter',               'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.codeigniter.com/',                                                'wiki_page' => 'https://en.wikipedia.org/wiki/CodeIgniter'                     ],
            [ 'id' => 8,   'full_name' => 'Cypress',                            'name' => 'Cypress',                  'slug' => 'cypress',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.cypress.io/',                                                     'wiki_page' => 'https://en.wikipedia.org/wiki/Cypress_(software)'              ],
            [ 'id' => 9,   'full_name' => 'Django',                             'name' => 'Django',                   'slug' => 'django',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.djangoproject.com/',                                              'wiki_page' => 'https://en.wikipedia.org/wiki/Django_(web_framework)'          ],
            [ 'id' => 10,  'full_name' => 'Eclipse Jersey',                     'name' => 'Eclipse Jersey',           'slug' => 'eclipse-jersey',            'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://eclipse-ee4j.github.io/jersey/',                                      'wiki_page' => 'https://en.wikipedia.org/wiki/Eclipse_Jersey'                  ],
            [ 'id' => 11,  'full_name' => 'Electron',                           'name' => 'Electron',                 'slug' => 'electron',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.electronjs.org/',                                                 'wiki_page' => 'https://en.wikipedia.org/wiki/Electron_(software_framework)'   ],
            [ 'id' => 12,  'full_name' => 'Ember.js',                           'name' => 'Ember.js',                 'slug' => 'ember-js',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://emberjs.com/',                                                        'wiki_page' => 'https://en.wikipedia.org/wiki/Ember.js'                        ],
            [ 'id' => 13,  'full_name' => 'Express.js',                         'name' => 'Express.js',               'slug' => 'express-js',                'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://expressjs.com/',                                                      'wiki_page' => 'https://en.wikipedia.org/wiki/Express.js'                      ],
            [ 'id' => 14,  'full_name' => 'FastAPI',                            'name' => 'FastAPI',                  'slug' => 'fastapi',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://fastapi.tiangolo.com/',                                               'wiki_page' => 'https://en.wikipedia.org/wiki/FastAPI'                         ],
            [ 'id' => 15,  'full_name' => 'Flask',                              'name' => 'Flask',                    'slug' => 'flask',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://flask.palletsprojects.com/en/stable/',                                'wiki_page' => 'https://en.wikipedia.org/wiki/Flask_(web_framework)'           ],
            [ 'id' => 16,  'full_name' => 'Foundation',                         'name' => 'Foundation',               'slug' => 'foundation',                'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://get.foundation/',                                                     'wiki_page' => 'https://en.wikipedia.org/wiki/Foundation_(framework)'          ],
            [ 'id' => 17,  'full_name' => 'FuelPHP',                            'name' => 'FuelPHP',                  'slug' => 'fuelphp',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://fuelphp.com/',                                                        'wiki_page' => 'https://en.wikipedia.org/wiki/FuelPHP'                         ],
            [ 'id' => 18,  'full_name' => 'gRPC',                               'name' => 'gRPC',                     'slug' => 'grpc',                      'abbreviation' => 'gRPC',    'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://grpc.io/',                                                            'wiki_page' => 'https://en.wikipedia.org/wiki/GRPC'                            ],
            [ 'id' => 19,  'full_name' => 'Hibernate',                          'name' => 'Hibernate',                'slug' => 'hibernate',                 'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://hibernate.org/',                                                      'wiki_page' => 'https://en.wikipedia.org/wiki/Hibernate_(framework)'           ],
            [ 'id' => 20,  'full_name' => 'InertiaJS',                          'name' => 'InertiaJS',                'slug' => 'inertiajs',                 'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://inertiajs.com/',                                                      'wiki_page' => null                                                            ],
            [ 'id' => 21,  'full_name' => 'Jest',                               'name' => 'Jest',                     'slug' => 'jest',                      'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://jestjs.io/',                                                          'wiki_page' => null                                                            ],
            [ 'id' => 22,  'full_name' => 'Jetpack Compose',                    'name' => 'Jetpack',                  'slug' => 'jetpack',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://en.wikipedia.org/wiki/Jetpack_Compose',                               'wiki_page' => 'https://developer.android.com/compose'                         ],
            [ 'id' => 23,  'full_name' => 'JUnit',                              'name' => 'JUnit',                    'slug' => 'junit',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://junit.org/',                                                          'wiki_page' => 'https://en.wikipedia.org/wiki/Junit'                           ],
            [ 'id' => 24,  'full_name' => 'Jupyter',                            'name' => 'Jupyter',                  'slug' => 'jupyter',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://jupyter.org/',                                                        'wiki_page' => 'https://en.wikipedia.org/wiki/Project_Jupyter'                 ],
            [ 'id' => 25,  'full_name' => 'Laminas',                            'name' => 'Laminas',                  'slug' => 'laminas',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://getlaminas.org/',                                                     'wiki_page' => 'https://en.wikipedia.org/wiki/Laminas'                         ],
            [ 'id' => 26,  'full_name' => 'LangChain',                          'name' => 'LangChain',                'slug' => 'langchain',                 'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.langchain.com/langgraph',                                         'wiki_page' => null                                                            ],
            [ 'id' => 27,  'full_name' => 'LangGraph',                          'name' => 'LangGraph',                'slug' => 'langgrah',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://laravel.com/',                                                        'wiki_page' => null                                                            ],
            [ 'id' => 28,  'full_name' => 'Laravel',                            'name' => 'Laravel',                  'slug' => 'laravel',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => null,                                                                          'wiki_page' => 'https://en.wikipedia.org/wiki/Laravel'                         ],
            [ 'id' => 29,  'full_name' => 'Laravel Livewire',                   'name' => 'Laravel Livewire',         'slug' => 'laravel-livewire',          'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://laravel-livewire.com/',                                               'wiki_page' => null                                                            ],
            [ 'id' => 30,  'full_name' => 'Lightning Web Components',           'name' => 'Lightning Web Components', 'slug' => 'lwc',                       'abbreviation' => 'LWC',     'open_source' => 0, 'proprietary' => 0, 'owner' => 'Salesforce', 'link' => 'https://developer.salesforce.com/developer-centers/lightning-web-components', 'wiki_page' => null                                                            ],
            [ 'id' => 31,  'full_name' => 'Materialize',                        'name' => 'Materialize',              'slug' => 'materialize',               'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://materializecss.com/',                                                 'wiki_page' => null                                                            ],
            [ 'id' => 32,  'full_name' => 'Mocha',                              'name' => 'Mocha',                    'slug' => 'mocha',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://mochajs.org/',                                                        'wiki_page' => null                                                            ],
            [ 'id' => 33,  'full_name' => 'Mockito',                            'name' => 'Mockito',                  'slug' => 'mockito',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://site.mockito.org/',                                                   'wiki_page' => 'https://en.wikipedia.org/wiki/Mockito'                         ],
            [ 'id' => 34,  'full_name' => 'Mono',                               'name' => 'Mono',                     'slug' => 'mono',                      'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.mono-project.com/',                                               'wiki_page' => 'https://en.wikipedia.org/wiki/Mono_(software)'                 ],
            [ 'id' => 35,  'full_name' => 'NestJS',                             'name' => 'NestJS',                   'slug' => 'nestjs',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://nestjs.com/',                                                         'wiki_page' => 'https://en.wikipedia.org/wiki/NestJS'                          ],
            [ 'id' => 36,  'full_name' => 'Next.js',                            'name' => 'Next.js',                  'slug' => 'next-js',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => 'Vercel',     'link' => 'https://nextjs.org/',                                                         'wiki_page' => 'https://en.wikipedia.org/wiki/Next.js'                         ],
            [ 'id' => 37,  'full_name' => 'Nightwatch',                         'name' => 'Nightwatch',               'slug' => 'nightwatch',                'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://nightwatchjs.org/',                                                   'wiki_page' =>  null                                                           ],
            [ 'id' => 38,  'full_name' => 'Phalcon',                            'name' => 'Phalcon',                  'slug' => 'phalcon',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://phalcon.io/en-us',                                                    'wiki_page' => 'https://en.wikipedia.org/wiki/Phalcon_(framework)'             ],
            [ 'id' => 39,  'full_name' => 'Phoenix',                            'name' => 'Phoenix',                  'slug' => 'phoenix',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.phoenixframework.org/',                                           'wiki_page' => 'https://en.wikipedia.org/wiki/Phoenix_(web_framework)'         ],
            [ 'id' => 40,  'full_name' => 'PHPUnit',                            'name' => 'PHPUnit',                  'slug' => 'phpunit',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://phpunit.de/index.html',                                               'wiki_page' => 'https://en.wikipedia.org/wiki/PHPUnit'                         ],
            [ 'id' => 41,  'full_name' => 'pytest',                             'name' => 'pytest',                   'slug' => 'pytest',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://docs.pytest.org/en/stable/',                                          'wiki_page' => 'https://en.wikipedia.org/wiki/Pytest'                          ],
            [ 'id' => 42,  'full_name' => 'PyTorch',                            'name' => 'PyTorch',                  'slug' => 'pytorch',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://pytorch.org/',                                                        'wiki_page' => 'https://en.wikipedia.org/wiki/PyTorch'                         ],
            [ 'id' => 43,  'full_name' => 'React Native',                       'name' => 'React Native',             'slug' => 'react-native',              'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://reactnative.dev/',                                                    'wiki_page' => 'https://en.wikipedia.org/wiki/React_Native'                    ],
            [ 'id' => 44,  'full_name' => 'Remix',                              'name' => 'Remix',                    'slug' => 'remix',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://remix.run/',                                                          'wiki_page' => null                                                            ],
            [ 'id' => 45,  'full_name' => 'Slim',                               'name' => 'Slim',                     'slug' => 'slim',                      'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.slimframework.com/',                                              'wiki_page' => null                                                            ],
            [ 'id' => 46,  'full_name' => 'Spring Boot',                        'name' => 'Spring Boot',              'slug' => 'spring-boot',               'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://spring.io/projects/spring-boot',                                      'wiki_page' => 'https://en.wikipedia.org/wiki/Spring_Boot'                     ],
            [ 'id' => 47,  'full_name' => 'Spring Framework',                   'name' => 'Spring Framework',         'slug' => 'sprint-framework',          'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://spring.io/projects/spring-framework',                                 'wiki_page' => 'https://en.wikipedia.org/wiki/Spring_Framework'                ],
            [ 'id' => 48,  'full_name' => 'Svelte',                             'name' => 'Svelte',                   'slug' => 'svelte',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://svelte.dev/',                                                         'wiki_page' => 'https://en.wikipedia.org/wiki/Svelte'                          ],
            [ 'id' => 49,  'full_name' => 'SwiftUI',                            'name' => 'SwiftUI',                  'slug' => 'swiftfui',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => 'Apple',      'link' => 'https://developer.apple.com/swiftui/',                                        'wiki_page' => 'https://en.wikipedia.org/wiki/SwiftUI'                         ],
            [ 'id' => 50,  'full_name' => 'Symfony',                            'name' => 'Symfony',                  'slug' => 'symfony',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://symfony.com/',                                                        'wiki_page' => 'https://en.wikipedia.org/wiki/Symfony'                         ],
            [ 'id' => 51,  'full_name' => 'Tailwind CSS',                       'name' => 'Tailwind CSS',             'slug' => 'tailwind-css',              'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://tailwindcss.com/',                                                    'wiki_page' => 'https://en.wikipedia.org/wiki/Tailwind_CSS'                    ],
            [ 'id' => 52,  'full_name' => 'TestCafe',                           'name' => 'TestCafe',                 'slug' => 'testcafe',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://testcafe.io/',                                                        'wiki_page' => null                                                            ],
            [ 'id' => 53,  'full_name' => 'Vue.js',                             'name' => 'Vue.js',                   'slug' => 'vue-js',                    'abbreviation' => 'Vue',     'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://vuejs.org/',                                                          'wiki_page' => 'https://en.wikipedia.org/wiki/Vue.js'                          ],
            [ 'id' => 54,  'full_name' => 'Yii',                                'name' => 'Yii',                      'slug' => 'yii',                       'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.yiiframework.com/',                                               'wiki_page' => null                                                            ],
            [ 'id' => 55,  'full_name' => 'Bulma',                              'name' => 'Bulma',                    'slug' => 'bulma',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://bulma.io/',                                                           'wiki_page' => null                                                            ],
            [ 'id' => 56,  'full_name' => 'Delta Lake',                         'name' => 'Delta Lake',               'slug' => 'delta-lake',                'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://delta.io/',                                                           'wiki_page' => null                                                            ],
            [ 'id' => 57,  'full_name' => 'AWS Cloud Development Kit',          'name' => 'AWS CDK',                  'slug' => 'aws-cloud-development-kit', 'abbreviation' => 'AWS CDK', 'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://aws.amazon.com/cdk/',                                                 'wiki_page' => 'https://en.wikipedia.org/wiki/AWS_Cloud_Development_Kit'       ],
            [ 'id' => 58,  'full_name' => 'other',                              'name' => 'other',                    'slug' => 'other',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => null,                                                                          'wiki_page' => null                                                            ],
        ];
        \App\Models\Dictionary\Framework::insert($data);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::connection('dictionary_db')->dropIfExists('frameworks');
    }
};
