<?php

use App\Models\Portfolio\Video;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * The tag used to identify the portfolio database.
     *
     * @var string
     */
    protected $database_tag = 'portfolio_db';

    /**
     * The id of the admin who owns the portfolio video resource.
     *
     * @var int
     */
    protected $ownerId = 2;

    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::connection($this->database_tag)->create('videos', function (Blueprint $table) {
            $table->id();
            $table->foreignIdFor(\App\Models\System\Owner::class, 'owner_id');
            $table->string('name')->unique();
            $table->string('slug')->unique();
            $table->foreignIdFor(\App\Models\Portfolio\Video::class, 'parent_id')->nullable();
            $table->tinyInteger('featured')->default(0);
            $table->string('summary')->nullable();
            $table->tinyInteger('full_episode')->default(1);
            $table->tinyInteger('clip')->default(1);
            $table->tinyInteger('public_access')->default(1);
            $table->tinyInteger('source_footage')->default(1);
            $table->date('date')->nullable();
            $table->year('year')->nullable();
            $table->string('company')->nullable();
            $table->string('credit')->nullable();
            $table->string('show')->nullable();
            $table->string('location')->nullable();
            $table->text('embed')->nullable();
            $table->string('video_url')->nullable();
            $table->text('notes')->nullable();
            $table->string('link', 500)->nullable();
            $table->string('link_name')->nullable();
            $table->text('description')->nullable();
            $table->string('image', 500)->nullable();
            $table->string('image_credit')->nullable();
            $table->string('image_source')->nullable();
            $table->string('thumbnail', 500)->nullable();
            $table->integer('sequence')->default(0);
            $table->tinyInteger('public')->default(1);
            $table->tinyInteger('readonly')->default(0);
            $table->tinyInteger('root')->default(0);
            $table->tinyInteger('disabled')->default(0);
            $table->timestamps();
            $table->softDeletes();

            $table->unique(['owner_id', 'name'], 'owner_id_name_unique');
            $table->unique(['owner_id', 'slug'], 'owner_id_slug_unique');
        });

        $data = [
            [
                'id'             => 1,
                'name'           => 'Live Around Town - episode 1',
                'slug'           => 'live-around-town-episode-1',
                'featured'       => 1,
                'summary'        => null,
                'full_episode'   => 1,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 1994,
                'company'        => 'No Place Like Home Productions',
                'credit'         => 'Craig Zearfoss, Rob Linder',
                'show'           => 'Live Around Town',
                'location'       => 'Chapel Hill, NC and Raleigh, NC',
                'public'         => 1,
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/vGobMdqmulI?si=AvM5y69Pgkv_6FKD" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/vGobMdqmulI?si=84OJZ8hM2P2BhKHk',
                'link_name'      => 'YouTube',
                'description'    => '',
            ],
            [
                'id'             => 2,
                'name'           => 'Live Around Town - episode 2',
                'slug'           => 'live-around-town-episode-2',
                'featured'       => 1,
                'summary'        => null,
                'full_episode'   => 1,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 1994,
                'company'        => 'No Place Like Home Productions',
                'credit'         => 'Craig Zearfoss, Rob Linder',
                'show'           => 'Live Around Town',
                'location'       => 'Chapel Hill, NC and Raleigh, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/DCfjWDD4HMw?si=JRxmqHcYMP8zLfqK" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/DCfjWDD4HMw?si=ozn-YOXDbDQVLaCH',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 3,
                'name'           => 'Live Around Town - episode 3',
                'slug'           => 'live-around-town-episode-3',
                'featured'       => 1,
                'summary'        => null,
                'full_episode'   => 1,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 1994,
                'company'        => 'No Place Like Home Productions',
                'credit'         => 'Craig Zearfoss, Rob Linder',
                'show'           => 'Live Around Town',
                'location'       => 'Chapel Hill, NC and Raleigh, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/QpoHRSwvC6I?si=6qRTz4e8mwB9Bh8V" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/QpoHRSwvC6I?si=yqoYiulhq2Mm-82W',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 4,
                'name'           => 'Live Around Town - episode 4',
                'slug'           => 'live-around-town-episode-4',
                'featured'       => 1,
                'summary'        => null,
                'full_episode'   => 1,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 1994,
                'company'        => 'No Place Like Home Productions',
                'credit'         => 'Craig Zearfoss, Rob Linder',
                'show'           => 'Live Around Town',
                'location'       => 'Chapel Hill, NC and Raleigh, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/PJ_rOzaCMTE?si=yIoLIlXwRUPVInb3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/PJ_rOzaCMTE?si=Rq4J13VnMIR25gIs',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 5,
                'name'           => 'Live Around Town - episode 5',
                'slug'           => 'live-around-town-episode-5',
                'featured'       => 1,
                'summary'        => null,
                'full_episode'   => 1,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 1994,
                'company'        => 'No Place Like Home Productions',
                'credit'         => 'Craig Zearfoss, Rob Linder',
                'show'           => 'Live Around Town',
                'location'       => 'Chapel Hill, NC and Raleigh, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/iOSVHuAXYlU?si=jv990XSee1DJBoDS" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/iOSVHuAXYlU?si=dnGV-wUAUPKVOlk3',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 6,
                'name'           => 'Bandelirium from the Cave in Chapel Hill, NC - episode 1',
                'slug'           => 'bandelirium-from-the-cave-in-chapel-hill-nc-episode-1',
                'featured'       => 1,
                'summary'        => null,
                'full_episode'   => 1,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 1998,
                'company'        => 'Z-TV','credit' => 'Crispy Bess, Mr. Mouse, Craig Zearfoss, Robby Poore, John Andrews Wilson, Evangeline Christie',
                'show'           => 'Bandelirium',
                'location'       => 'Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/CxHwQM74eno?si=Bm_62bBD2RO1zTYd" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/CxHwQM74eno?si=Bm_62bBD2RO1zTYd',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 7,
                'name'           => 'Bandelirium from the Cave in Chapel Hill, NC - episode 2',
                'slug'           => 'bandelirium-from-the-cave-in-chapel-hill-nc-episode-2',
                'featured'       => 1,
                'summary'        => null,
                'full_episode'   => 1,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 1998,
                'company'        => 'Z-TV',
                'credit'         => 'Crispy Bess, Mr. Mouse, Craig Zearfoss, Robby Poore, John Andrews Wilson, Evangeline Christie',
                'show'           => 'Bandelirium',
                'location'       => 'Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/QtmqTI1YK2M?si=JyhqD3-IeHgZW7nG" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/QtmqTI1YK2M?si=JyhqD3-IeHgZW7nG',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 8,
                'name'           => 'Bandelirium from the Cave in Chapel Hill, NC - episode 3',
                'slug'           => 'bandelirium-from-the-cave-in-chapel-hill-nc-episode-3',
                'featured'       => 1,
                'summary'        => null,
                'full_episode'   => 1,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 1998,
                'company'        => 'Z-TV',
                'credit'         => 'Crispy Bess, Mr. Mouse, Craig Zearfoss, Robby Poore, John Andrews Wilson, Evangeline Christie',
                'show'           => 'Bandelirium',
                'location'       => 'Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/7yDv19IU9EY?si=giCY3E8ESHCW0PBZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/7yDv19IU9EY?si=giCY3E8ESHCW0PBZ',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 9,
                'name'           => 'Sleazefest: The Movie',
                'slug'           => 'sleazefest-the-movie',
                'featured'       => 1,
                'summary'        => null,
                'full_episode'   => 1,
                'clip'           => 0,
                'public_access'  => 0,
                'source_footage' => 0,
                'year'           => 1995,
                'company'        => 'No Place Like Home Productions',
                'credit'         => 'Craig Zearfoss, Rob Linder, Matt Johnson, Dave Schmitt',
                'show'           => null,
                'location'       => 'Local 506, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/EFUzw85z8hU?si=VCNpyJPI8qgEFZvw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/EFUzw85z8hU?si=KxJ6WE0TNO_Ow0Bg',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 10,
                'name'           => 'The Woggles - Ramadan Romance',
                'slug'           => 'ramadan-romance-by-the-woggles',
                'featured'       => 1,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 0,
                'source_footage' => 0,
                'year'           => 1998,
                'company'        => 'No Place Like Home Productions',
                'credit'         => 'Craig Zearfoss, Davis Stillson',
                'show'           => null,
                'location'       => 'Star Bar, Atlanta, GA',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/NjiOGW_wkIY?si=mLqG3hPcqm6lpEx2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/NjiOGW_wkIY?si=DLblWHZD8gGyENWC',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],

            [
                'id'             => 12,
                'name'           => 'The Tallboys on Live @ the Cave',
                'slug'           => 'the-tallboys-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/1sp_U2ROdn8?si=c3bObeeIa30b5_It" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/1sp_U2ROdn8?si=_P3nIBuPfbjPVb4l',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 13,
                'name'           => 'Shark Quest on Live @ the Cave',
                'slug'           => 'shark-quest-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/BVLFp-Pe2m0?si=AdYE6hQ2Rd4B5bGa" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/BVLFp-Pe2m0?si=AdYE6hQ2Rd4B5bGa',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 14,
                'name'           => 'Lud on Live @ the Cave',
                'slug'           => 'lud-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/CWDu6Vou2mo?si=H0gTFXyScmYisuTI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/CWDu6Vou2mo?si=H0gTFXyScmYisuTI',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 15,
                'name'           => 'Transportation on Live @ the Cave',
                'slug'           => 'transportation-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/QpW8PIWGs5I?si=JwX9hpWJmpv1Q5lO" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/QpW8PIWGs5I?si=JwX9hpWJmpv1Q5lO',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 16,
                'name'           => 'Trailer Bride on Live @ the Cave',
                'slug'           => 'trailer-bride-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/gibuGcpZF7A?si=sSZRfKFgVvlSyd4a" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/gibuGcpZF7A?si=sSZRfKFgVvlSyd4a',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 17,
                'name'           => 'Evil Wiener on Live @ the Cave',
                'slug'           => 'evil-wiener-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/OCpQf5siO0M?si=-qyn6Bo4ukul_MsV" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/OCpQf5siO0M?si=EgcxNKHmUCug74ZH',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 18,
                'name'           => 'Clok-Lok on Live @ the Cave',
                'slug'           => 'clok-lok-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/tacQld_hcGg?si=cOCdBlDT3B_Whdpi" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/tacQld_hcGg?si=cOCdBlDT3B_Whdpi',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 19,
                'name'           => 'Ghost of Rock on Live @ the Cave',
                'slug'           => 'ghost-of-rock-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/2E-2ZvvMYV8?si=1vsUbToX709hmCjz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/2E-2ZvvMYV8?si=1vsUbToX709hmCjz',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 20,
                'name'           => 'Morris on Live @ the Cave',
                'slug'           => 'morris--on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => 'https://youtu.be/VTVv3Mk8OtI?si=-vsYSlR34IAubT92',
                'link'           => 'https://youtu.be/VTVv3Mk8OtI?si=-vsYSlR34IAubT92',
                'link_name'      => 'YouTube',
                'description'    => 'Performing I\' Not the One to Choose',
                'public'         => 1,
            ],
            [
                'id'             => 21,
                'name'           => 'Chris Smith on Live @ the Cave',
                'slug'           => 'chris-smith-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/H0hg22giaDM?si=3ojMppZcK8E2R384" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/H0hg22giaDM?si=3ojMppZcK8E2R384',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 22,
                'name'           => 'Kitty Box and the Alley Cats on Live @ the Cave',
                'slug'           => 'bitty-box-and-the-alley-cats-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/v8oteqf-nW8?si=BvxEnbk1DnrLyYAI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/v8oteqf-nW8?si=BvxEnbk1DnrLyYAI',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 23,
                'name'           => 'Dom Casual on Live @ the Cave',
                'slug'           => 'dom-casual-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/wHp9bObySSk?si=50KhLnbPlOI28iw7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/wHp9bObySSk?si=50KhLnbPlOI28iw7',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 24,
                'name'           => 'Malt Swagger on Live @ the Cave',
                'slug'           => 'malt-swagger-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/LUcldiQPy7A?si=1DhP8BycELWb2lN-" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/LUcldiQPy7A?si=1DhP8BycELWb2lN-',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 25,
                'name'           => 'The Lucy Stoners - on Live @ the Cave',
                'slug'           => 'the-lucy-stones-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/YFGyGs61D9U?si=iXrbYUmiIQxU4cIa" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/YFGyGs61D9U?si=bnES-w4eTwyY7mCy',
                'link_name'      => 'YouTube',
                'description'    => 'Performing Not Half of Us.',
                'public'         => 1,
            ],
            [
                'id'             => 26,
                'name'           => 'Chuck Chuck Goose on Live @ the Cave',
                'slug'           => 'chuck-chuck-goose-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/C1N8np3OOGM?si=bftOeUZ5pOlA--9J" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/C1N8np3OOGM?si=bftOeUZ5pOlA--9J',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 27,
                'name'           => 'David Spencer on Live @ the Cave',
                'slug'           => 'david-spencer-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/CL5pVZoIGkU?si=O-C--dbGqVWEa0uv" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/CL5pVZoIGkU?si=O-C--dbGqVWEa0uv',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 28,
                'name'           => 'Roman Candles on Live @ the Cave',
                'slug'           => 'roman-candles-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/a4Jm6FokBso?si=dQqMupWCigGDN9-W" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/a4Jm6FokBso?si=dQqMupWCigGDN9-W',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 29,
                'name'           => 'Hobart Willis and the Back Forty on Live @ the Cave',
                'slug'           => 'hobart-willis-and-the-back-forty-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/BcP-0LC8nUQ?si=OxgDpCmkNaQhcudZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/BcP-0LC8nUQ?si=OxgDpCmkNaQhcudZ',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 30,
                'name'           => 'Chupa Chup on Live @ the Cave',
                'slug'           => 'chupa-chup-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/J7EBVGJOuGM?si=sdQoP9hCzwI97RYH" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/J7EBVGJOuGM?si=sdQoP9hCzwI97RYH',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 31,
                'name'           => 'Pistol Pete and Popgun Paul on Live @ the Cave',
                'slug'           => 'pistol-pete-and-popgun-paul-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '',
                'link'           => '',
                'link_name'      => '',
                'description'    => 'Performing Never Be Straight',
                'public'         => 1,
            ],
            [
                'id'             => 32,
                'name'           => 'Dexter Romweber on Live @ the Cave',
                'slug'           => 'dexter-romweber-on-live-at-the-cave',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/co6BuJKbUcc?si=90y73q0D_nvNmlfu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/co6BuJKbUcc?si=90y73q0D_nvNmlfu',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 33,
                'name'           => 'Dexter Romweber on Live @ the Cave - Brazil',
                'slug'           => 'dexter-romweber-on-live-at-the-cave-brazil',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Z-TV',
                'credit'         => '',
                'show'           => 'Live @ the Cave',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/mI04UiU_smI?si=aF_z7B5rpbUcUpmg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/mI04UiU_smI?si=aF_z7B5rpbUcUpmg',
                'link_name'      => 'YouTube',
                'description'    => 'Performing Brazil',
                'public'         => 1,
            ],
            [
                'id'             => 34,
                'name'           => 'Z-TV with Dexter Romweber',
                'slug'           => 'z-tv-with-dexter-romweber',
                'featured'       => 1,
                'summary'        => null,
                'full_episode'   => 1,
                'clip'           => 0,
                'public_access'  => 1,
                'source_footage' => 0,
                'year'           => 1998,
                'company'        => 'Z-TV',
                'credit'         => 'Mr. Mouse and Craig Zearfoss',
                'show'           => 'Z-TV',
                'location'       => 'The Cave, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/zQcKf3Bk6mA?si=M0R6jZVEo9eo-aPF" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/zQcKf3Bk6mA?si=M0R6jZVEo9eo-aPF',
                'link_name'      => 'YouTube',
                'description'    => '',
                'public'         => 1,
            ],
            [
                'id'             => 35,
                'name'           => 'Dreadful - The Somnambulist Project',
                'slug'           => 'dreadful-the-somnambulist-project',
                'featured'       => 1,
                'summary'        => null,
                'full_episode'   => 1,
                'clip'           => 0,
                'public_access'  => 0,
                'source_footage' => 0,
                'year'           => 1995,
                'company'        => 'Somnambulist Project',
                'credit'         => '',
                'show'           => null,
                'location'       => 'Forest Theater, Chapel Hill, NC',
                'embed'          => '<iframe width="560" height="315" src="https://www.youtube.com/embed/kggOFqg5zYg?si=vJSWXsQ3qvi8pBYR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                'link'           => 'https://youtu.be/kggOFqg5zYg?si=vJSWXsQ3qvi8pBYR',
                'link_name'      => 'YouTube',
                'description'    => 'Conceived, written, and directed by Jason Arkles, this play won accolades as one of the top ten theatrical productions of the year, featuring his puppetry as well as the music by music director Curtis Eller along with the Dreadful Quartet.',
                'public'         => 1,
            ],
            [
                'id'             => 36,
                'name'           => 'The Serpent - The Somnambulist Project - 1995 Carrboro Arts Center',
                'slug'           => 'the-serpent-the-somnambulist-project-1995-carrboro-arts-center',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 1,
                'clip'           => 0,
                'public_access'  => 0,
                'source_footage' => 0,
                'year'           => 2000,
                'company'        => 'Somnambulist Project',
                'credit'         => '',
                'show'           => null,
                'location'       => 'Carrboro Arts Center, Carrboro, NC',
                'embed'          => '',
                'link'           => '',
                'link_name'      => '',
                'description'    => '',
                'public'         => 1,
            ],

            /*
            [
                'id'             => 11,
                'name'           => '',
                'slug'           => '',
                'featured'       => 0,
                'summary'        => null,
                'full_episode'   => 0,
                'clip'           => 0,
                'public_access'  => 0,
                'source_footage' => 0,
                'year'           => 2025,
                'company'        => '',
                'credit'         => '',
                'show'           => null,
                'location'       => '',
                'embed'          => '',
                'link'           => '',
                'link_name'      => '',
                'description'    => '',
                'public'         => 1,
            ],
            */
        ];

        // add timestamps and owner_ids
        for($i=0; $i<count($data);$i++) {
            $data[$i]['created_at'] = now();
            $data[$i]['updated_at'] = now();
            $data[$i]['owner_id']   = $this->ownerId;
        }

        Video::insert($data);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::connection($this->database_tag)->dropIfExists('videos');
    }
};
