<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::connection('dictionary_db')->create('languages', function (Blueprint $table) {
            $table->id();
            $table->string('full_name')->unique();
            $table->string('name', 100)->unique();
            $table->string('slug', 100)->unique();
            $table->string('abbreviation', 100)->nullable();
            $table->tinyInteger('open_source')->default(0);
            $table->tinyInteger('proprietary')->default(0);
            $table->tinyInteger('compiled')->default(0);
            $table->string('owner', 100)->nullable();
            $table->string('website')->nullable();
            $table->string('wiki_page')->nullable();
            $table->text('description')->nullable();
        });

        $data = [
            [ 'id' => 1,  'name' => 'ASP',          'full_name' => 'Active Server Pages',                           'slug' => 'active-server-pages',      'abbreviation' => 'ASP',     'open_source' => 0, 'proprietary' => 1, 'compiled' => 1, 'owner' => 'Microsoft',  'website' => 'https://dotnet.microsoft.com/en-us/apps/aspnet', 'wiki_page' => 'https://en.wikipedia.org/wiki/Active_Server_Pages' ],
            [ 'id' => 2,  'name' => 'Apex',         'full_name' => 'Apex',                                          'slug' => 'apex',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 1, 'compiled' => 0, 'owner' => 'Salesforce', 'website' => 'https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_intro_what_is_apex.htm', 'wiki_page' => 'https://en.wikipedia.org/wiki/Apex' ],
            [ 'id' => 3,  'name' => 'AppleScript',  'full_name' => 'AppleScript',                                   'slug' => 'applescript',              'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => 'Apple',      'website' => 'https://developer.apple.com/library/archive/documentation/AppleScript/Conceptual/AppleScriptLangGuide/introduction/ASLR_intro.html', 'wiki_page' => 'https://en.wikipedia.org/wiki/AppleScript' ],
            [ 'id' => 4,  'name' => 'AspectJ',      'full_name' => 'AspectJ',                                       'slug' => 'aspectj',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 1, 'owner' => null,           'website' => 'http://eclipse.dev/aspectj/', 'wiki_page' => 'https://en.wikipedia.org/wiki/AspectJ' ],
            [ 'id' => 5,  'name' => 'assembly',     'full_name' => 'assembly language',                             'slug' => 'assembly-language',        'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 1, 'owner' => null,           'website' => null, 'wiki_page' => 'https://en.wikipedia.org/wiki/Assembly_language' ],
            [ 'id' => 6,  'name' => 'C',            'full_name' => 'C',                                             'slug' => 'c',                        'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 1, 'owner' => null,           'website' => 'https://en.cppreference.com/w/c/language.html', 'wiki_page' => 'https://en.wikipedia.org/wiki/C_(programming_language)' ],
            [ 'id' => 7,  'name' => 'C++',          'full_name' => 'C++',                                           'slug' => 'c-plus-plus',              'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 1, 'owner' => null,           'website' => 'https://isocpp.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/C%2B%2B' ],
            [ 'id' => 8,  'name' => 'C#',           'full_name' => 'C#',                                            'slug' => 'c-sharp',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 1, 'owner' => null,           'website' => 'https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/', 'wiki_page' => 'https://en.wikipedia.org/wiki/C_Sharp_(programming_language)' ],
            [ 'id' => 9,  'name' => 'CSS',          'full_name' => 'Cascading Style Sheets',                        'slug' => 'css',                      'abbreviation' => 'CSS',     'open_source' => 1, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://developer.mozilla.org/en-US/docs/Web/CSS', 'wiki_page' => 'https://en.wikipedia.org/wiki/CSS' ],
            [ 'id' => 10, 'name' => 'COBOL',        'full_name' => 'COBOL',                                         'slug' => 'cobol',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 1, 'owner' => null,           'website' => 'https://www.ibm.com/think/topics/cobol', 'wiki_page' => 'https://en.wikipedia.org/wiki/COBOL' ],
            [ 'id' => 11, 'name' => 'CoffeeScript', 'full_name' => 'CoffeeScript',                                  'slug' => 'coffeescript',             'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 1, 'owner' => null,           'website' => 'https://coffeescript.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/CoffeeScript' ],
            [ 'id' => 12, 'name' => 'ColdFusion',   'full_name' => 'ColdFusion',                                    'slug' => 'coldfusion',               'abbreviation' => 'CFML',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => 'Adobe',      'website' => 'https://www.adobe.com/products/coldfusion-family.html', 'wiki_page' => 'https://en.wikipedia.org/wiki/Adobe_ColdFusion' ],
            [ 'id' => 13, 'name' => 'Curl',         'full_name' => 'Curl',                                          'slug' => 'curl',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.curl.com/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Curl_(programming_language)' ],
            [ 'id' => 14, 'name' => 'D',            'full_name' => 'D',                                             'slug' => 'd',                        'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://dlang.org/', 'wiki_page' => 'https://simple.wikipedia.org/wiki/D_(programming_language)' ],
            [ 'id' => 15, 'name' => 'Dart',         'full_name' => 'Dart',                                          'slug' => 'dart',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://dart.dev/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Dart_(programming_language)' ],
            [ 'id' => 16, 'name' => 'DCL',          'full_name' => 'DIGITAL Command Language',                      'slug' => 'digital-command-language', 'abbreviation' => 'DCL',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => null, 'wiki_page' => 'https://en.wikipedia.org/wiki/DIGITAL_Command_Language' ],
            [ 'id' => 17, 'name' => 'ECMAScript',   'full_name' => 'ECMAScript',                                    'slug' => 'ecmascript',               'abbreviation' => null,      'open_source' => 1, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://developer.mozilla.org/en-US/docs/Glossary/ECMAScript', 'wiki_page' => 'https://en.wikipedia.org/wiki/ECMAScript' ],
            [ 'id' => 18, 'name' => 'ECL',          'full_name' => 'Embeddable Common Lisp',                        'slug' => 'embeddable-common-lisp',   'abbreviation' => 'ECL',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://ecl.common-lisp.dev/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Embeddable_Common_Lisp' ],
            [ 'id' => 19, 'name' => 'Elixir',       'full_name' => 'Elixir',                                        'slug' => 'elixir',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://elixir-lang.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Elixir_(programming_language)' ],
            [ 'id' => 20, 'name' => 'Erlang',       'full_name' => 'Erlang',                                        'slug' => 'erlang',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.erlang.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Erlang_(programming_language)' ],
            [ 'id' => 21, 'name' => 'XHTML',        'full_name' => 'Extensible HyperText Markup Language',          'slug' => 'xhtml',                    'abbreviation' => 'XHTML',   'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://developer.mozilla.org/en-US/docs/Glossary/XHTML', 'wiki_page' => 'https://en.wikipedia.org/wiki/XHTML#:~:text=Extensible%20HyperText%20Markup%20Language%20(XHTML,Filename%20extension' ],
            [ 'id' => 22, 'name' => 'XML',          'full_name' => 'Extensible Markup Language',                    'slug' => 'xml',                      'abbreviation' => 'XML',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.w3.org/TR/xml/', 'wiki_page' => 'https://en.wikipedia.org/wiki/XML' ],
            [ 'id' => 23, 'name' => 'XSLT',         'full_name' => 'Extensible Stylesheet Language Transformation', 'slug' => 'extensible-stylesheet-language-transformation', 'abbreviation' => 'XSLT', 'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => 'https://en.wikipedia.org/wiki/XSLT',           'website' => 'https://www.w3.org/TR/xslt-30/', 'wiki_page' => null ],
            [ 'id' => 24, 'name' => 'Fortran',      'full_name' => 'Fortran',                                       'slug' => 'fortran',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://fortran-lang.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Fortran' ],
            [ 'id' => 25, 'name' => 'Go',           'full_name' => 'Go',                                            'slug' => 'go',                       'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://go.dev/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Go_(programming_language)' ],
            [ 'id' => 26, 'name' => 'GQL',          'full_name' => 'Graphic Query Language',                        'slug' => 'gql',                      'abbreviation' => 'GQL',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://graphql.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Graph_Query_Language' ],
            [ 'id' => 27, 'name' => 'Groovy',       'full_name' => 'Groovy',                                        'slug' => 'groovy',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://groovy-lang.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Apache_Groovy' ],
            [ 'id' => 28, 'name' => 'Hack',         'full_name' => 'Hack',                                          'slug' => 'hack',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://hacklang.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Hack_(programming_language)' ],
            [ 'id' => 29, 'name' => 'Haskell',      'full_name' => 'Haskell',                                       'slug' => 'haskell',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.haskell.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Haskell' ],
            [ 'id' => 30, 'name' => 'HTML',         'full_name' => 'HyperText Markup Language',                     'slug' => 'html',                     'abbreviation' => 'HTML',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://developer.mozilla.org/en-US/docs/Web/HTML', 'wiki_page' => 'https://en.wikipedia.org/wiki/HTML' ],
            [ 'id' => 31, 'name' => 'HTML5',        'full_name' => 'HyperText Markup Language 5',                   'slug' => 'html5',                    'abbreviation' => 'HTML5',   'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://developer.mozilla.org/en-US/docs/Glossary/HTML5', 'wiki_page' => 'https://en.wikipedia.org/wiki/HTML5' ],
            [ 'id' => 32, 'name' => 'Java',         'full_name' => 'Java',                                          'slug' => 'java',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 1, 'owner' => 'Oracle',     'website' => 'https://www.java.com/en/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Java_(programming_language)' ],
            [ 'id' => 33, 'name' => 'JavaScript',   'full_name' => 'JavaScript',                                    'slug' => 'javascript',               'abbreviation' => 'JS',      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', 'wiki_page' => 'https://en.wikipedia.org/wiki/JavaScript' ],
            [ 'id' => 34, 'name' => 'JCL',          'full_name' => 'Job Control Language',                          'slug' => 'job-control-language',     'abbreviation' => 'JCL',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => null, 'wiki_page' => 'https://en.wikipedia.org/wiki/Job_Control_Language' ],
            [ 'id' => 35, 'name' => 'Julia',        'full_name' => 'Julia',                                         'slug' => 'julia',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://julialang.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Julia_(programming_language)' ],
            [ 'id' => 36, 'name' => 'Kotlin',       'full_name' => 'Kotlin',                                        'slug' => 'kotlin',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://kotlinlang.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Kotlin_(programming_language)' ],
            [ 'id' => 37, 'name' => 'LESS',         'full_name' => 'LESS',                                          'slug' => 'less',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://lesscss.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Less_(style_sheet_language)' ],
            [ 'id' => 38, 'name' => 'Lisp',         'full_name' => 'Lisp',                                          'slug' => 'lisp',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://lisp-lang.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Lisp_(programming_language' ],
            [ 'id' => 39, 'name' => 'Lua',          'full_name' => 'Lua',                                           'slug' => 'lua',                      'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.lua.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Lua' ],
            [ 'id' => 40, 'name' => 'm4',           'full_name' => 'm4',                                            'slug' => 'm4',                       'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => null, 'wiki_page' => 'https://en.wikipedia.org/wiki/M4_(computer_language)' ],
            [ 'id' => 41, 'name' => 'Markdown',     'full_name' => 'Markdown',                                      'slug' => 'markdown',                 'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.markdownguide.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Markdown' ],
            [ 'id' => 42, 'name' => 'NetRexx',      'full_name' => 'NetRexx',                                       'slug' => 'netrexx',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.netrexx.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/NetRexx' ],
            [ 'id' => 43, 'name' => 'NoSQL',        'full_name' => 'NoSQL',                                         'slug' => 'nosql',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => null, 'wiki_page' => 'https://en.wikipedia.org/wiki/NoSQL' ],
            [ 'id' => 44, 'name' => 'GLSL',         'full_name' => 'OpenGL Shading Language',                       'slug' => 'glsl',                     'abbreviation' => 'GLSL',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://learnopengl.com/Getting-started/Shaders', 'wiki_page' => 'https://en.wikipedia.org/wiki/OpenGL_Shading_Language' ],
            [ 'id' => 45, 'name' => 'Pascal',       'full_name' => 'Pascal',                                        'slug' => 'pascal',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => null, 'wiki_page' => 'https://en.wikipedia.org/wiki/Pascal_(programming_language)' ],
            [ 'id' => 46, 'name' => 'PHP',          'full_name' => 'Personal Home Page',                            'slug' => 'php',                      'abbreviation' => 'PHP',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.php.net/', 'wiki_page' => 'https://en.wikipedia.org/wiki/PHP' ],
            [ 'id' => 47, 'name' => 'PowerShell',   'full_name' => 'PowerShell',                                    'slug' => 'powershell',               'abbreviation' => null,      'open_source' => 1, 'proprietary' => 0, 'compiled' => 0, 'owner' => 'Microsoft',  'website' => 'https://learn.microsoft.com/en-us/powershell/', 'wiki_page' => 'https://en.wikipedia.org/wiki/PowerShell' ],
            [ 'id' => 48, 'name' => 'Preact',       'full_name' => 'Preact',                                        'slug' => 'preact',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://preactjs.com/', 'wiki_page' => null ],
            [ 'id' => 49, 'name' => 'Pure',         'full_name' => 'Pure',                                          'slug' => 'pure',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://agraef.github.io/pure-lang/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Pure_(programming_language)' ],
            [ 'id' => 50, 'name' => 'Python',       'full_name' => 'Python',                                        'slug' => 'python',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.python.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Python' ],
            [ 'id' => 51, 'name' => 'R',            'full_name' => 'R',                                             'slug' => 'r',                        'abbreviation' => 'R',       'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.r-project.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/R_(programming_language)' ],
            [ 'id' => 52, 'name' => 'Raku',         'full_name' => 'Raku',                                          'slug' => 'raku',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://raku.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Raku_(programming_language)' ],
            [ 'id' => 53, 'name' => 'Rebol',        'full_name' => 'Rebol',                                         'slug' => 'rebol',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.rebol.com/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Rebol' ],
            [ 'id' => 54, 'name' => 'Red',          'full_name' => 'Red',                                           'slug' => 'red',                      'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.red-lang.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Red_(programming_language)' ],
            [ 'id' => 55, 'name' => 'RAML',         'full_name' => 'RESTful API Modeling Language',                 'slug' => 'raml',                     'abbreviation' => 'RAML',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://raml.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/RAML_(software)' ],
            [ 'id' => 56, 'name' => 'Rexx',         'full_name' => 'Rexx',                                          'slug' => 'rexx',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://en.wikibooks.org/wiki/Rexx_Programming', 'wiki_page' => 'https://en.wikipedia.org/wiki/Rexx' ],
            [ 'id' => 57, 'name' => 'Rspec',        'full_name' => 'Rspec',                                         'slug' => 'rpsec',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://rspec.info/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Rspec' ],
            [ 'id' => 58, 'name' => 'Ruby',         'full_name' => 'Ruby',                                          'slug' => 'ruby',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.ruby-lang.org/en/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Ruby' ],
            [ 'id' => 59, 'name' => 'Rust',         'full_name' => 'Rust',                                          'slug' => 'rust',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.rust-lang.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Rust_(programming_language)' ],
            [ 'id' => 60, 'name' => 'SAS',          'full_name' => 'Statistical Analysis System',                   'slug' => 'sas',                      'abbreviation' => 'SAS',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.sas.com/en_us/software/base-sas.html', 'wiki_page' => 'https://en.wikipedia.org/wiki/SAS_language' ],
            [ 'id' => 61, 'name' => 'Sassy CSS',    'full_name' => 'Sassy CSS',                                     'slug' => 'sassy-css',                'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://medium.com/@jgoz/sassy-css-scss-quick-guide-b38f51c6868a', 'wiki_page' => null ],
            [ 'id' => 62, 'name' => 'Scala',        'full_name' => 'Scala',                                         'slug' => 'scala',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.scala-lang.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Scala_(programming_language)' ],
            [ 'id' => 63, 'name' => 'Scheme',       'full_name' => 'Scheme',                                        'slug' => 'scheme',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.scheme.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Scheme_(programming_language)' ],
            [ 'id' => 64, 'name' => 'Scribe',       'full_name' => 'Scribe',                                        'slug' => 'scribe',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => null, 'wiki_page' => 'https://en.wikipedia.org/wiki/Scribe_(markup_language)' ],
            [ 'id' => 65, 'name' => 'SGML',         'full_name' => 'Standard Generalized Markup Language',          'slug' => 'sgml',                     'abbreviation' => 'SGML',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => null, 'wiki_page' => 'https://developer.mozilla.org/en-US/docs/Glossary/SGML' ],
            [ 'id' => 66, 'name' => 'SQL',          'full_name' => 'Structured Query Language',                     'slug' => 'sql',                      'abbreviation' => 'SQL',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => null, 'wiki_page' => 'https://en.wikipedia.org/wiki/SQL' ],
            [ 'id' => 67, 'name' => 'Swift',        'full_name' => 'Swift',                                         'slug' => 'swift',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.swift.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Swift_(programming_language)' ],
            [ 'id' => 68, 'name' => 'SASS',         'full_name' => 'Syntactically Awesome Style Sheets',            'slug' => 'sass',                     'abbreviation' => 'SASS',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://sass-lang.com/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Sass_(style_sheet_language)' ],
            [ 'id' => 69, 'name' => 'TCL',          'full_name' => 'Tool Command Language',                         'slug' => 'tool-command-language',    'abbreviation' => 'TCL',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.tcl-lang.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Tcl' ],
            [ 'id' => 70, 'name' => 'TypeScript',   'full_name' => 'TypeScript',                                    'slug' => 'typescript',               'abbreviation' => 'TS',      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.typescriptlang.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/TypeScript' ],
            [ 'id' => 71, 'name' => 'VBScript',     'full_name' => 'VBScript',                                      'slug' => 'VBScript',                 'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => 'Microsoft',  'website' => null, 'wiki_page' => 'https://en.wikipedia.org/wiki/VBScript' ],
            [ 'id' => 72, 'name' => 'Visual Basic', 'full_name' => 'Visual Basic',                                  'slug' => 'visual-basic',             'abbreviation' => 'VB',      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://learn.microsoft.com/en-us/dotnet/visual-basic/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Visual_Basic_(.NET)' ],
            [ 'id' => 73, 'name' => 'WSDL',         'full_name' => 'Web Services Description Language',             'slug' => 'wsdl',                     'abbreviation' => 'WSDL',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.w3.org/TR/2007/REC-wsdl20-20070626/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Web_Services_Description_Language' ],
            [ 'id' => 74, 'name' => 'Wolfram',      'full_name' => 'Wolfram Mathematica',                           'slug' => 'wolfram-mathematica',      'abbreviation' => 'Wolfram', 'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.wolfram.com/language/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Wolfram_Mathematica' ],
            [ 'id' => 75, 'name' => 'WFL',          'full_name' => 'Work Flow Language',                            'slug' => 'work-flow-language',       'abbreviation' => 'WFL',     'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => null, 'wiki_page' => 'https://en.wikipedia.org/wiki/Work_Flow_Language' ],
            [ 'id' => 76, 'name' => 'YAML',         'full_name' => 'YAML',                                          'slug' => 'yaml',                     'abbreviation' => 'YAML',    'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://yaml.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/YAML' ],
            [ 'id' => 77, 'name' => 'PL/SQL',       'full_name' => 'PL/SQL',                                        'slug' => 'pl-sql',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.oracle.com/database/technologies/appdev/plsql.html', 'wiki_page' => 'https://en.wikipedia.org/wiki/PL/SQL' ],
            [ 'id' => 78, 'name' => 'Perl',         'full_name' => 'Perl',                                          'slug' => 'perl',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'compiled' => 0, 'owner' => null,           'website' => 'https://www.perl.org/', 'wiki_page' => 'https://en.wikipedia.org/wiki/Perl' ],
        ];
        \App\Models\Dictionary\Language::insert($data);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::connection('dictionary_db')->dropIfExists('languages');
    }
};
