<?php

use App\Models\Dictionary\Library;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    protected $database_tag = 'dictionary_db';

    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::connection($this->database_tag)->create('libraries', function (Blueprint $table) {
            $table->id();
            $table->string('full_name')->unique();
            $table->string('name', 100)->unique();
            $table->string('slug', 100)->unique();
            $table->string('abbreviation', 20)->nullable();
            $table->string('definition', 500)->nullable();
            $table->boolean('open_source')->default(false);
            $table->boolean('proprietary')->default(false);
            $table->boolean('compiled')->default(false);
            $table->string('owner', 100)->nullable();
            $table->string('wikipedia', 500)->nullable();
            $table->string('link', 500)->nullable();
            $table->string('link_name')->nullable();
            $table->text('description')->nullable();
            $table->string('image', 500)->nullable();
            $table->string('image_credit')->nullable();
            $table->string('image_source')->nullable();
            $table->string('thumbnail', 500)->nullable();
            $table->boolean('public')->default(true);
            $table->boolean('readonly')->default(false);
            $table->boolean('root')->default(false);
            $table->boolean('disabled')->default(false);
            $table->integer('sequence')->default(false);
            $table->timestamps();
            $table->softDeletes();
        });

        $data = [
            [ 'id' => 1,   'name' => 'Angular Testing Library',      'full_name' => 'Angular Testing Library',      'slug' => 'angular-testing-library',      'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://testing-library.com/docs/angular-testing-library/intro/',    'wikipedia' => null,                                                             'definition' => 'A light-weight solution for testing web pages by querying and interacting with DOM nodes (whether simulated with JSDOM/Jest or in the browser).' ],
            [ 'id' => 2,   'name' => 'BabylonJS',                    'full_name' => 'BabylonJS',                    'slug' => 'babylonjs',                    'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://www.babylonjs.com/',                                         'wikipedia' => 'https://en.wikipedia.org/wiki/Babylon.js',                       'definition' => 'A JavaScript library and 3D engine for displaying real time 3D graphics in a web browser via HTML5.' ],
            [ 'id' => 3,   'name' => 'Cypress Testing Library',      'full_name' => 'Cypress Testing Library',      'slug' => 'cypress-testing-library',      'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://testing-library.com/docs/cypress-testing-library/intro/',    'wikipedia' => null,                                                             'definition' => 'A library that allows the use of dom-testing queries within Cypress end-to-end browser tests.' ],
            [ 'id' => 4,   'name' => 'Flowbite',                     'full_name' => 'Flowbite',                     'slug' => 'flowbite',                     'abbreviation' => null, 'open_source' => 1, 'proprietary' => 0, 'owner' => null,        'link' => 'https://flowbite.com/',                                              'wikipedia' => null,                                                             'definition' => 'An open-source library of over 600+ UI components, sections, and pages built with the utility classes from Tailwind CSS and designed in Figma.' ],
            [ 'id' => 5,   'name' => 'Hadoop',                       'full_name' => 'Hadoop',                       'slug' => 'hadoop',                       'abbreviation' => null, 'open_source' => 1, 'proprietary' => 0, 'owner' => null,        'link' => 'https://hadoop.apache.org/',                                         'wikipedia' => 'https://en.wikipedia.org/wiki/Apache_Hadoop',                    'definition' => 'A collection of open-source software utilities for reliable, scalable, distributed computing.' ],
            [ 'id' => 6,   'name' => 'Highcharts',                   'full_name' => 'Highcharts',                   'slug' => 'highcharts',                   'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://www.highcharts.com/',                                        'wikipedia' => null,                                                             'definition' => 'A library to create charts and dashboards for web and mobile platforms.' ],
            [ 'id' => 7,   'name' => 'jQuery',                       'full_name' => 'jQuery',                       'slug' => 'jquery',                       'abbreviation' => null, 'open_source' => 1, 'proprietary' => 0, 'owner' => null,        'link' => 'https://jquery.com/',                                                'wikipedia' => 'https://en.wikipedia.org/wiki/Jquery',                           'definition' => 'A JavaScript library designed to simplify HTML DOM tree traversal and manipulation, as well as event handling, CSS animations, and Ajax.' ],
            [ 'id' => 8,   'name' => 'Lucene',                       'full_name' => 'Lucene',                       'slug' => 'lucene',                       'abbreviation' => null, 'open_source' => 1, 'proprietary' => 0, 'owner' => null,        'link' => 'https://lucene.apache.org/',                                         'wikipedia' => 'https://en.wikipedia.org/wiki/Apache_Lucene',                    'definition' => 'A free and open-source search engine software library, originally written in Java by Doug Cutting.' ],
            [ 'id' => 9,   'name' => 'Nightwatch Testing Library',   'full_name' => 'Nightwatch Testing Library',   'slug' => 'nightwatch-testing-library',   'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://testing-library.com/docs/nightwatch-testing-library/intro/', 'wikipedia' => null,                                                             'definition' => 'A library that allows the use of dom-testing-library queries in Nightwatch for end-to-end web testing.' ],
            [ 'id' => 10,  'name' => 'NumPy',                        'full_name' => 'NumPy',                        'slug' => 'numpy',                        'abbreviation' => null, 'open_source' => 1, 'proprietary' => 0, 'owner' => null,        'link' => 'https://numpy.org/',                                                 'wikipedia' => 'https://en.wikipedia.org/wiki/NumPy',                            'definition' => 'A library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.' ],
            [ 'id' => 11,  'name' => 'Playwright',                   'full_name' => 'Playwright',                   'slug' => 'playwright',                   'abbreviation' => null, 'open_source' => 1, 'proprietary' => 0, 'owner' => null,        'link' => 'https://playwright.dev/docs/library',                              'wikipedia' => 'https://en.wikipedia.org/wiki/Playwright_(software)',              'definition' => 'An open-source automation library for browser testing and web scraping[3] developed by Microsoft.' ],
            [ 'id' => 12,  'name' => 'Polymer',                      'full_name' => 'Polymer',                      'slug' => 'polymer',                      'abbreviation' => null, 'open_source' => 1, 'proprietary' => 0, 'owner' => null,        'link' => 'https://polymer-library.polymer-project.org/',                       'wikipedia' => 'https://en.wikipedia.org/wiki/Polymer_(library)',                'definition' => 'An open-source JavaScript library for building web applications using Web Components.' ],
            [ 'id' => 13,  'name' => 'Preact Testing Library',       'full_name' => 'Preact Testing Library',       'slug' => 'preact-testing-library',       'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://testing-library.com/docs/preact-testing-library/intro/',     'wikipedia' => null,                                                             'definition' => 'A very lightweight solution for testing Preact components.' ],
            [ 'id' => 14,  'name' => 'Puppeteer',                    'full_name' => 'Puppeteer',                    'slug' => 'puppeteer',                    'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://pptr.dev/',                                                  'wikipedia' => null,                                                             'definition' => 'A Node.js library to automate Chrome.' ],
            [ 'id' => 15,  'name' => 'Puppeteer Testing Library',    'full_name' => 'Puppeteer Testing Library',    'slug' => 'puppeteer-testing-library',    'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://testing-library.com/docs/pptr-testing-library/intro/',       'wikipedia' => null,                                                             'definition' => 'A lightweight adapter allowing DOM Testing Library to be used with puppeteer.' ],
            [ 'id' => 16,  'name' => 'PyLucene',                     'full_name' => 'PyLucene',                     'slug' => 'pylucene',                     'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://lucene.apache.org/pylucene/',                                'wikipedia' => null,                                                             'definition' => 'An extension for accessing Java Lucene™ to allow you to use Lucene\'s text indexing and searching capabilities from Python.' ],
            [ 'id' => 17,  'name' => 'PySpark',                      'full_name' => 'PySpark',                      'slug' => 'pyspark',                      'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://spark.apache.org/docs/latest/api/python/index.html',         'wikipedia' => null,                                                             'definition' => 'A library that enables you to perform real-time, large-scale data processing in a distributed environment using Python.' ],
            [ 'id' => 18,  'name' => 'React',                        'full_name' => 'React',                        'slug' => 'react',                        'abbreviation' => null, 'open_source' => 1, 'proprietary' => 0, 'owner' => null,        'link' => 'https://react.dev/',                                                 'wikipedia' => 'https://en.wikipedia.org/wiki/React_(software)',                 'definition' => 'A free and open-source front-end JavaScript library that aims to make building user interfaces based on components more "seamless".' ],
            [ 'id' => 19,  'name' => 'React Native Testing Library', 'full_name' => 'React Native Testing Library', 'slug' => 'react-native-testing-library', 'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://callstack.github.io/react-native-testing-library/',          'wikipedia' => null,                                                             'definition' => 'A library to create maintainable tests and test public APIs with React Native apps.' ],
            [ 'id' => 20,  'name' => 'React Testing Library',        'full_name' => 'React Testing Library',        'slug' => 'react-testing-library',        'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://testing-library.com/docs/react-testing-library/intro/',      'wikipedia' => null,                                                             'definition' => 'A library that builds on top of DOM Testing Library by adding APIs for working with React components.' ],
            [ 'id' => 21,  'name' => 'ReactiveX',                    'full_name' => 'ReactiveX',                    'slug' => 'reactivex',                    'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://reactivex.io/',                                              'wikipedia' => 'https://en.wikipedia.org/wiki/ReactiveX',                        'definition' => 'A software library that allows imperative programming languages to operate on sequences of data regardless of whether the data is synchronous or asynchronous.' ],
            [ 'id' => 22,  'name' => 'Reason Testing Library',       'full_name' => 'Reason Testing Library',       'slug' => 'reason-testing-library',       'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://testing-library.com/docs/bs-react-testing-library/intro/',   'wikipedia' => null,                                                             'definition' => 'Refers to bindings for the Reason programming language to use the Testing Library framework.' ],
            [ 'id' => 23,  'name' => 'ReasonReact',                  'full_name' => 'ReasonReact',                  'slug' => 'reasonreact',                  'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://reasonml.github.io/reason-react/',                           'wikipedia' => null,                                                             'definition' => 'A collection of zero-runtime type definitions and lightweight utilities for React.' ],
            [ 'id' => 24,  'name' => 'Redux',                        'full_name' => 'Redux',                        'slug' => 'redux',                        'abbreviation' => null, 'open_source' => 1, 'proprietary' => 0, 'owner' => null,        'link' => 'https://redux.js.org/',                                              'wikipedia' => 'https://en.wikipedia.org/wiki/Redux_(JavaScript_library)',       'definition' => 'An open-source JavaScript library for managing and centralizing application state.' ],
            [ 'id' => 25,  'name' => 'RxJava',                       'full_name' => 'RxJava',                       'slug' => 'rxjava',                       'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://github.com/ReactiveX/RxJava',                                'wikipedia' => null,                                                             'definition' => 'A library for composing asynchronous and event-based programs using observable sequences for the Java VM.' ],
            [ 'id' => 26,  'name' => 'SciPy',                        'full_name' => 'SciPy',                        'slug' => 'scipy',                        'abbreviation' => null, 'open_source' => 1, 'proprietary' => 0, 'owner' => null,        'link' => 'https://scipy.org/',                                                 'wikipedia' => 'https://en.wikipedia.org/wiki/SciPy',                            'definition' => 'A free and open-source Python library used for scientific computing and technical computing.' ],
            [ 'id' => 27,  'name' => 'Stencil',                      'full_name' => 'Stencil',                      'slug' => 'stencil',                      'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://stenciljs.com/',                                             'wikipedia' => null,                                                             'definition' => 'A library for building reusable, scalable component libraries to generate Web Components.' ],
            [ 'id' => 28,  'name' => 'Svelte Testing Library',       'full_name' => 'Svelte Testing Library',       'slug' => 'svelte-testing-library',       'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://testing-library.com/docs/svelte-testing-library/intro/',     'wikipedia' => null,                                                             'definition' => 'A very lightweight solution for testing Svelte components.' ],
            [ 'id' => 29,  'name' => 'TensorFlow',                   'full_name' => 'TensorFlow',                   'slug' => 'tensorflow',                   'abbreviation' => null, 'open_source' => 1, 'proprietary' => 0, 'owner' => null,        'link' => 'https://www.tensorflow.org/',                                        'wikipedia' => 'https://en.wikipedia.org/wiki/TensorFlow',                       'definition' => 'A software library for machine learning and artificial intelligence.' ],
            [ 'id' => 30,  'name' => 'ThreeJS',                      'full_name' => 'ThreeJS',                      'slug' => 'threejs',                      'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://threejs.org/',                                               'wikipedia' => 'https://en.wikipedia.org/wiki/Three.js',                         'definition' => 'A cross-browser JavaScript library and application programming interface (API) used to create and display animated 3D computer graphics in a web browser using WebGL.' ],
            [ 'id' => 31,  'name' => 'Vue Testing Library',          'full_name' => 'Vue Testing Library',          'slug' => 'vue-testing-library',          'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://testing-library.com/docs/vue-testing-library/intro/',        'wikipedia' => null,                                                             'definition' => 'Builds on top of DOM Testing Library by adding APIs for working with Vue components.' ],
            [ 'id' => 32,  'name' => 'Web Graphics Library',         'full_name' => 'Web Graphics Library',         'slug' => 'web-graphics-library',         'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://get.webgl.org/',                                             'wikipedia' => 'https://en.wikipedia.org/wiki/WebGL',                            'definition' => 'A JavaScript API for rendering interactive 2D and 3D graphics within any compatible web browser without the use of plug-ins.' ],
            [ 'id' => 33,  'name' => 'Xamarin',                      'full_name' => 'Xamarin',                      'slug' => 'xamarin',                      'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => null,                                                                 'wikipedia' => 'https://en.wikipedia.org/wiki/Xamarin',                          'definition' => 'A library to build cross-platform native mobile apps for iOS, Android, and Windows using a single C#/.NET codebase.' ],
            [ 'id' => 34,  'name' => 'Xstate',                       'full_name' => 'Xstate',                       'slug' => 'xstate',                       'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => 'https://xstate.js.org/',                                             'wikipedia' => null,                                                             'definition' => 'A state management and orchestration solution for JavaScript and TypeScript apps.' ],
            [ 'id' => 35,  'name' => 'other',                        'full_name' => 'other',                        'slug' => 'other',                        'abbreviation' => null, 'open_source' => 0, 'proprietary' => 0, 'owner' => null,        'link' => null,                                                                 'wikipedia' => null,                                                             'definition' => '' ],
        ];

        // add timestamps
        for($i=0; $i<count($data);$i++) {
            $data[$i]['created_at'] = now();
            $data[$i]['updated_at'] = now();
        }

        Library::insert($data);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::connection($this->database_tag)->dropIfExists('libraries');
    }
};
