<?php

use App\Models\Portfolio\Course;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * The tag used to identify the portfolio database.
     *
     * @var string
     */
    protected $database_tag = 'portfolio_db';

    /**
     * The id of the admin who owns the portfolio course resource.
     *
     * @var int
     */
    protected $ownerId = 2;

    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::connection($this->database_tag)->create('courses', function (Blueprint $table) {
            $table->id();
            $table->foreignIdFor(\App\Models\Owner::class, 'owner_id');
            $table->string('name');
            $table->string('slug');
            $table->tinyInteger('featured')->default(0);
            $table->string('summary')->nullable();
            $table->year('year')->nullable()->default(null);
            $table->tinyInteger('completed')->default(0);
            $table->date('completion_date')->nullable();
            $table->float('duration_hours')->nullable();
            $table->foreignIdFor( \App\Models\Portfolio\Academy::class)->nullable()->default(null);
            $table->string('school')->nullable()->default(null);
            $table->string('instructor')->nullable()->default(null);
            $table->string('sponsor')->nullable()->default(null);
            $table->string('certificate_url', 500)->nullable();
            $table->text('notes')->nullable();
            $table->string('link', 500)->nullable();
            $table->string('link_name')->nullable();
            $table->text('description')->nullable();
            $table->string('image', 500)->nullable();
            $table->string('image_credit')->nullable();
            $table->string('image_source')->nullable();
            $table->string('thumbnail', 500)->nullable();
            $table->integer('sequence')->default(0);
            $table->tinyInteger('public')->default(1);
            $table->tinyInteger('readonly')->default(0);
            $table->tinyInteger('root')->default(0);
            $table->tinyInteger('disabled')->default(0);
            $table->timestamps();
            $table->softDeletes();

            $table->unique(['owner_id', 'name'], 'owner_id_name_unique');
            $table->unique(['owner_id', 'slug'], 'owner_id_slug_unique');
        });

        $data = [
            [
                'id'              => 1,
                'name'            => 'AWS Cloud Practitioner Essentials: Cloud Concepts',
                'slug'            => 'aws-cloud-practitioner-essentials-cloud-concepts',
                'completed'       => 1,
                'completion_date' => '2019-04-25',
                'year'            => 2019,
                'duration_hours'  => 0.5,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20AWS%20Cloud%20Practitioner%20Essentials%20-%20Cloud%20Concepts.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 2,
                'name'            => 'AWS Cloud Practitioner Essentials: Core Services',
                'slug'            => 'aws-cloud-practitioner-eEssentials-core-services',
                'completed'       => 1,
                'completion_date' => '2019-05-01',
                'year'            => 2019,
                'duration_hours'  => 3.0,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20AWS%20Cloud%20Practitioner%20Essentials%20-%20Core%20Services.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 3,
                'name'            => 'AWS Cloud Practitioner Essentials: Course Introduction',
                'slug'            => 'aws-cloud-practitioner-essentials-course-introduction',
                'completed'       => 1,
                'completion_date' => '2019-04-25',
                'year'            => 2019,
                'duration_hours'  => 0.08333,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20AWS%20Cloud%20Practitioner%20Essentials%20-%20Course%20Introduction.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 4,
                'name'            => 'AWS Compute Services Overview',
                'slug'            => 'aws-compute-services-overview',
                'completed'       => 1,
                'completion_date' => '2019-05-14',
                'year'            => 2019,
                'duration_hours'  => 0.08333,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20AWS%20Compute%20Services%20Overview.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 5,
                'name'            => 'AWS Database Services Overview',
                'slug'            => 'aws-database-services-overview',
                'completed'       => 1,
                'completion_date' => '2019-05-08',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20AWS%20Database%20Services%20Overview.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 6,
                'name'            => 'AWS Shared Responsibility Model',
                'slug'            => 'aws-shared-responsibility-model',
                'completed'       => 1,
                'completion_date' => '2019-06-12',
                'year'            => 2019,
                'duration_hours'  => 0.08333,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20AWS%20Shared%20Responsibility%20Model.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 7,
                'name'            => 'Introduction to AWS Auto Scaling',
                'slug'            => 'introduction-to-aws-auto-scaling',
                'completed'       => 1,
                'completion_date' => '2019-05-06',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20AWS%20Auto%20Scaling.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 8,
                'name'            => 'Introduction to AWS Backup',
                'slug'            => 'introduction-to-aws-backup',
                'completed'       => 1,
                'completion_date' => '2019-05-13',
                'year'            => 2019,
                'duration_hours'  => 0.33333,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20AWS%20Backup.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 9,
                'name'            => 'Introduction to AWS Device Farm',
                'slug'            => 'introduction-to-aws-device-farm',
                'completed'       => 1,
                'completion_date' => '2019-06-12',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20AWS%20Device%20Farm.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 10,
                'name'            => 'Introduction to AWS Fargate',
                'slug'            => 'introduction-to-aws-fargate',
                'completed'       => 1,
                'completion_date' => '2019-05-14',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20AWS%20Fargate.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 11,
                'name'            => 'Introduction to AWS Import/Export',
                'slug'            => 'introduction-to-aws-import-export',
                'completed'       => 1,
                'completion_date' => '2019-05-13',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20AWS%20Import-Export.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 12,
                'name'            => 'Introduction to AWS Snowball',
                'slug'            => 'introduction-to-aws-snowball',
                'completed'       => 1,
                'completion_date' => '2019-05-13',
                'year'            => 2019,
                'duration_hours'  => 0.08333,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20AWS%20Snowball.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 13,
                'name'            => 'Introduction to AWS Snowballmobile',
                'slug'            => 'introduction-to-aws-snowballmobile',
                'completed'       => 1,
                'completion_date' => '2019-05-13',
                'year'            => 2019,
                'duration_hours'  => 0.08333,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20AWS%20Snowmobile.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 14,
                'name'            => 'Introduction to AWS Storage Gateway',
                'slug'            => 'introduction-to-aws-storage-gateway',
                'completed'       => 1,
                'completion_date' => '2019-05-13',
                'year'            => 2019,
                'duration_hours'  => 0.08333,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20AWS%20Storage%20Gateway.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 15,
                'name'            => 'Introduction to Amazon Aurora',
                'slug'            => 'introduction-to-amazon-aurora',
                'completed'       => 1,
                'completion_date' => '2019-05-09',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20Amazon%20Aurora.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 16,
                'name'            => 'Introduction the EC2 Systems Manager',
                'slug'            => 'introduction-the-ec2-systems-manager',
                'completed'       => 1,
                'completion_date' => '2019-07-14',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20Amazon%20EC2%20Systems%20Manager.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 17,
                'name'            => 'Introduction to ElastiCache',
                'slug'            => 'introduction-to-elasticache',
                'completed'       => 1,
                'completion_date' => '2019-5-10',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20Amazon%20ElastiCache.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 18,
                'name'            => 'Introduction to Amazon Elastic Block Store (EBS)',
                'slug'            => 'introduction-to-amazon-elastic-block-store-(ebs)',
                'completed'       => 1,
                'completion_date' => '2019-05-10',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20Amazon%20Elastic%20Block%20Storage%20-%20EBS.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 19,
                'name'            => 'Introduction to Amazon Elastic Compute Cloud (EC2)',
                'slug'            => 'introduction-to-amazon-elastic-compute-cloud-(ec2)',
                'completed'       => 1,
                'completion_date' => '2019-05-06',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20Amazon%20Elastic%20Compute%20Cloud%20-%20EC2.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 20,
                'name'            => 'Introduction to Amazon Elastic File System (EFS)',
                'slug'            => 'introduction-to-amazon-elastic-file-system-(efs)',
                'completed'       => 1,
                'completion_date' => '2019-05-10',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20Amazon%20Elastic%20File%20System%20-%20EFS.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 21,
                'name'            => 'Introduction to Amazon Elastic Load Balancer - Classic',
                'slug'            => 'introduction-to-amazon-elastic-load-balancer-classic',
                'completed'       => 1,
                'completion_date' => '2019-06-12',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20Amazon%20Elastic%20Load%20Balancer%20-%20Classic.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 22,
                'name'            => 'Introduction to Amazon FSx for Lustre',
                'slug'            => 'introduction-to-amazon-fsx-for-lustre',
                'completed'       => 1,
                'completion_date' => '2019-05-13',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20Amazon%20FSx%20for%20Lustre.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 23,
                'name'            => 'Introduction to Amazon FSx for Windows File Server',
                'slug'            => 'introduction-to-amazon-fsx-for-windows-file-server',
                'completed'       => 1,
                'completion_date' => '2019-05-10',
                'year'            => 2019,
                'duration_hours'  => 0.33333,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20Amazon%20FSx%20for%20Windows%20File%20Server.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 24,
                'name'            => 'Introduction to Amazon Glacier',
                'slug'            => 'introduction-to-amazon-glacier',
                'completed'       => 1,
                'completion_date' => '2019-05-13',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20Amazon%20Glacier.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 25,
                'name'            => 'Introduction to Amazon Redshift',
                'slug'            => 'introduction-to-amazon-redshift',
                'completed'       => 1,
                'completion_date' => '2019-5-10',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20Amazon%20Redshift.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 26,
                'name'            => 'Introduction to Amazon Relational Database Service (RDS)',
                'slug'            => 'introduction-to-amazon-relational-database-service-(rds)',
                'completed'       => 1,
                'completion_date' => '2019-05-08',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20Amazon%20Relational%20Database%20Service%20-%20RDS.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 27,
                'name'            => 'Introduction to Amazon S3',
                'slug'            => 'introduction-to-amazon-s3',
                'completed'       => 1,
                'completion_date' => '2019-05-06',
                'year'            => 2019,
                'duration_hours'  => 0.25,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20Amazon%20S3.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 28,
                'name'            => 'Introduction to Amazon Simple Storage Service (S3)',
                'slug'            => 'introduction-to-amazon-simple-storage-service-(s3)',
                'completed'       => 1,
                'completion_date' => '2019-05-10',
                'year'            => 2019,
                'duration_hours'  => 0.16667,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20Introduction%20to%20Amazon%20Simple%20Storage%20Service%20-%20S3.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 29,
                'name'            => 'PostgreSQL Fundamentals',
                'slug'            => 'postgresql-fundamentals',
                'completed'       => 1,
                'completion_date' => '2019-05-08',
                'year'            => 2019,
                'duration_hours'  => 0.33333,
                'academy_id'      => 9,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'https://raw.githubusercontent.com/craigzearfoss/certificates/refs/heads/master/AWS%20-%20PostgreSQL%20Fundamentals.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 30,
                'name'            => 'Foundations of Cybersecurity',
                'slug'            => 'foundations-of-cybersecurity',
                'completed'       => 1,
                'completion_date' => '2023-06-14',
                'year'            => 2023,
                'duration_hours'  => 10,
                'academy_id'      => 2,
                'instructor'      => '',
                'sponsor'         => 'Google',
                'certificate_url' => 'images/admin/portfolio/2/course/RS62SKVP89SG.png',
                'link'            => 'https://www.coursera.org/account/accomplishments/verify/RS62SKVP89SG',
                'link_name'       => 'Coursera verification',
            ],
            [
                'id'              => 31,
                'name'            => 'Play It Safer: Manage Security Risks',
                'slug'            => 'play-it-safer-manage-security-risks',
                'completed'       => 1,
                'completion_date' => '2023-06-17',
                'year'            => 2023,
                'duration_hours'  => 9,
                'academy_id'      => 2,
                'instructor'      => '',
                'sponsor'         => 'Google',
                'certificate_url' => 'images/admin/portfolio/2/course/52BCA2UWTHPE.png',
                'link'            => 'https://www.coursera.org/account/accomplishments/verify/52BCA2UWTHPE',
                'link_name'       => 'Coursera verification',
            ],
            [
                'id'              => 32,
                'name'            => 'Connect and Protect: Networks and Network Security',
                'slug'            => 'connect-and-protect-networks-and-network-security',
                'completed'       => 1,
                'completion_date' => '2023-06-25',
                'year'            => 2023,
                'duration_hours'  => 11,
                'academy_id'      => 2,
                'instructor'      => '',
                'sponsor'         => 'Google',
                'certificate_url' => 'images/admin/portfolio/2/course/MUUFRJW2JK7G.png',
                'link'            => 'https://www.coursera.org/account/accomplishments/verify/MUUFRJW2JK7G',
                'link_name'       => 'Coursera verification',
            ],
            [
                'id'              => 33,
                'name'            => 'Tools of the Trade: Linux and SQL',
                'slug'            => 'tools-of-the-Trade-linux-and-sql',
                'completed'       => 1,
                'completion_date' => '2023-06-29',
                'year'            => 2023,
                'duration_hours'  => 23,
                'academy_id'      => 2,
                'instructor'      => '',
                'sponsor'         => 'Google',
                'certificate_url' => 'images/admin/portfolio/2/course/KFJC8C2ZLQPU.png',
                'link'            => 'https://www.coursera.org/account/accomplishments/verify/KFJC8C2ZLQPU',
                'link_name'       => 'Coursera verification',
            ],
            [
                'id'              => 34,
                'name'            => 'Assets, Threats, and Vulnerabilities',
                'slug'            => 'assets-threats-and-vulnerabilities',
                'completed'       => 1,
                'completion_date' => '2023-07-03',
                'year'            => 2023,
                'duration_hours'  => 19,
                'academy_id'      => 2,
                'instructor'      => '',
                'sponsor'         => 'Google',
                'certificate_url' => 'images/admin/portfolio/2/course/DWKGKVVLFE9F.png',
                'link'            => 'https://www.coursera.org/account/accomplishments/verify/DWKGKVVLFE9F',
                'link_name'       => 'Coursera verification',
            ],
            [
                'id'              => 35,
                'name'            => 'Sound the Alarm: Detection and Response',
                'slug'            => 'sound-the-alarm-detection-and-response',
                'completed'       => 1,
                'completion_date' => '2023-07-06',
                'year'            => 2023,
                'duration_hours'  => 18,
                'academy_id'      => 2,
                'instructor'      => '',
                'sponsor'         => 'Google',
                'certificate_url' => 'images/admin/portfolio/2/course/LK8958ER9X7D.png',
                'link'            => 'https://www.coursera.org/account/accomplishments/verify/LK8958ER9X7D',
                'link_name'       => 'Coursera verification',
            ],
            [
                'id'              => 36,
                'name'            => 'Automate Cybersecurity Tasks with Python',
                'slug'            => 'automate-cybersecurity-tasks-with-python',
                'completed'       => 1,
                'completion_date' => '2023-07-09',
                'year'            => 2023,
                'duration_hours'  => null,
                'academy_id'      => 2,
                'instructor'      => '',
                'sponsor'         => 'Google',
                'certificate_url' => 'images/admin/portfolio/2/course/64K4C9WZSJQ.png',
                'link'            => 'https://www.coursera.org/account/accomplishments/verify/64K4C9WZSJQ',
                'link_name'       => 'Coursera verification',
            ],
            [
                'id'              => 37,
                'name'            => 'JavaScript Foundations',
                'slug'            => 'javascript-foundations',
                'completed'       => 1,
                'completion_date' => '2015-09-22',
                'year'            => 2015,
                'duration_hours'  => null,
                'academy_id'      => 3,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'images/admin/portfolio/2/course/javascript-foundations.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 38,
                'name'            => 'Responsive Web Design',
                'slug'            => 'responsive-web-design',
                'completed'       => 1,
                'completion_date' => '2015-09-17',
                'year'            => 2015,
                'duration_hours'  => null,
                'academy_id'      => 3,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'images/admin/portfolio/2/course/responsive-web-design.png',
                'link'            => null,
                'link_name'       => null,
            ],
            [
                'id'              => 39,
                'name'            => 'University M042: New Features and Tools in MongoDB 4.2',
                'slug'            => 'university-m042-new-features-and-tools-in-mongodb-4-2',
                'completed'       => 1,
                'completion_date' => '2019-06-18',
                'year'            => 2019,
                'duration_hours'  => 0,
                'academy_id'      => 5,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'images/admin/portfolio/2/course/MDBz9qkj8zq9r.pdf',
                'link'            => 'https://ti-user-certificates.s3.amazonaws.com/ae62dcd7-abdc-4e90-a570-83eccba49043/63744623-417f-5e55-8d5c-c09650679c4d-craig-zearfoss-ddc8ff8d-66fe-5f98-9677-854db66c6cf9-certificate.pdf',
                'link_name'       => 'MongoDB certificate link',
            ],
            [
                'id'              => 40,
                'name'            => 'M310: MongoDB Security',
                'slug'            => 'm310-mongodb-security',
                'completed'       => 1,
                'completion_date' => '2019-06-03',
                'year'            => 2019,
                'duration_hours'  => 0,
                'academy_id'      => 5,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'images/admin/portfolio/2/course/MDBh4n25xp9f3.pdf',
                'link'            => 'https://ti-user-certificates.s3.amazonaws.com/ae62dcd7-abdc-4e90-a570-83eccba49043/63744623-417f-5e55-8d5c-c09650679c4d-craig-zearfoss-cb169d9d-f28b-5cfc-98ae-6849d44e9e45-certificate.pdf',
                'link_name'       => 'MongoDB certificate link',
            ],

            [
                'id'              => 41,
                'name'            => 'M312: Diagnostics and Debugging',
                'slug'            => 'm312-diagnostics-and-debugging',
                'completed'       => 1,
                'completion_date' => '2019-06-03',
                'year'            => 2019,
                'duration_hours'  => 0,
                'academy_id'      => 5,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'images/admin/portfolio/2/course/MDB4llntcxgsw.pdf',
                'link'            => 'https://ti-user-certificates.s3.amazonaws.com/ae62dcd7-abdc-4e90-a570-83eccba49043/63744623-417f-5e55-8d5c-c09650679c4d-craig-zearfoss-28e6dfda-043f-5c82-a2ad-ff1aa0b4091f-certificate.pdf',
                'link_name'       => 'MongoDB certificate link',
            ],
            [
                'id'              => 42,
                'name'            => 'M201: MongoDB Performance',
                'slug'            => 'm201-mongodb-performance',
                'completed'       => 1,
                'completion_date' => '2019-04-24',
                'year'            => 2019,
                'duration_hours'  => 0,
                'academy_id'      => 5,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'images/admin/portfolio/2/course/MDB5u800z5l3u.pdf',
                'link'            => 'https://ti-user-certificates.s3.amazonaws.com/ae62dcd7-abdc-4e90-a570-83eccba49043/63744623-417f-5e55-8d5c-c09650679c4d-craig-zearfoss-f04e21f1-2b5f-588f-a921-14605013fb42-certificate.pdf',
                'link_name'       => 'MongoDB certificate link',
            ],
            [
                'id'              => 43,
                'name'            => 'M121: The MongoDB Aggregation Framework',
                'slug'            => 'm121-the-mongodb-aggregation-framework',
                'completed'       => 1,
                'completion_date' => '2019-04-21',
                'year'            => 2019,
                'duration_hours'  => 0,
                'academy_id'      => 5,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'images/admin/portfolio/2/course/MDBz9qkj8zq9r.pdf',
                'link'            => 'https://ti-user-certificates.s3.amazonaws.com/ae62dcd7-abdc-4e90-a570-83eccba49043/63744623-417f-5e55-8d5c-c09650679c4d-craig-zearfoss-ddc8ff8d-66fe-5f98-9677-854db66c6cf9-certificate.pdf',
                'link_name'       => 'MongoDB certificate link',
            ],
            [
                'id'              => 44,
                'name'            => 'M220JS: MongoDB for JavaScript Developers',
                'slug'            => 'm220js-mongodb-for-javaScript-developers',
                'completed'       => 1,
                'completion_date' => '2019-03-30',
                'year'            => 2019,
                'duration_hours'  => 0,
                'academy_id'      => 5,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'images/admin/portfolio/2/course/MDBvcjb83odqk.pdf',
                'link'            => 'https://ti-user-certificates.s3.amazonaws.com/ae62dcd7-abdc-4e90-a570-83eccba49043/63744623-417f-5e55-8d5c-c09650679c4d-craig-zearfoss-5fc17da8-4f83-5c1d-9e13-18c046833329-certificate.pdf',
                'link_name'       => 'MongoDB certificate link',
            ],
            [
                'id'              => 45,
                'name'            => 'M103: Basic Cluster Administration',
                'slug'            => 'm103-basic-cluster-administration',
                'completed'       => 1,
                'completion_date' => '2019-03-12',
                'year'            => 2019,
                'duration_hours'  => 0,
                'academy_id'      => 5,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'images/admin/portfolio/2/course/MDBzmzrrpzzin.pdf',
                'link'            => 'https://ti-user-certificates.s3.amazonaws.com/ae62dcd7-abdc-4e90-a570-83eccba49043/63744623-417f-5e55-8d5c-c09650679c4d-craig-zearfoss-b3ac9b75-0c7b-51ea-8cd0-b250bf0a2bcc-certificate.pdf',
                'link_name'       => 'MongoDB certificate link',
            ],
            [
                'id'              => 46,
                'name'            => 'M001: MongoDB Basics ',
                'slug'            => 'm001-mongodb-basics',
                'completed'       => 1,
                'completion_date' => '2019-03-12',
                'year'            => 2019,
                'duration_hours'  => 0,
                'academy_id'      => 5,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => 'images/admin/portfolio/2/course/MDB0elknbkm6j.pdf',
                'link'            => 'learn.mongodb.com/learn/certificates/university-m001-mongob-basics?userId=63744623-417f-5e55-8d5c-c09650679c4d&id=2dc804a7-34d3-5ed1-b3de-750819bdb3c4',
                'link_name'       => 'MongoDB certificate link',
            ],


            /*
            [
                'id'              => 1,
                'name'            => '',
                'slug'            => '',
                'completed'       => 1,
                'completion_date' => '',
                'year'            => 2000,
                'duration_hours'  => 0,
                'academy_id'      => 2,
                'instructor'      => '',
                'sponsor'         => '',
                'certificate_url' => '',
                'link'            => null,
                'link_name'       => null,
            ],
            */
        ];

        // add timestamps and owner_ids
        for($i=0; $i<count($data);$i++) {
            $data[$i]['owner_id']   = $this->ownerId;
            $data[$i]['created_at'] = now();
            $data[$i]['updated_at'] = now();
        }

        Course::insert($data);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::connection($this->database_tag)->dropIfExists('courses');
    }
};
