<?php

use \App\Models\Database;
use \App\Models\Resource;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $data = [
            [
                //'id'       => 3,
                'name'     => 'portfolio',  //config('app.db_portfolio'), //TODO: using config method brings back null?
                'database' => 'portfolio',  //config('app.db_portfolio'), //TODO: using config method brings back null?
                'tag'      => 'portfolio_db',
                'title'    => 'Portfolio',
                'plural'   => 'Portfolios',
                'icon'     => 'fa-folder',
                'guest'    => 1,
                'user'     => 1,
                'admin'    => 1,
                'sequence' => 3000,
                'public'   => 1,
                'disabled' => 0,
                'admin_id' => 1,
            ],
        ];

        Database::insert($data);

        if (!$row = Database::where('database', '=', 'portfolio')->first()) {

            throw new \Exception('portfolio database not found.');

        } else {

            $databaseId = $row->id;

            $data = [
                [
                    'database_id' => $databaseId,
                    'name'        => 'academy',
                    'table'       => 'academies',
                    'title'       => 'Academy',
                    'plural'      => 'Academies',
                    'guest'       => 0,
                    'user'        => 0,
                    'admin'       => 1,
                    'icon'        => 'fa-school',
                    'sequence'    => 3010,
                    'public'      => 0,
                    'readonly'    => 0,
                    'root'        => 1,
                    'disabled'    => 0,
                    'admin_id'    => 1,
                ],
                [
                    'database_id' => $databaseId,
                    'name'        => 'art',
                    'table'       => 'art',
                    'title'       => 'Art',
                    'plural'      => 'Art',
                    'guest'       => 1,
                    'user'        => 0,
                    'admin'       => 1,
                    'icon'        => 'fa-image',
                    'sequence'    => 3020,
                    'public'      => 1,
                    'readonly'    => 0,
                    'root'        => 1,
                    'disabled'    => 0,
                    'admin_id'    => 1,
                ],
                [
                    'database_id' => $databaseId,
                    'name'        => 'certification',
                    'table'       => 'certifications',
                    'title'       => 'Certification',
                    'plural'      => 'Certifications',
                    'guest'       => 1,
                    'user'        => 0,
                    'admin'       => 1,
                    'icon'        => 'fa-graduation-cap',
                    'sequence'    => 3030,
                    'public'      => 1,
                    'readonly'    => 0,
                    'root'        => 1,
                    'disabled'    => 0,
                    'admin_id'    => 1,
                ],
                [
                    'database_id' => $databaseId,
                    'name'        => 'course',
                    'table'       => 'courses',
                    'title'       => 'Course',
                    'plural'      => 'Courses',
                    'guest'       => 1,
                    'user'        => 0,
                    'admin'       => 1,
                    'icon'        => 'fa-chalkboard',
                    'sequence'    => 3040,
                    'public'      => 1,
                    'readonly'    => 0,
                    'root'        => 1,
                    'disabled'    => 0,
                    'admin_id'    => 1,
                ],
                [
                    'database_id' => $databaseId,
                    'name'        => 'ingredient',
                    'table'       => 'ingredients',
                    'title'       => 'Ingredient',
                    'plural'      => 'Ingredients',
                    'guest'       => 1,
                    'user'        => 0,
                    'admin'       => 1,
                    'icon'        => 'fa-pizza-slice',
                    'sequence'    => 3050,
                    'public'      => 0,
                    'readonly'    => 0,
                    'root'        => 1,
                    'disabled'    => 0,
                    'admin_id'    => 1,
                ],
                [
                    'database_id' => $databaseId,
                    'name'        => 'job',
                    'table'       => 'jobs',
                    'title'       => 'Job',
                    'plural'      => 'Jobs',
                    'guest'       => 0,
                    'user'        => 0,
                    'admin'       => 1,
                    'icon'        => 'fa-briefcase',
                    'sequence'    => 3060,
                    'public'      => 0,
                    'readonly'    => 0,
                    'root'        => 1,
                    'disabled'    => 0,
                    'admin_id'    => 1,
                ],
                [
                    'database_id' => $databaseId,
                    'name'        => 'job-coworker',
                    'table'       => 'job_coworkers',
                    'title'       => 'Job Coworker',
                    'plural'      => 'Job Coworkers',
                    'guest'       => 0,
                    'user'        => 0,
                    'admin'       => 1,
                    'icon'        => 'fa-users',
                    'sequence'    => 3070,
                    'public'      => 0,
                    'readonly'    => 0,
                    'root'        => 1,
                    'disabled'    => 0,
                    'admin_id'    => 1,
                ],
                [
                    'database_id' => $databaseId,
                    'name'        => 'job-task',
                    'table'       => 'job_tasks',
                    'title'       => 'Job Task',
                    'plural'      => 'Job Tasks',
                    'guest'       => 0,
                    'user'        => 0,
                    'admin'       => 1,
                    'icon'        => 'fa-cogs',
                    'sequence'    => 3080,
                    'public'      => 0,
                    'readonly'    => 0,
                    'root'        => 1,
                    'disabled'    => 0,
                    'admin_id'    => 1,
                ],
                [
                    'database_id' => $databaseId,
                    'name'        => 'link',
                    'table'       => 'links',
                    'title'       => 'Link',
                    'plural'      => 'Links',
                    'guest'       => 1,
                    'user'        => 0,
                    'admin'       => 1,
                    'icon'        => 'fa-link',
                    'sequence'    => 3090,
                    'public'      => 1,
                    'readonly'    => 0,
                    'root'        => 1,
                    'disabled'    => 0,
                    'admin_id'    => 1,
                ],
                [
                    'database_id' => $databaseId,
                    'name'        => 'music',
                    'table'       => 'music',
                    'title'       => 'Music',
                    'plural'      => 'Music',
                    'guest'       => 1,
                    'user'        => 0,
                    'admin'       => 1,
                    'icon'        => 'fa-music',
                    'sequence'    => 3100,
                    'public'      => 1,
                    'readonly'    => 0,
                    'root'        => 1,
                    'disabled'    => 0,
                    'admin_id'    => 1,
                ],
                [
                    'database_id' => $databaseId,
                    'name'        => 'project',
                    'table'       => 'projects',
                    'title'       => 'Project',
                    'plural'      => 'Projects',
                    'guest'       => 1,
                    'user'        => 0,
                    'admin'       => 1,
                    'icon'        => 'fa-wrench',
                    'sequence'    => 3110,
                    'public'      => 1,
                    'readonly'    => 0,
                    'root'        => 1,
                    'disabled'    => 0,
                    'admin_id'    => 1,
                ],
                [
                    'database_id' => $databaseId,
                    'name'        => 'reading',
                    'table'       => 'readings',
                    'title'       => 'Reading',
                    'plural'      => 'Readings',
                    'guest'       => 1,
                    'user'        => 0,
                    'admin'       => 1,
                    'icon'        => 'fa-book',
                    'sequence'    => 3120,
                    'public'      => 1,
                    'readonly'    => 0,
                    'root'        => 1,
                    'disabled'    => 0,
                    'admin_id'    => 1,
                ],
                [
                    'database_id' => $databaseId,
                    'name'        => 'recipe',
                    'table'       => 'recipes',
                    'title'       => 'Recipe',
                    'plural'      => 'Recipes',
                    'guest'       => 1,
                    'user'        => 0,
                    'admin'       => 1,
                    'icon'        => 'fa-cutlery',
                    'sequence'    => 3130,
                    'public'      => 1,
                    'readonly'    => 0,
                    'root'        => 1,
                    'disabled'    => 0,
                    'admin_id'    => 1,
                ],
                [
                    'database_id' => $databaseId,
                    'name'        => 'unit',
                    'table'       => 'units',
                    'title'       => 'Unit',
                    'plural'      => 'Units',
                    'guest'       => 0,
                    'user'        => 0,
                    'admin'       => 1,
                    'icon'        => 'fa-video-camera',
                    'sequence'    => 3140,
                    'public'      => 0,
                    'readonly'    => 0,
                    'root'        => 1,
                    'disabled'    => 0,
                    'admin_id'    => 1,
                ],
                [
                    'database_id' => $databaseId,
                    'name'        => 'video',
                    'table'       => 'videos',
                    'title'       => 'Video',
                    'plural'      => 'Videos',
                    'guest'       => 1,
                    'user'        => 0,
                    'admin'       => 1,
                    'icon'        => 'fa-video-camera',
                    'sequence'    => 3150,
                    'public'      => 1,
                    'readonly'    => 0,
                    'root'        => 1,
                    'disabled'    => 0,
                    'admin_id'    => 1,
                ],
            ];

            Resource::insert($data);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::connection('dictionary_db')->dropIfExists('dictionary_sections');
    }
};
