<?php

use App\Models\Dictionary\Framework;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    protected $database_tag = 'dictionary_db';

    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::connection($this->database_tag)->create('frameworks', function (Blueprint $table) {
            $table->id();
            $table->string('full_name')->unique();
            $table->string('name', 100)->unique();
            $table->string('slug', 100)->unique();
            $table->string('abbreviation', 20)->nullable();
            $table->string('definition')->nullable();
            $table->tinyInteger('open_source')->default(0);
            $table->tinyInteger('proprietary')->default(0);
            $table->tinyInteger('compiled')->default(0);
            $table->string('owner', 100)->nullable();
            $table->string('wikipedia')->nullable();
            $table->string('link')->nullable();
            $table->string('link_name')->nullable();
            $table->text('description')->nullable();
            $table->string('image')->nullable();
            $table->string('image_credit')->nullable();
            $table->string('image_source')->nullable();
            $table->string('thumbnail')->nullable();
            $table->integer('sequence')->default(0);
            $table->tinyInteger('public')->default(1);
            $table->tinyInteger('readonly')->default(0);
            $table->tinyInteger('root')->default(0);
            $table->tinyInteger('disabled')->default(0);
            $table->timestamps();
            $table->softDeletes();
        });

        $data = [
            [ 'id' => 1,   'full_name' => 'Angular',                            'name' => 'Angular',                  'slug' => 'angular',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://angular.dev/',                                                        'wikipedia' => 'https://en.wikipedia.org/wiki/Angular_(web_framework)',         'definition' => 'A TypeScript-based free and open-source single-page web application framework developed by Google.' ],
            [ 'id' => 2,   'full_name' => 'ASP.NET',                            'name' => 'ASP.NET',                  'slug' => 'asp-net',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => 'Microsoft',  'link' => 'https://dotnet.microsoft.com/en-us/apps/aspnet',                              'wikipedia' => 'https://en.wikipedia.org/wiki/ASP.NET',                         'definition' => 'A server-side web-application framework designed for web development to produce dynamic web pages.' ],
            [ 'id' => 3,   'full_name' => 'AWS Identity and Access Management', 'name' => 'AWS IAM',                  'slug' => 'aws-iam',                   'abbreviation' => 'AWS IAM', 'open_source' => 0, 'proprietary' => 0, 'owner' => 'Amazon',     'link' => 'https://aws.amazon.com/iam/',                                                 'wikipedia' =>  null,                                                           'definition' => 'A web service that helps you securely control access to AWS resources.' ],
            [ 'id' => 4,   'full_name' => 'Backbone.js',                        'name' => 'Backbone.js',              'slug' => 'backbone-js',               'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://backbonejs.org/',                                                     'wikipedia' => 'https://en.wikipedia.org/wiki/Backbone.js',                     'definition' => 'A JavaScript rich-client web app framework based on the model–view–controller design paradigm, intended to connect to an API over a RESTful JSON interface.' ],
            [ 'id' => 5,   'full_name' => 'Bootstrap',                          'name' => 'Bootstrap',                'slug' => 'bootstrap',                 'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://getbootstrap.com/docs/5.0/getting-started/introduction/',             'wikipedia' => 'https://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)', 'definition' => 'A free and open-source CSS framework directed at responsive, mobile-first front-end web development. (formerly <strong>Twitter Bootstrap</strong>)' ],
            [ 'id' => 6,   'full_name' => 'CakePHP',                            'name' => 'CakePHP',                  'slug' => 'cakephp',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://cakephp.org/',                                                        'wikipedia' => 'https://en.wikipedia.org/wiki/CakePHP',                         'definition' => 'An open-source web framework written in PHP that follows the model–view–controller (MVC) approach.' ],
            [ 'id' => 7,   'full_name' => 'CodeIgniter',                        'name' => 'CodeIgniter',              'slug' => 'codeigniter',               'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.codeigniter.com/',                                                'wikipedia' => 'https://en.wikipedia.org/wiki/CodeIgniter',                     'definition' => 'A free and open-source software rapid web development framework, for use in building dynamic web sites with PHP.[' ],
            [ 'id' => 8,   'full_name' => 'Cypress',                            'name' => 'Cypress',                  'slug' => 'cypress',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.cypress.io/',                                                     'wikipedia' => 'https://en.wikipedia.org/wiki/Cypress_(software)',              'definition' => 'A frontend test automation tool for regression testing of web applications that runs on Windows, Linux, and macOS.' ],
            [ 'id' => 9,   'full_name' => 'Django',                             'name' => 'Django',                   'slug' => 'django',                    'abbreviation' => null,      'open_source' => 1, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.djangoproject.com/',                                              'wikipedia' => 'https://en.wikipedia.org/wiki/Django_(web_framework)',          'definition' => 'A free and open-source, Python-based web framework that runs on a web server.' ],
            [ 'id' => 10,  'full_name' => 'Eclipse Jersey',                     'name' => 'Eclipse Jersey',           'slug' => 'eclipse-jersey',            'abbreviation' => null,      'open_source' => 1, 'proprietary' => 0, 'owner' => null,         'link' => 'https://eclipse-ee4j.github.io/jersey/',                                      'wikipedia' => 'https://en.wikipedia.org/wiki/Eclipse_Jersey',                  'definition' => 'An open source framework for developing RESTful Web Services in Java.' ],
            [ 'id' => 11,  'full_name' => 'Electron',                           'name' => 'Electron',                 'slug' => 'electron',                  'abbreviation' => null,      'open_source' => 1, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.electronjs.org/',                                                 'wikipedia' => 'https://en.wikipedia.org/wiki/Electron_(software_framework)',   'definition' => 'A free and open-source software framework developed and maintained by OpenJS Foundation.' ],
            [ 'id' => 12,  'full_name' => 'Ember.js',                           'name' => 'Ember.js',                 'slug' => 'ember-js',                  'abbreviation' => null,      'open_source' => 1, 'proprietary' => 0, 'owner' => null,         'link' => 'https://emberjs.com/',                                                        'wikipedia' => 'https://en.wikipedia.org/wiki/Ember.js',                        'definition' => 'An open-source JavaScript web framework that utilizes a component-service pattern.' ],
            [ 'id' => 13,  'full_name' => 'Express.js',                         'name' => 'Express.js',               'slug' => 'express-js',                'abbreviation' => null,      'open_source' => 1, 'proprietary' => 0, 'owner' => null,         'link' => 'https://expressjs.com/',                                                      'wikipedia' => 'https://en.wikipedia.org/wiki/Express.js',                      'definition' => 'A back end web application framework for building RESTful APIs with Node.js.' ],
            [ 'id' => 14,  'full_name' => 'FastAPI',                            'name' => 'FastAPI',                  'slug' => 'fastapi',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://fastapi.tiangolo.com/',                                               'wikipedia' => 'https://en.wikipedia.org/wiki/FastAPI',                         'definition' => '' ],
            [ 'id' => 15,  'full_name' => 'Flask',                              'name' => 'Flask',                    'slug' => 'flask',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://flask.palletsprojects.com/en/stable/',                                'wikipedia' => 'https://en.wikipedia.org/wiki/Flask_(web_framework)',           'definition' => '' ],
            [ 'id' => 16,  'full_name' => 'Foundation',                         'name' => 'Foundation',               'slug' => 'foundation',                'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://get.foundation/',                                                     'wikipedia' => 'https://en.wikipedia.org/wiki/Foundation_(framework)',          'definition' => '' ],
            [ 'id' => 17,  'full_name' => 'FuelPHP',                            'name' => 'FuelPHP',                  'slug' => 'fuelphp',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://fuelphp.com/',                                                        'wikipedia' => 'https://en.wikipedia.org/wiki/FuelPHP',                         'definition' => '' ],
            [ 'id' => 18,  'full_name' => 'gRPC',                               'name' => 'gRPC',                     'slug' => 'grpc',                      'abbreviation' => 'gRPC',    'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://grpc.io/',                                                            'wikipedia' => 'https://en.wikipedia.org/wiki/GRPC',                            'definition' => '' ],
            [ 'id' => 19,  'full_name' => 'Hibernate',                          'name' => 'Hibernate',                'slug' => 'hibernate',                 'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://hibernate.org/',                                                      'wikipedia' => 'https://en.wikipedia.org/wiki/Hibernate_(framework)',           'definition' => '' ],
            [ 'id' => 20,  'full_name' => 'InertiaJS',                          'name' => 'InertiaJS',                'slug' => 'inertiajs',                 'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://inertiajs.com/',                                                      'wikipedia' => null,                                                            'definition' => '' ],
            [ 'id' => 21,  'full_name' => 'Jest',                               'name' => 'Jest',                     'slug' => 'jest',                      'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://jestjs.io/',                                                          'wikipedia' => null,                                                            'definition' => '' ],
            [ 'id' => 22,  'full_name' => 'Jetpack Compose',                    'name' => 'Jetpack',                  'slug' => 'jetpack',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://en.wikipedia.org/wiki/Jetpack_Compose',                               'wikipedia' => 'https://developer.android.com/compose',                         'definition' => '' ],
            [ 'id' => 23,  'full_name' => 'JUnit',                              'name' => 'JUnit',                    'slug' => 'junit',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://junit.org/',                                                          'wikipedia' => 'https://en.wikipedia.org/wiki/Junit',                           'definition' => '' ],
            [ 'id' => 24,  'full_name' => 'Jupyter',                            'name' => 'Jupyter',                  'slug' => 'jupyter',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://jupyter.org/',                                                        'wikipedia' => 'https://en.wikipedia.org/wiki/Project_Jupyter',                 'definition' => '' ],
            [ 'id' => 25,  'full_name' => 'Laminas',                            'name' => 'Laminas',                  'slug' => 'laminas',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://getlaminas.org/',                                                     'wikipedia' => 'https://en.wikipedia.org/wiki/Laminas',                         'definition' => '' ],
            [ 'id' => 26,  'full_name' => 'LangChain',                          'name' => 'LangChain',                'slug' => 'langchain',                 'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.langchain.com/langgraph',                                         'wikipedia' => null,                                                            'definition' => '' ],
            [ 'id' => 27,  'full_name' => 'LangGraph',                          'name' => 'LangGraph',                'slug' => 'langgrah',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://laravel.com/',                                                        'wikipedia' => null,                                                            'definition' => '' ],
            [ 'id' => 28,  'full_name' => 'Laravel',                            'name' => 'Laravel',                  'slug' => 'laravel',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => null,                                                                          'wikipedia' => 'https://en.wikipedia.org/wiki/Laravel',                         'definition' => '' ],
            [ 'id' => 29,  'full_name' => 'Laravel Livewire',                   'name' => 'Laravel Livewire',         'slug' => 'laravel-livewire',          'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://laravel-livewire.com/',                                               'wikipedia' => null,                                                            'definition' => '' ],
            [ 'id' => 30,  'full_name' => 'Lightning Web Components',           'name' => 'Lightning Web Components', 'slug' => 'lwc',                       'abbreviation' => 'LWC',     'open_source' => 0, 'proprietary' => 0, 'owner' => 'Salesforce', 'link' => 'https://developer.salesforce.com/developer-centers/lightning-web-components', 'wikipedia' => null,                                                            'definition' => '' ],
            [ 'id' => 31,  'full_name' => 'Materialize',                        'name' => 'Materialize',              'slug' => 'materialize',               'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://materializecss.com/',                                                 'wikipedia' => null,                                                            'definition' => '' ],
            [ 'id' => 32,  'full_name' => 'Mocha',                              'name' => 'Mocha',                    'slug' => 'mocha',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://mochajs.org/',                                                        'wikipedia' => null,                                                            'definition' => '' ],
            [ 'id' => 33,  'full_name' => 'Mockito',                            'name' => 'Mockito',                  'slug' => 'mockito',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://site.mockito.org/',                                                   'wikipedia' => 'https://en.wikipedia.org/wiki/Mockito',                         'definition' => '' ],
            [ 'id' => 34,  'full_name' => 'Mono',                               'name' => 'Mono',                     'slug' => 'mono',                      'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.mono-project.com/',                                               'wikipedia' => 'https://en.wikipedia.org/wiki/Mono_(software)',                 'definition' => '' ],
            [ 'id' => 35,  'full_name' => 'NestJS',                             'name' => 'NestJS',                   'slug' => 'nestjs',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://nestjs.com/',                                                         'wikipedia' => 'https://en.wikipedia.org/wiki/NestJS',                          'definition' => '' ],
            [ 'id' => 36,  'full_name' => 'Next.js',                            'name' => 'Next.js',                  'slug' => 'next-js',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => 'Vercel',     'link' => 'https://nextjs.org/',                                                         'wikipedia' => 'https://en.wikipedia.org/wiki/Next.js',                         'definition' => '' ],
            [ 'id' => 37,  'full_name' => 'Nightwatch',                         'name' => 'Nightwatch',               'slug' => 'nightwatch',                'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://nightwatchjs.org/',                                                   'wikipedia' =>  null,                                                           'definition' => '' ],
            [ 'id' => 38,  'full_name' => 'Phalcon',                            'name' => 'Phalcon',                  'slug' => 'phalcon',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://phalcon.io/en-us',                                                    'wikipedia' => 'https://en.wikipedia.org/wiki/Phalcon_(framework)',             'definition' => '' ],
            [ 'id' => 39,  'full_name' => 'Phoenix',                            'name' => 'Phoenix',                  'slug' => 'phoenix',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.phoenixframework.org/',                                           'wikipedia' => 'https://en.wikipedia.org/wiki/Phoenix_(web_framework)',         'definition' => '' ],
            [ 'id' => 40,  'full_name' => 'PHPUnit',                            'name' => 'PHPUnit',                  'slug' => 'phpunit',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://phpunit.de/index.html',                                               'wikipedia' => 'https://en.wikipedia.org/wiki/PHPUnit',                         'definition' => '' ],
            [ 'id' => 41,  'full_name' => 'pytest',                             'name' => 'pytest',                   'slug' => 'pytest',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://docs.pytest.org/en/stable/',                                          'wikipedia' => 'https://en.wikipedia.org/wiki/Pytest',                          'definition' => '' ],
            [ 'id' => 42,  'full_name' => 'PyTorch',                            'name' => 'PyTorch',                  'slug' => 'pytorch',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://pytorch.org/',                                                        'wikipedia' => 'https://en.wikipedia.org/wiki/PyTorch',                         'definition' => '' ],
            [ 'id' => 43,  'full_name' => 'React Native',                       'name' => 'React Native',             'slug' => 'react-native',              'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://reactnative.dev/',                                                    'wikipedia' => 'https://en.wikipedia.org/wiki/React_Native',                    'definition' => '' ],
            [ 'id' => 44,  'full_name' => 'Remix',                              'name' => 'Remix',                    'slug' => 'remix',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://remix.run/',                                                          'wikipedia' => null,                                                            'definition' => '' ],
            [ 'id' => 45,  'full_name' => 'Slim',                               'name' => 'Slim',                     'slug' => 'slim',                      'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.slimframework.com/',                                              'wikipedia' => null,                                                            'definition' => '' ],
            [ 'id' => 46,  'full_name' => 'Spring Boot',                        'name' => 'Spring Boot',              'slug' => 'spring-boot',               'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://spring.io/projects/spring-boot',                                      'wikipedia' => 'https://en.wikipedia.org/wiki/Spring_Boot',                     'definition' => '' ],
            [ 'id' => 47,  'full_name' => 'Spring Framework',                   'name' => 'Spring Framework',         'slug' => 'sprint-framework',          'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://spring.io/projects/spring-framework',                                 'wikipedia' => 'https://en.wikipedia.org/wiki/Spring_Framework',                'definition' => '' ],
            [ 'id' => 48,  'full_name' => 'Svelte',                             'name' => 'Svelte',                   'slug' => 'svelte',                    'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://svelte.dev/',                                                         'wikipedia' => 'https://en.wikipedia.org/wiki/Svelte',                          'definition' => '' ],
            [ 'id' => 49,  'full_name' => 'SwiftUI',                            'name' => 'SwiftUI',                  'slug' => 'swiftfui',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => 'Apple',      'link' => 'https://developer.apple.com/swiftui/',                                        'wikipedia' => 'https://en.wikipedia.org/wiki/SwiftUI',                         'definition' => '' ],
            [ 'id' => 50,  'full_name' => 'Symfony',                            'name' => 'Symfony',                  'slug' => 'symfony',                   'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://symfony.com/',                                                        'wikipedia' => 'https://en.wikipedia.org/wiki/Symfony',                         'definition' => '' ],
            [ 'id' => 51,  'full_name' => 'Tailwind CSS',                       'name' => 'Tailwind CSS',             'slug' => 'tailwind-css',              'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://tailwindcss.com/',                                                    'wikipedia' => 'https://en.wikipedia.org/wiki/Tailwind_CSS',                    'definition' => '' ],
            [ 'id' => 52,  'full_name' => 'TestCafe',                           'name' => 'TestCafe',                 'slug' => 'testcafe',                  'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://testcafe.io/',                                                        'wikipedia' => null,                                                            'definition' => '' ],
            [ 'id' => 53,  'full_name' => 'Vue.js',                             'name' => 'Vue.js',                   'slug' => 'vue-js',                    'abbreviation' => 'Vue',     'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://vuejs.org/',                                                          'wikipedia' => 'https://en.wikipedia.org/wiki/Vue.js',                          'definition' => '' ],
            [ 'id' => 54,  'full_name' => 'Yii',                                'name' => 'Yii',                      'slug' => 'yii',                       'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://www.yiiframework.com/',                                               'wikipedia' => null,                                                            'definition' => '' ],
            [ 'id' => 55,  'full_name' => 'Bulma',                              'name' => 'Bulma',                    'slug' => 'bulma',                     'abbreviation' => null,      'open_source' => 1, 'proprietary' => 0, 'owner' => null,         'link' => 'https://bulma.io/',                                                           'wikipedia' => null,                                                            'definition' => 'An open source framework that provides ready-to-use frontend components that you can easily combine to build responsive web interfaces.' ],
            [ 'id' => 56,  'full_name' => 'Delta Lake',                         'name' => 'Delta Lake',               'slug' => 'delta-lake',                'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => 'https://delta.io/',                                                           'wikipedia' => null,                                                            'definition' => 'An open-source storage framework that enables building a format agnostic Lakehouse architecture.' ],
            [ 'id' => 57,  'full_name' => 'AWS Cloud Development Kit',          'name' => 'AWS CDK',                  'slug' => 'aws-cloud-development-kit', 'abbreviation' => 'AWS CDK', 'open_source' => 1, 'proprietary' => 0, 'owner' => null,         'link' => 'https://aws.amazon.com/cdk/',                                                 'wikipedia' => 'https://en.wikipedia.org/wiki/AWS_Cloud_Development_Kit',       'definition' => 'An open-source software development framework developed by Amazon Web Services (AWS) for defining and provisioning cloud infrastructure resources using familiar programming languages.' ],
            [ 'id' => 58,  'full_name' => 'other',                              'name' => 'other',                    'slug' => 'other',                     'abbreviation' => null,      'open_source' => 0, 'proprietary' => 0, 'owner' => null,         'link' => null,                                                                          'wikipedia' => null,                                                            'definition' => '' ],
        ];

        // add timestamps
        for($i=0; $i<count($data);$i++) {
            $data[$i]['created_at'] = now();
            $data[$i]['updated_at'] = now();
        }

        Framework::insert($data);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::connection($this->database_tag)->dropIfExists('frameworks');
    }
};
