<?php

use App\Models\Dictionary\Database;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    protected $database_tag = 'dictionary_db';

    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::connection($this->database_tag)->create('databases', function (Blueprint $table) {
            $table->id();
            $table->string('full_name')->unique();
            $table->string('name', 100)->unique();
            $table->string('slug', 100)->unique();
            $table->string('abbreviation', 20)->nullable();
            $table->string('definition', 500)->nullable();
            $table->tinyInteger('open_source')->default(0);
            $table->tinyInteger('proprietary')->default(0);
            $table->tinyInteger('compiled')->default(0);
            $table->string('owner', 100)->nullable();
            $table->string('wikipedia', 500)->nullable();
            $table->string('link', 500)->nullable();
            $table->string('link_name')->nullable();
            $table->text('description')->nullable();
            $table->string('image', 500)->nullable();
            $table->string('image_credit')->nullable();
            $table->string('image_source')->nullable();
            $table->string('thumbnail', 500)->nullable();
            $table->integer('sequence')->default(0);
            $table->tinyInteger('public')->default(1);
            $table->tinyInteger('readonly')->default(0);
            $table->tinyInteger('root')->default(0);
            $table->tinyInteger('disabled')->default(0);
            $table->timestamps();
            $table->softDeletes();
        });

        $data = [
            [ 'id' => 1,  'full_name' => 'Access',                   'name' => 'Access',             'slug' => 'access',                   'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://www.microsoft.com/en-us/microsoft-365/access',          'wikipedia' => 'https://en.wikipedia.org/wiki/Microsoft_Access',                   'definition' => 'A database management system (DBMS) from Microsoft that combines a relational database engine with a GUI and software-development tools.' ],
            [ 'id' => 2,  'full_name' => 'Amazon Aurora',            'name' => 'Aurora',             'slug' => 'amazon-aurora',            'abbreviation' => 'Aurora',    'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://aws.amazon.com/rds/aurora/',                            'wikipedia' => 'https://en.wikipedia.org/wiki/Amazon_Aurora',                      'definition' => 'A proprietary relational database offered as a service by Amazon Web Services (AWS).' ],
            [ 'id' => 3,  'full_name' => 'Amazon DynamoDB',          'name' => 'DynamoDB',           'slug' => 'amazon-dynamodb',          'abbreviation' => 'DynamoDB',  'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://aws.amazon.com/dynamodb/',                              'wikipedia' => 'https://en.wikipedia.org/wiki/Amazon_DynamoDB',                    'definition' => 'A managed NoSQL database service provided by Amazon Web Services (AWS).' ],
            [ 'id' => 4,  'full_name' => 'Amazon Redshift',          'name' => 'Redshift',           'slug' => 'amazon-redshift',          'abbreviation' => 'Redshift',  'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://aws.amazon.com/redshift/',                              'wikipedia' => 'https://en.wikipedia.org/wiki/Amazon_Redshift',                    'definition' => 'A data warehouse product which forms part of the larger cloud-computing platform Amazon Web Services.' ],
            [ 'id' => 5,  'full_name' => 'Azure Cosmos DB',          'name' => 'Cosmos DB',          'slug' => 'azure-cosmos-db',          'abbreviation' => 'Cosmos DB', 'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://azure.microsoft.com/en-us/products/cosmos-db',          'wikipedia' => 'https://en.wikipedia.org/wiki/Cosmos_DB',                          'definition' => 'A globally distributed, multi-model database service offered by Microsoft.' ],
            [ 'id' => 6,  'full_name' => 'Azure SQL Database',       'name' => 'Azure SQL Database', 'slug' => 'azure-sql-database',       'abbreviation' => 'Azure SQL', 'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://azure.microsoft.com/en-us/products/azure-sql/database', 'wikipedia' => 'https://en.wikipedia.org/wiki/Microsoft_Azure_SQL_Database',       'definition' => 'A managed cloud database (PaaS) cloud-based Microsoft SQL Servers, provided as part of Microsoft Azure services.' ],
            [ 'id' => 7,  'full_name' => 'BigQuery',                 'name' => 'BigQuery',           'slug' => 'bigquery',                 'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://cloud.google.com/bigquery',                             'wikipedia' => 'https://en.wikipedia.org/wiki/BigQuery',                           'definition' => 'A managed, serverless data warehouse product by Google, offering scalable analysis over large quantities of data.' ],
            [ 'id' => 8,  'full_name' => 'Bigtable',                 'name' => 'Bigtable',           'slug' => 'bigtable',                 'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => 'Google',           'link' => 'https://cloud.google.com/bigtable',                             'wikipedia' => 'https://en.wikipedia.org/wiki/Bigtable',                           'definition' => 'A fully managed wide-column and key-value NoSQL database service for large analytical and operational workloads as part of the Google Cloud portfolio.' ],
            [ 'id' => 9,  'full_name' => 'Cassandra',                'name' => 'Cassandra',          'slug' => 'cassandra',                'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://cassandra.apache.org/_/index.html',                     'wikipedia' => 'https://en.wikipedia.org/wiki/Apache_Cassandra',                   'definition' => 'A free and open-source database management system designed to handle large volumes of data across multiple commodity servers.' ],
            [ 'id' => 10, 'full_name' => 'ClickHouse',               'name' => 'ClickHouse',         'slug' => 'clickhouse',               'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://clickhouse.com/',                                       'wikipedia' => 'https://en.wikipedia.org/wiki/ClickHouse',                         'definition' => 'An open-source column-oriented DBMS (columnar database management system) for online analytical processing (OLAP) that allows users to generate analytical reports using SQL queries in real-time.' ],
            [ 'id' => 11, 'full_name' => 'CloudSQL',                 'name' => 'CloudSQL',           'slug' => 'cloudsql',                 'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => 'Google',           'link' => 'https://cloud.google.com/sql',                                  'wikipedia' => null,                                                               'definition' => 'A fully managed relational database service for PostgreSQL, MySQL, and SQL Server offered by Google' ],
            [ 'id' => 12, 'full_name' => 'Databricks',               'name' => 'Databricks',         'slug' => 'databricks',               'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => 'Databricks, Inc.', 'link' => 'https://www.databricks.com/',                                   'wikipedia' => 'https://en.wikipedia.org/wiki/Databricks',                         'definition' => 'A unified, cloud-based analytics platform for building, deploying, and maintaining data, analytics, and AI solutions at scale.' ],
            [ 'id' => 13, 'full_name' => 'DuckDB',                   'name' => 'DuckDB',             'slug' => 'duckdb',                   'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://duckdb.org/',                                           'wikipedia' => 'https://en.wikipedia.org/wiki/DuckDB',                             'definition' => 'An open-source column-oriented Relational Database Management System (RDBMS).' ],
            [ 'id' => 14, 'full_name' => 'Elasticsearch',            'name' => 'Elasticsearch',      'slug' => 'elasticsearch',            'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://www.elastic.co/',                                       'wikipedia' => 'https://en.wikipedia.org/wiki/Elasticsearch',                      'definition' => 'A source-available search engine based on Apache Lucene that provides a distributed, multitenant-capable full-text search engine.' ],
            [ 'id' => 15, 'full_name' => 'GraphQL',                  'name' => 'GraphQL',            'slug' => 'graphql',                  'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://graphql.org/',                                          'wikipedia' => 'https://en.wikipedia.org/wiki/GraphQL',                            'definition' => 'A data query and manipulation language that allows specifying what data is to be retrieved ("declarative data fetching") or modified.' ],
            [ 'id' => 16, 'full_name' => 'Hbase',                    'name' => 'Hbase',              'slug' => 'hbase',                    'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => 'Apache',           'link' => 'https://hbase.apache.org/',                                     'wikipedia' => 'https://en.wikipedia.org/wiki/Apache_HBase',                       'definition' => 'An open-source non-relational distributed database modeled after Google\'s Bigtable and written in Java.' ],
            [ 'id' => 17, 'full_name' => 'InfluxDB',                 'name' => 'InfluxDB',           'slug' => 'influxdb',                 'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://www.influxdata.com/',                                   'wikipedia' => 'https://en.wikipedia.org/wiki/InfluxDB',                           'definition' => 'A time series database (TSDB) developed by the company InfluxData.' ],
            [ 'id' => 18, 'full_name' => 'MariaDB',                  'name' => 'MariaDB',            'slug' => 'mariadb',                  'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://go.mariadb.com/',                                       'wikipedia' => 'https://en.wikipedia.org/wiki/MariaDB',                            'definition' => 'A community-developed, commercially supported fork of the MySQL relational database management system (RDBMS), intended to remain free and open-source software under the GNU General Public License.' ],
            [ 'id' => 19, 'full_name' => 'MaxDB',                    'name' => 'MaxDB',              'slug' => 'maxdb',                    'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://maxdb.sap.com/',                                        'wikipedia' => 'https://en.wikipedia.org/wiki/MaxDB',                              'definition' => 'An ANSI SQL-92 (entry level) compliant relational database management system (RDBMS) from SAP AG, which was also delivered by MySQL AB from 2003 to 2007.' ],
            [ 'id' => 20, 'full_name' => 'Memcached',                'name' => 'Memcached',          'slug' => 'memcached',                'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://memcached.org/',                                        'wikipedia' => 'https://en.wikipedia.org/wiki/Memcached',                          'definition' => 'A general-purpose distributed memory-caching system often used to speed up dynamic database-driven websites by caching data and objects in RAM .' ],
            [ 'id' => 21, 'full_name' => 'MongoDB',                  'name' => 'MongoDB',            'slug' => 'mongodb',                  'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://www.mongodb.com/',                                      'wikipedia' => 'https://en.wikipedia.org/wiki/MongoDB',                            'definition' => 'A cross-platform NoSQL database product that uses JSON-like documents with optional schemas.' ],
            [ 'id' => 22, 'full_name' => 'MySQL',                    'name' => 'MySQL',              'slug' => 'mysql',                    'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => 'Oracle',           'link' => 'https://www.mysql.com/',                                        'wikipedia' => 'https://en.wikipedia.org/wiki/MySQL',                              'definition' => 'An open-source relational database management system (RDBMS).' ],
            [ 'id' => 23, 'full_name' => 'NebulaGraph',              'name' => 'NebulaGraph',        'slug' => 'nebulagraph',              'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://www.nebula-graph.io/',                                  'wikipedia' => 'https://en.wikipedia.org/wiki/NebulaGraph',                        'definition' => 'A free software distributed graph database built for super large-scale graphs with milliseconds of latency.' ],
            [ 'id' => 25, 'full_name' => 'Oracle',                   'name' => 'Oracle',             'slug' => 'oracle',                   'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => 'Oracle',           'link' => 'https://www.oracle.com/',                                       'wikipedia' => 'https://en.wikipedia.org/wiki/Oracle_Database',                    'definition' => 'A proprietary multi-model database management system produced and marketed by Oracle Corporation.' ],
            [ 'id' => 26, 'full_name' => 'PostgreSQL',               'name' => 'PostgreSQL',         'slug' => 'postgresql',               'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://www.postgresql.org/',                                   'wikipedia' => 'https://en.wikipedia.org/wiki/PostgreSQL',                         'definition' => 'A free and open-source relational database management system (RDBMS) emphasizing extensibility and SQL compliance.' ],
            [ 'id' => 28, 'full_name' => 'RavenDB',                  'name' => 'RavenDB',            'slug' => 'ravendb',                  'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://ravendb.net/',                                          'wikipedia' => 'https://en.wikipedia.org/wiki/RavenDB',                            'definition' => 'An open-source document-oriented database written in C#, developed by Hibernating Rhinos Ltd.' ],
            [ 'id' => 29, 'full_name' => 'Redis',                    'name' => 'Redis',              'slug' => 'redis',                    'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://redis.io/',                                             'wikipedia' => 'https://en.wikipedia.org/wiki/Redis',                              'definition' => 'An in-memory key–value database, used as a distributed cache and message broker, with optional durability.' ],
            [ 'id' => 30, 'full_name' => 'ScyllaDB',                 'name' => 'ScyllaDB',           'slug' => 'scylladb',                 'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://www.scylladb.com/',                                     'wikipedia' => 'https://en.wikipedia.org/wiki/ScyllaDB',                           'definition' => 'A source-available distributed NoSQL wide-column data store. It was designed to be compatible with Apache Cassandra while achieving significantly higher throughputs and lower latencies.' ],
            [ 'id' => 31, 'full_name' => 'Snowflake',                'name' => 'Snowflake',          'slug' => 'snowflake',                'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://www.snowflake.com/en/',                                 'wikipedia' => 'https://en.wikipedia.org/wiki/Snowflake_Inc.',                     'definition' => 'Cloud-based data warehousing and data lake solutions offered from Snowflake Inc.' ],
            [ 'id' => 32, 'full_name' => 'SQL Server',               'name' => 'MSSQL',              'slug' => 'sql-server',               'abbreviation' => 'MSSQL',     'open_source' => 0, 'proprietary' => 0, 'owner' => 'Microsoft',        'link' => 'https://www.microsoft.com/en-us/sql-server',                    'wikipedia' => 'https://en.wikipedia.org/wiki/Microsoft_SQL_Server',               'definition' => 'A proprietary relational database management system developed by Microsoft using Structured Query Language (SQL).' ],
            [ 'id' => 33, 'full_name' => 'SQLite',                   'name' => 'SQLite',             'slug' => 'sqlite',                   'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://sqlite.org/',                                           'wikipedia' => 'https://en.wikipedia.org/wiki/SQLite',                             'definition' => 'A free and open-source relational database engine written in the C programming language.' ],
            [ 'id' => 34, 'full_name' => 'Venice',                   'name' => 'Venice',             'slug' => 'venice',                   'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://venicedb.org/',                                         'wikipedia' => null,                                                               'definition' => 'A derived data storage platform featuring high throughput asynchronous ingestion.' ],
            [ 'id' => 35, 'full_name' => 'Vitess',                   'name' => 'Vitess',             'slug' => 'vitess',                   'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://vitess.io/',                                            'wikipedia' => null,                                                               'definition' => 'A MySQL compatible database with extended scalability and built-in sharding.' ],
            [ 'id' => 36, 'full_name' => 'Presto',                   'name' => 'Presto',             'slug' => 'prestos',                  'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://prestodb.io/',                                          'wikipedia' => 'https://en.wikipedia.org/wiki/Presto_(SQL_query_engine)',          'definition' => 'A distributed query engine for big data using the SQL query language.' ],
            [ 'id' => 37, 'full_name' => 'other',                    'name' => 'other',              'slug' => 'other',                    'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => null,                                                            'wikipedia' => null,                                                               'definition' => '' ],
            [ 'id' => 38, 'full_name' => 'Neo4j',                    'name' => 'Neo4j',              'slug' => 'neo4j',                    'abbreviation' => null,        'open_source' => 0, 'proprietary' => 0, 'owner' => null,               'link' => 'https://neo4j.com/',                                            'wikipedia' => 'https://en.wikipedia.org/wiki/Neo4j',                              'definition' => 'A native graph database and analytics platform that stores data as interconnected nodes and relationships, making it ideal for applications that require a deep understanding of connections, like fraud detection, recommendation engines, and knowledge graphs.' ],
        ];

        // add timestamps
        for($i=0; $i<count($data);$i++) {
            $data[$i]['created_at'] = now();
            $data[$i]['updated_at'] = now();
        }

        Database::insert($data);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::connection($this->database_tag)->dropIfExists('databases');
    }
};
