<?php

use App\Models\Career\JobBoard;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $data = [
            1 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'other', 'slug' => 'other', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => null, 'linkedin_url' => null, 'jobs_url' => null, 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            2 => [ 'primary' => 1, 'founded' => 1990, 'recruiter_id' => null, 'name' => 'Dice', 'slug' => 'dice', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 1, 'street' => '6465 South Greenwood Plaza Boulevard, Suite 400', 'street2' => null, 'city' => 'Centennial', 'state_id' => null, 'zip' => '80111', 'country_id' => null, 'link' => 'https://dice.com/', 'linkedin_url' => 'https://www.linkedin.com/company/dice/', 'jobs_url' => 'https://www.dice.com/jobs', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'jobs|job search|it jobs|employment|career development|virtual events|resume search|career advice|tech hiring|technical recruiting|careers|ai career|tech career|remote job board|career events|recruiting|job opportunities|hiring|job boards|company search' ],
            3 => [ 'primary' => 1, 'founded' => null, 'recruiter_id' => null, 'name' => 'Indeed', 'slug' => 'indeed', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://indeed.com/', 'linkedin_url' => null, 'jobs_url' => 'https://www.indeed.com/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => null ],
            4 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'iHireTechnology', 'slug' => 'ihiretechnology', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://ihiretechnology.com/', 'linkedin_url' => null, 'jobs_url' => null, 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            5 => [ 'primary' => 0, 'founded' => 2007, 'recruiter_id' => null, 'name' => 'JobLeads', 'slug' => 'jobleads', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Hamburg', 'state_id' => null, 'zip' => null, 'country_id' => 88, 'link' => 'https://jobleads.com/', 'linkedin_url' => 'https://www.linkedin.com/company/jobleads-gmbh/', 'jobs_url' => 'https://www.jobleads.com/us/jobs', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'executive search|personal consulting|headhunter|senior professionals|executives|careers|c-level Jobs|it|internet' ],
            6 => [ 'primary' => 0, 'founded' => 2023, 'recruiter_id' => null, 'name' => 'Jobright.ai', 'slug' => 'jobrightai', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Santa Clara', 'state_id' => 5, 'zip' => null, 'country_id' => 237, 'link' => 'https://jobright.ai/', 'linkedin_url' => 'https://www.linkedin.com/company/jobright-ai/', 'jobs_url' => 'https://jobright.ai/jobs/recommend', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 7, 'specialties' => null ],
            7 => [ 'primary' => 0, 'founded' => 2015, 'recruiter_id' => null, 'name' => 'LaraJobs', 'slug' => 'larajobs', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://larajobs.com/', 'linkedin_url' => 'https://www.linkedin.com/company/larajobs/', 'jobs_url' => 'https://larajobs.com/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => null ],
            8 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Lensa', 'slug' => 'lensa', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://lensa.com/', 'linkedin_url' => null, 'jobs_url' => 'https://lensa.com/talent/job-opportunities', 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            9 => [ 'primary' => 1, 'founded' => 2002, 'recruiter_id' => null, 'name' => 'LinkedIn', 'slug' => 'linkedin', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://linkedin.com/', 'linkedin_url' => null, 'jobs_url' => 'https://www.linkedin.com/jobs/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            10 => [ 'primary' => 1, 'founded' => 1994, 'recruiter_id' => null, 'name' => 'Monster', 'slug' => 'monster', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Guaynabo', 'state_id' => null, 'zip' => null, 'country_id' => 178, 'link' => 'https://monster.com/', 'linkedin_url' => 'https://www.linkedin.com/company/monster/', 'jobs_url' => 'https://www.monster.com', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'talent management|recruitment process outsourcing|applicant tracking|recruiting|hiring|pay-per-performance recruitment advertising|ats integrations|online recruiting|job advertising|job search|career advice' ],
            11 => [ 'primary' => 1, 'founded' => 2004, 'recruiter_id' => null, 'name' => 'SimplyHired', 'slug' => 'simplyhired', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://simplyhired.com/', 'linkedin_url' => 'https://www.linkedin.com/company/simply-hired/', 'jobs_url' => 'https://www.simplyhired.com/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'recruitment|employment|search|jobs|advertising|job search|human resources|hr|online recruiting|job postings|pay-per-performance recruitment advertising network' ],
            12 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'VirtualVocations', 'slug' => 'virtualvocations', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.virtualvocations.com/', 'linkedin_url' => null, 'jobs_url' => 'https://www.virtualvocations.com/jobs', 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            13 => [ 'primary' => 1, 'founded' => 2010, 'recruiter_id' => null, 'name' => 'ZipRecruiter', 'slug' => 'ziprecruiter', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Santa Monica', 'state_id' => 5, 'zip' => null, 'country_id' => 237, 'link' => 'https://ziprecruiter.com/', 'linkedin_url' => 'https://www.linkedin.com/company/ziprecruiter/', 'jobs_url' => 'https://www.ziprecruiter.com/jobseeker/home', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'recruiting|hiring|job boards|job posting|web application|candidate screening|hr services|job alerts|artificial intelligence|tech|startup |ai|hr tech' ],
            14 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 4, 'name' => 'Robert Half', 'slug' => 'robert-half', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.roberthalf.com/us/en/jobs', 'linkedin_url' => null, 'jobs_url' => null, 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            15 => [ 'primary' => 0, 'founded' => 1997, 'recruiter_id' => 2, 'name' => 'CSS Staffing', 'slug' => 'css-staffing', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => '13110 Birch Drive STE 148 #351', 'street2' => null, 'city' => 'Omaha', 'state_id' => 28, 'zip' => '68164', 'country_id' => 237, 'link' => 'https://www.cssus.net/', 'linkedin_url' => 'https://www.linkedin.com/company/contract-staffing-specialists/', 'jobs_url' => 'https://www.cssus.net/it-employment-agency/', 'phone' => '(402) 334-8760', 'email' => 'info@cssus.net', 'recruiter_industry_id' => 6, 'specialties' => null ],
            16 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 3, 'name' => 'TalentFish', 'slug' => 'talentfish', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://talentfish.com/opportunities/', 'linkedin_url' => null, 'jobs_url' => null, 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            17 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 1, 'name' => 'Trova', 'slug' => 'trova', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.trovasearch.com/job-postings/', 'linkedin_url' => null, 'jobs_url' => null, 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            18 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 5, 'name' => 'Horizontal Talent', 'slug' => 'horizontal-talent', 'local' => 1, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.horizontaltalent.com/job-board', 'linkedin_url' => null, 'jobs_url' => null, 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            19 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 6, 'name' => 'Randstad USA', 'slug' => 'randstad-usa', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.randstadusa.com/jobs/', 'linkedin_url' => null, 'jobs_url' => null, 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            20 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 7, 'name' => 'CyberCoders', 'slug' => 'cybercoders', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.cybercoders.com/search', 'linkedin_url' => null, 'jobs_url' => null, 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            21 => [ 'primary' => 0, 'founded' => 2008, 'recruiter_id' => null, 'name' => 'RingSide Talent', 'slug' => 'ringside-talent', 'local' => 0, 'regional' => 1, 'national' => 0, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Columbus', 'state_id' => 36, 'zip' => null, 'country_id' => 237, 'link' => 'https://ringsidetalent.com/jobs/', 'linkedin_url' => 'https://www.linkedin.com/company/ringside-talent/', 'jobs_url' => null, 'phone' => '(614) 643-0700', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'recruiting & staffing|executive search|retained executive search|talent acquisition|finance|construction|engineering|information technology|architecture|contract staffing|temporary staffing|contract to hire staffing|payroll staffing|diversity recruiting|it recruiting|project and program manager staffing|accounting recruiting|finance recruiting|temporary staffing|contract to hire staffing' ],
            22 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'RIT Solutions', 'slug' => 'rit-solutions', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Arlington', 'state_id' => 47, 'zip' => null, 'country_id' => 237, 'link' => 'http://www.ritsolinc.com', 'linkedin_url' => 'https://www.linkedin.com/company/rit-solutions-inc/', 'jobs_url' => 'https://ritsolinc.jobs.net/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => null ],
            23 => [ 'primary' => 0, 'founded' => 2009, 'recruiter_id' => null, 'name' => 'Vernovis', 'slug' => 'vernovis', 'local' => 0, 'regional' => 1, 'national' => 0, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Mason', 'state_id' => 36, 'zip' => null, 'country_id' => 237, 'link' => 'https://vernovis.com/', 'linkedin_url' => null, 'jobs_url' => 'https://vernovis.com/search-jobs/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Resource-Based Consulting|Project Resources|Accounting|Finance|Audit|Systems|Tax|Treasury|Technology Talent|Subject-Matter Experts|Information Technology|Critical Projects|Cybersecurity|Direct Hire|1099|Contract|Contract to Hire|IT Operations|IT Staffing' ],
            24 => [ 'primary' => 0, 'founded' => 2007, 'recruiter_id' => null, 'name' => 'Glassdoor', 'slug' => 'glassdoor', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'San Francsco', 'state_id' => 5, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.glassdoor.com/', 'linkedin_url' => 'https://www.linkedin.com/company/glassdoor/', 'jobs_url' => 'https://www.glassdoor.com/Job/index.htm', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'Jobs|Interview Questions|Company Reviews|Office Photos|Salaries|Recruiting|Employment Branding|Benefits|Talent Acquistion|Talent Solutions' ],
            25 => [ 'primary' => 0, 'founded' => 2014, 'recruiter_id' => null, 'name' => 'Handshake', 'slug' => 'handshake', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'San Francsco', 'state_id' => 5, 'zip' => null, 'country_id' => 237, 'link' => 'https://joinhandshake.com/', 'linkedin_url' => 'https://www.linkedin.com/company/team-handshake/', 'jobs_url' => 'https://joinhandshake.com/students/whos-hiring/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 7, 'specialties' => 'Technology|Education|HR|internet|careers|higher education|recruiting|entry-level |diversity |STEM|AI|jobseeker' ],
            26 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Hire Central', 'slug' => 'hire-central', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => '2 Kallang Pudding Road', 'street2' => '#05-11 Mactech Building', 'city' => null, 'state_id' => null, 'zip' => '349307', 'country_id' => 201, 'link' => 'https://hirecentral.co/', 'linkedin_url' => null, 'jobs_url' => null, 'phone' => '+65 J6068372336', 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            27 => [ 'primary' => 0, 'founded' => 1995, 'recruiter_id' => null, 'name' => 'Craigslist', 'slug' => 'craigslist', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.craigslist.org', 'linkedin_url' => 'https://www.linkedin.com/company/craigslist/', 'jobs_url' => null, 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => null ],
            28 => [ 'primary' => 0, 'founded' => 2020, 'recruiter_id' => null, 'name' => 'Talent.com', 'slug' => 'talentcom', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Montreal', 'state_id' => 62, 'zip' => null, 'country_id' => 42, 'link' => 'https://www.talent.com/', 'linkedin_url' => 'https://www.linkedin.com/company/talent-com/', 'jobs_url' => 'https://www.talent.com/jobs', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'Job Search|Career Advice|Find a Job|Career Advancement|Job Platform|Jobs|Salary Calculator|Tax Calculator|Job Seekers' ],
            29 => [ 'primary' => 0, 'founded' => 2007, 'recruiter_id' => null, 'name' => 'FlexJobs', 'slug' => 'flexjobs', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Guaynabo', 'state_id' => null, 'zip' => null, 'country_id' => 178, 'link' => 'https://www.flexjobs.com/', 'linkedin_url' => 'https://www.linkedin.com/company/flexjobs-com/', 'jobs_url' => 'https://www.flexjobs.com/remote-jobs', 'phone' => '(866) 991-9222', 'email' => null, 'recruiter_industry_id' => 7, 'specialties' => 'Telecommuting Opportunities|Flexible Work Arrangements|Work-From-Home Jobs|Remote Job Search|Remote Work Advice|Flexible Job Marketplace|Remote Job Trends|Remote Job Networking|Remote Work Insights|Work-Life Balance Jobs|Virtual Work Solutions|Remote Job Guidance|Job Interviews|remote jobs near me|legit work from home jobs|entry-level remote jobs|part-time work from home jobs|remote jobs|online jobs|flex jobs' ],
            30 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'CareerBuilder', 'slug' => 'careerbuilder', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Guaynabo', 'state_id' => null, 'zip' => null, 'country_id' => 178, 'link' => 'https://www.careerbuilder.com/', 'linkedin_url' => 'https://www.linkedin.com/company/careerbuildercom/', 'jobs_url' => 'https://www.careerbuilder.com/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'Candidate Sourcing|Workforce Analytics|HR Software|Online Recruiting|Job Advertising|Pay-Per-Performance Recruitment Advertising|Job Search|Career Advice|ATS Integrations|Recruitment Marketing' ],
            31 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Snagajob', 'slug' => 'snagajob', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.snagajob.com/', 'linkedin_url' => 'https://www.linkedin.com/company/snagajob/', 'jobs_url' => 'https://www.snagajob.com/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'Hourly Hiring|Retail|Jobs|Applicant Tracking System (ATS)|Talent Sourcing|SaaS|HR Technology|Foodservice|Hospitality|Workforce Management|Service Industry|Onboarding & Compliance|Employee Scheduling|Job Search' ],
            32 => [ 'primary' => 0, 'founded' => 2003, 'recruiter_id' => null, 'name' => 'Ladders', 'slug' => 'ladders', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => 33, 'zip' => null, 'country_id' => null, 'link' => 'https://www.theladders.com/', 'linkedin_url' => 'https://www.linkedin.com/company/ladders/', 'jobs_url' => 'https://www.theladders.com/search', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'Job Search|Career Advice|Recruiting|Employment|Career Management' ],
            33 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'The Muse', 'slug' => 'the-muse', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'New York', 'state_id' => 33, 'zip' => '10001', 'country_id' => 237, 'link' => 'https://www.themuse.com/', 'linkedin_url' => 'https://www.linkedin.com/company/the-daily-muse/', 'jobs_url' => 'https://www.themuse.com/search', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'Career Advice|Job Opportunities|Women in Business|Job Search|Career Discovery|Employer Branding|Careers|Job Growth|Career Goals|Job Education|Career Culture|Career Impact' ],
            34 => [ 'primary' => 0, 'founded' => 1998, 'recruiter_id' => null, 'name' => 'Nexxt', 'slug' => 'nexxt', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Wayne', 'state_id' => 39, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.nexxt.com/', 'linkedin_url' => 'https://www.linkedin.com/company/nexxtinc/', 'jobs_url' => 'https://www.nexxt.com/jobs/search', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => null ],
            35 => [ 'primary' => 0, 'founded' => 2009, 'recruiter_id' => null, 'name' => 'CareerBliss', 'slug' => 'careerbliss', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '3972 Barranca Parkway, Ste J326', 'street2' => null, 'city' => 'Irvine', 'state_id' => 5, 'zip' => '92606', 'country_id' => 237, 'link' => 'https://www.careerbliss.com/', 'linkedin_url' => 'https://www.linkedin.com/company/careerbliss/', 'jobs_url' => 'https://www.careerbliss.com/jobs/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'Job listings|Company Reviews|Salaries|Job Advice Articles|Company Q&A' ],
            36 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'We Work Remotely', 'slug' => 'we-work-remotely', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Vancouver', 'state_id' => 53, 'zip' => null, 'country_id' => 42, 'link' => 'https://weworkremotely.com/', 'linkedin_url' => 'https://www.linkedin.com/company/we-work-remotely/', 'jobs_url' => 'https://weworkremotely.com/remote-full-time-jobs', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'Programming|Customer Support |DevOps/System Admin|Copywriting |Business Exec and Management|Marketing |Design|Job Search|Remote Jobs' ],
            37 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'The Job Network', 'slug' => 'the-job-network', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'New York', 'state_id' => 33, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.thejobnetwork.com/', 'linkedin_url' => 'https://www.linkedin.com/company/the-job-network/', 'jobs_url' => null, 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'recruiting|job search|talent acquisition|job matching' ],
            38 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Adzuna', 'slug' => 'adzuna', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.adzuna.com/', 'linkedin_url' => null, 'jobs_url' => null, 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'Jobs|Search|Recruitment|Classifieds|Online Advertising' ],
            39 => [ 'primary' => 0, 'founded' => 2000, 'recruiter_id' => null, 'name' => 'Geebo', 'slug' => 'geebo', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'McLean', 'state_id' => 47, 'zip' => '22101', 'country_id' => 237, 'link' => 'https://geebo.com/', 'linkedin_url' => 'https://www.linkedin.com/company/geebo-com/', 'jobs_url' => 'https://geebo.com/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'classifieds' ],
            40 => [ 'primary' => 0, 'founded' => 2002, 'recruiter_id' => null, 'name' => 'ClearanceJobs', 'slug' => 'clearancejobs', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Centennial', 'state_id' => 6, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.clearancejobs.com/', 'linkedin_url' => 'https://www.linkedin.com/company/clearancejobs/', 'jobs_url' => null, 'phone' => '(800) 947-3574', 'email' => null, 'recruiter_industry_id' => 2, 'specialties' => 'recruitment|security clearance jobs|cleared candidates|defense industry|intelligence careers|security clearance|defense jobs|staffing|aerospace|government contracting' ],
            41 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Jobs Juju', 'slug' => 'jobs-juju', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.jobsjuju.com/', 'linkedin_url' => null, 'jobs_url' => 'https://www.jobsjuju.com/jobs', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => null ],
            42 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'College Recruiter', 'slug' => 'college-recruiter', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.collegerecruiter.com/', 'linkedin_url' => null, 'jobs_url' => null, 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            43 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Careerjet', 'slug' => 'careerjet', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.careerjet.com/', 'linkedin_url' => 'https://www.linkedin.com/company/careerjet/', 'jobs_url' => 'https://www.careerjet.com/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 6, 'specialties' => 'search engine|jobs|internet|advertising|software development' ],
            44 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Wellfound', 'slug' => 'wellfound', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'New York', 'state_id' => 33, 'zip' => null, 'country_id' => 237, 'link' => 'https://wellfound.com/', 'linkedin_url' => 'https://www.linkedin.com/company/wellfoundhq/', 'jobs_url' => 'https://wellfound.com/jobs', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => null ],
            45 => [ 'primary' => 0, 'founded' => 2000, 'recruiter_id' => null, 'name' => 'Getwork', 'slug' => 'getwork', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://getwork.com/', 'linkedin_url' => 'https://www.linkedin.com/company/getwork-global/', 'jobs_url' => 'https://getwork.com/', 'phone' => '(866) 359-9360', 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'Job Search|Pay-Per-Click Solutions|Targeted Recruitment Marketing' ],
            46 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Remote.co', 'slug' => 'remote-co', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Boulder', 'state_id' => 6, 'zip' => null, 'country_id' => 237, 'link' => 'https://remote.co/', 'linkedin_url' => 'https://www.linkedin.com/company/remote-co/', 'jobs_url' => 'https://remote.co/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'Jobs|Job Search|Job Portal|Remote Job Portal|Remote Jobs|Remote Work|Telecommuting|Remote Career Resources|Remote Hiring|Remote Job Board|Digital Nomad Jobs' ],
            47 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Fiverr', 'slug' => 'fiverr', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '', 'street2' => null, 'city' => null, 'state_id' => 33, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.fiverr.com/', 'linkedin_url' => 'https://www.linkedin.com/company/fiverr-com/', 'jobs_url' => 'https://www.fiverr.com/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 7, 'specialties' => 'gigs|online marketplace|services|fiverr|small business|freelance|logo designs|resume editors|article writers|crowd economy|ecommerce|entrepeneur' ],
            48 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'GovernmentJobs.com', 'slug' => 'governmentjobs-com', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.governmentjobs.com/', 'linkedin_url' => null, 'jobs_url' => 'https://www.governmentjobs.com/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            49 => [ 'primary' => 0, 'founded' => 1996, 'recruiter_id' => null, 'name' => 'HigherEdJobs', 'slug' => 'higheredjobs', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'State College', 'state_id' => 39, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.higheredjobs.com/', 'linkedin_url' => 'https://www.linkedin.com/company/higheredjobs/', 'jobs_url' => 'https://www.higheredjobs.com/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 3, 'specialties' => 'higher education|recruitment|career advice|hiring resources|job search|faculty|administration|research|executive|colleges|universities' ],
            50 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'HiringCafe', 'slug' => 'hiringcafe', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'San Jose', 'state_id' => 5, 'zip' => null, 'country_id' => 237, 'link' => 'https://hiring.cafe/', 'linkedin_url' => 'https://www.linkedin.com/company/hiring-cafe/', 'jobs_url' => 'https://hiring.cafe/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => null ],
            51 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Job.com', 'slug' => 'jobcom', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://job.com/', 'linkedin_url' => null, 'jobs_url' => 'https://job.com/jobs/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            52 => [ 'primary' => 0, 'founded' => 2019, 'recruiter_id' => null, 'name' => 'Joblist', 'slug' => 'joblist', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Miami', 'state_id' => 10, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.joblist.com/', 'linkedin_url' => 'https://www.linkedin.com/company/joblist-com/', 'jobs_url' => 'https://www.joblist.com/search', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'jobs|employment|recruiting' ],
            53 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Simplify', 'slug' => 'simplify', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://simplify.jobs/', 'linkedin_url' => null, 'jobs_url' => 'https://simplify.jobs/ai-job-search', 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            54 => [ 'primary' => 0, 'founded' => 2015, 'recruiter_id' => null, 'name' => 'Upwork', 'slug' => 'upwork', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'San Francisco', 'state_id' => 5, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.upwork.com/', 'linkedin_url' => 'https://www.linkedin.com/company/upwork/', 'jobs_url' => 'https://www.upwork.com/freelance-jobs/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 7, 'specialties' => 'freelancers|agencies' ],
            55 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Welcome to the Jungle', 'slug' => 'welcome-to-the-jungle', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.welcometothejungle.com/en', 'linkedin_url' => 'https://www.linkedin.com/company/wttj-en/', 'jobs_url' => 'https://www.welcometothejungle.com/en/jobs', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => null ],
            56 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Remote Rocketship', 'slug' => 'remote-rocketship', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.remoterocketship.com/', 'linkedin_url' => 'https://www.linkedin.com/company/remote-rocketship/', 'jobs_url' => 'https://www.remoterocketship.com/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            57 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Snaphunt', 'slug' => 'snaphunt', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Boston', 'state_id' => 22, 'zip' => null, 'country_id' => 237, 'link' => 'https://snaphunt.com/', 'linkedin_url' => 'https://www.linkedin.com/company/snaphunt/', 'jobs_url' => 'https://snaphunt.com/job-listing', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 7, 'specialties' => 'recruiting|hiring|video interview|staffing|ai|data driven hiring|hiring marketplace|talent sourcing|talent matching|reference checking|ats|remotetalent|startups|remote hiring|remote work|remote' ],
            58 => [ 'primary' => 0, 'founded' => 2014, 'recruiter_id' => null, 'name' => 'Remotive', 'slug' => 'remotive', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'New York', 'state_id' => 33, 'zip' => null, 'country_id' => 237, 'link' => 'https://remotive.com/', 'linkedin_url' => 'https://www.linkedin.com/company/remotive.io/', 'jobs_url' => null, 'phone' => null, 'email' => 'hello@remotive.com', 'recruiter_industry_id' => 9, 'specialties' => 'remote work|work from home|remote jobs|software development|customer support|job search|recruiting|jobs|hr|job boards|remote|work|work from home jobs|flexible jobs|virtual jobs|remote hiring|Programming|software development|jobsearch' ],
            59 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'RemoteHub', 'slug' => 'remotehub', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.remotehub.com/', 'linkedin_url' => null, 'jobs_url' => 'https://www.remotehub.com/jobs', 'phone' => null, 'email' => 'info@remotehub.com', 'recruiter_industry_id' => null, 'specialties' => null ],
            60 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Real Work From Anywhere', 'slug' => 'real-work-from-anywhere', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.realworkfromanywhere.com/', 'linkedin_url' => 'https://www.linkedin.com/company/realworkfromanywhere/', 'jobs_url' => 'https://www.realworkfromanywhere.com/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => null ],
            61 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'DailyRemote', 'slug' => 'dailyremote', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'New York', 'state_id' => 33, 'zip' => null, 'country_id' => 237, 'link' => 'https://dailyremote.com/', 'linkedin_url' => 'https://www.linkedin.com/company/dailyremote/', 'jobs_url' => null, 'phone' => null, 'email' => 'contact+jobseekers@dailyremote.com', 'recruiter_industry_id' => 9, 'specialties' => null ],
            62 => [ 'primary' => 0, 'founded' => 2014, 'recruiter_id' => null, 'name' => 'Working Nomads', 'slug' => 'working-nomads', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.workingnomads.com/', 'linkedin_url' => 'https://www.linkedin.com/company/working-nomads/', 'jobs_url' => 'https://www.workingnomads.com/jobs', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 4, 'specialties' => 'remote work|digital' ],
            63 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'RemoteJobsFinder.co', 'slug' => 'remotejobsfinder-co', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://remotejobsfinder.co/', 'linkedin_url' => null, 'jobs_url' => 'https://remotejobsfinder.co/en', 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            64 => [ 'primary' => 0, 'founded' => 1996, 'recruiter_id' => null, 'name' => 'Naukri', 'slug' => 'naukri', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.naukri.com/', 'linkedin_url' => 'https://www.linkedin.com/company/naukri.com/', 'jobs_url' => 'https://www.naukri.com/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'Online Recruitment Solution Provider' ],
            65 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Just Join IT', 'slug' => 'just-join-it', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://justjoin.it/', 'linkedin_url' => null, 'jobs_url' => 'https://justjoin.it/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            66 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'Hubstaff Talent', 'slug' => 'hubstaff-talent', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://hubstafftalent.net/', 'linkedin_url' => null, 'jobs_url' => 'https://hubstafftalent.net/search/jobs', 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            67 => [ 'primary' => 0, 'founded' => 2024, 'recruiter_id' => null, 'name' => 'MeeBoss', 'slug' => 'meeboss', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Bellevue', 'state_id' => 48, 'zip' => null, 'country_id' => 237, 'link' => 'https://meeboss.com/', 'linkedin_url' => 'https://www.linkedin.com/company/meeboss/', 'jobs_url' => 'https://meeboss.com/job', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => 'Direct Recruiting|Recruiting AI|Secured Chat|Job Recommendations|Chat & Apply' ],
            68 => [ 'primary' => 0, 'founded' => 2022, 'recruiter_id' => null, 'name' => 'HireBasis', 'slug' => 'hirebasis', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => 'https://www.hirebasis.com/', 'linkedin_url' => 'https://www.linkedin.com/company/hirebasis/', 'jobs_url' => 'https://www.hirebasis.com/find-work', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'employment board|job board|remote work|EOR Affiliate' ],
            69 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'COMPANY WEBSITE', 'slug' => 'company-website', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => null, 'linkedin_url' => null, 'jobs_url' => null, 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            70 => [ 'primary' => 0, 'founded' => null, 'recruiter_id' => null, 'name' => 'INQUIRY', 'slug' => 'inquiry', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => null, 'link' => null, 'linkedin_url' => null, 'jobs_url' => null, 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
        ];

        foreach ($data as $id=>$row) {
            if (!$jobBoard = new JobBoard()->newQuery()->find($id)) {
                echo PHP_EOL . $id . ') ' . $row['name'] . ' *** NOT FOUND ***';
            }

            foreach ($row as $col=>$val) {
                $jobBoard->{$col} = $val;
            }

            $jobBoard->save();
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('career_job_boards', function (Blueprint $table) {
            //
        });
    }
};
