<?php

use App\Models\Career\Recruiter;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        //
        // update recruiters
        $data = [
            [ 'name' => 'Actalent', 'slug' => 'actalent', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://www.actalentservices.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/actalentservices/', 'postings_url' => 'https://www.actalentservices.com/en/careers' ],
            [ 'name' => 'Addison Group', 'slug' => 'addison-group', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => '225 W Randolph, Suite 1900', 'street2' => null, 'city' => 'Chicago', 'state_id' => 14, 'zip' => '60606', 'country_id' => 237, 'founded' => null, 'link' => 'https://www.addisongroup.com/', 'phone' => '(312) 424-0300', 'email' => 'mediarelations@addisongroup.com', 'linkedin_url' => 'https://www.linkedin.com/groups/2508146/', 'postings_url' => 'https://addisongroup.com/jobs/' ],
            [ 'name' => 'Adecco', 'slug' => 'adecco', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => 1996, 'link' => 'https://www.adeccousa.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/adecco/', 'postings_url' => 'https://www.adecco.com/en-us/job-search' ],
            [ 'name' => 'Aerotek', 'slug' => 'aerotek', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => '7301 Parkway Drive South', 'street2' => null, 'city' => 'Hanover', 'state_id' => 21, 'zip' => '21703', 'country_id' => 237, 'founded' => 1983, 'link' => 'https://www.aerotek.com/', 'phone' => '(410) 694-5100', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/aerotek/', 'postings_url' => 'https://jobs.aerotek.com/us/en' ],
            [ 'name' => 'Akkodis', 'slug' => 'akkodis', 'primary' => 0, 'national' => 0, 'international' => 11, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://www.akkodis.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/akkodis/', 'postings_url' => 'https://www.akkodis.com/en-us/careers/job-results' ],
            [ 'name' => 'Allegis Group', 'slug' => 'allegis-group', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://www.allegisgroup.com/', 'phone' => null, 'email' => null, 'linkedin_url' => null, 'postings_url' => 'https://careers-allegisgroup.icims.com/jobs/search' ],
            [ 'name' => 'Apex Systems', 'slug' => 'apex-systems', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '4400 Cox Road, Suite 200', 'street2' => null, 'city' => 'Glen Allen', 'state_id' => 47, 'zip' => '23060', 'country_id' => 237, 'founded' => null, 'link' => 'https://www.apexsystems.com', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/apex-systems/', 'postings_url' => 'https://www.apexsystems.com/search-results-usa' ],
            [ 'name' => 'AppleOne Employment Services', 'slug' => 'appleone-employment-services', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Glendale', 'state_id' => 5, 'zip' => null, 'country_id' => 237, 'founded' => 1964, 'link' => 'https://www.appleone.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/appleone/', 'postings_url' => 'https://www.appleone.com/CareerSearch/' ],
            [ 'name' => 'Artech Information Systems', 'slug' => 'artech-information-systems', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '360 Mt. Kemble Avenue,  Suite 2000', 'street2' => null, 'city' => 'Morristown', 'state_id' => 31, 'zip' => null, 'country_id' => 237, 'founded' => 1992, 'link' => 'https://www.artech.com/', 'phone' => '(973) 998-2500', 'email' => null, 'linkedin_url' => null, 'postings_url' => null ],
            [ 'name' => 'Aston Carter', 'slug' => 'aston-carter', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Hanover', 'state_id' => 21, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://www.astoncarter.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/aston-carter/', 'postings_url' => 'https://careers.astoncarter.com/us/en' ],
            [ 'name' => 'Beacon Hill Staffing Group', 'slug' => 'beacon-hill-staffing-group', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '20 Ashburton Pl', 'street2' => null, 'city' => 'Boston', 'state_id' => 22, 'zip' => '02108', 'country_id' => 237, 'founded' => null, 'link' => 'https://bhsg.com/', 'phone' => '(617) 326-4000', 'email' => null, 'linkedin_url' => null, 'postings_url' => 'https://bhsg.com/jobs/' ],
            [ 'name' => 'Elwood Staffing', 'slug' => 'belflex-staffing-network', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '4111 Central Avenue', 'street2' => null, 'city' => 'Cincinnati', 'state_id' => 36, 'zip' => '47203', 'country_id' => 237, 'founded' => 1989, 'link' => 'https://www.elwoodstaffing.com/', 'phone' => '(812) 372-6200', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/belflex-staffing-network/about/', 'postings_url' => 'https://www.elwoodstaffing.com/jobsearch/' ],
            [ 'name' => 'Bridge Technical Talent ', 'slug' => 'bridge-technical-talent-', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => '1130 Ten Rod Road, Suite A103', 'street2' => null, 'city' => 'North Kingston', 'state_id' => 40, 'zip' => '02852', 'country_id' => 237, 'founded' => 2002, 'link' => 'http://www.bridge-talent.com/', 'phone' => '(401) 398-1900', 'email' => ' contacts@bridge-talent.com', 'linkedin_url' => null, 'postings_url' => null ],
            [ 'name' => 'Brooksource', 'slug' => 'brooksource', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '6215 N College Ave.', 'street2' => null, 'city' => 'Indianapolis', 'state_id' => 15, 'zip' => '46220', 'country_id' => 237, 'founded' => 2000, 'link' => 'https://www.brooksource.com/', 'phone' => '(317) 475-0079', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/brooksource/', 'postings_url' => 'https://jobs.brooksource.com/jobs/' ],
            [ 'name' => 'CodeImpact B.V.', 'slug' => 'codeimpact-b.v.', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => 'Teggert 140', 'street2' => null, 'city' => 'Voerendaal', 'state_id' => null, 'zip' => '6367XR ', 'country_id' => 156, 'founded' => null, 'link' => 'https://codeimpact.nl/', 'phone' => '+3 (185) 225-D90504', 'email' => 'info@codeimpact.nl', 'linkedin_url' => null, 'postings_url' => 'https://codeimpact.nl/nl/jobs/' ],
            [ 'name' => 'Collabera', 'slug' => 'collabera', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Basking Ridge', 'state_id' => 31, 'zip' => null, 'country_id' => 237, 'founded' => 1996, 'link' => 'https://www.collabera.com/', 'phone' => '(973) 889-5200', 'email' => ' info@collabera.com', 'linkedin_url' => 'https://www.linkedin.com/company/collabera/', 'postings_url' => 'https://collabera.com/job-search/' ],
            [ 'name' => 'CSS Tec', 'slug' => 'css-tec', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '1400 N. Providence Rd', 'street2' => 'Building 2, Suite 1205', 'city' => 'Media', 'state_id' => 29, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'http://www.css-tec.com', 'phone' => '(612) 565-4300', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/css-tec/', 'postings_url' => null ],
            [ 'name' => 'DataTeams', 'slug' => 'datateams', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://www.datateams.ai/', 'phone' => '+91 (974) 200-Q166911', 'email' => 'connect@datateams.ai', 'linkedin_url' => null, 'postings_url' => 'https://datateams.zohorecruit.in/jobs/Careers' ],
            [ 'name' => 'DISYS', 'slug' => 'disys', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => '8270 Greensboro Drive, Suite 1000', 'street2' => null, 'city' => 'McLean', 'state_id' => 47, 'zip' => '22102', 'country_id' => 237, 'founded' => null, 'link' => 'https://www.disys.com/', 'phone' => '(703) 752-7900', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/disys/', 'postings_url' => 'https://dexian.com/jobs/' ],
            [ 'name' => 'Diversant LLC', 'slug' => 'diversant-llc', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => '1455 Lincoln Parkway East, 8th Floor', 'street2' => null, 'city' => 'Atlanta', 'state_id' => 11, 'zip' => '30346', 'country_id' => 237, 'founded' => 1998, 'link' => 'https://innovasolutions.com/', 'phone' => '(770) 493-5588', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/diversant-llc/', 'postings_url' => 'https://innovasolutions.com/' ],
            [ 'name' => 'EdgeLink', 'slug' => 'edgelink', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 107, 'founded' => 2016, 'link' => 'https://www.linkedin.com/company/edgelink-technology-pvt-ltd/', 'phone' => '(932) 929-5654', 'email' => 'hr@edgelinktechnology.com', 'linkedin_url' => 'https://www.linkedin.com/company/edgelink-technology-pvt-ltd/', 'postings_url' => null ],
            [ 'name' => 'Emergent Staffing', 'slug' => 'emergent-staffing', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'St. Paul', 'state_id' => 24, 'zip' => null, 'country_id' => 237, 'founded' => 2020, 'link' => 'https://www.emergentstaffing.net/', 'phone' => '(612) 217-747', 'email' => 'hello@emergentstaffing.net', 'linkedin_url' => 'https://www.linkedin.com/company/emergent-staffing/', 'postings_url' => 'https://www.emergentstaffing.net/job-seekers/open-jobs/' ],
            [ 'name' => 'Employbridge', 'slug' => 'employbridge', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '1845 Satellite Blvd, Suite 300', 'street2' => null, 'city' => 'Duluth', 'state_id' => 11, 'zip' => '30097', 'country_id' => 237, 'founded' => 1997, 'link' => 'https://www.employbridge.com/', 'phone' => '(888) 381-7248', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/employbridge/', 'postings_url' => 'https://www.employbridge.com/job-search' ],
            [ 'name' => 'Epitec', 'slug' => 'epitec', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => '26555 Evergreen Rd., Suite 1700', 'street2' => null, 'city' => 'Southfield', 'state_id' => 23, 'zip' => '48076', 'country_id' => 237, 'founded' => 1978, 'link' => 'https://epitec.com/', 'phone' => '(248) 353-6800', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/epitec/', 'postings_url' => 'https://epitec.com/jobs-at-epitec/' ],
            [ 'name' => 'Experis', 'slug' => 'experis', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Milwaukee', 'state_id' => 50, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://www.experis.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/experis/', 'postings_url' => 'https://www.experis.com/en/search' ],
            [ 'name' => 'Express Employment Professionals', 'slug' => 'express-employment-professionals', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => 1983, 'link' => 'https://www.expresspros.com/', 'phone' => null, 'email' => null, 'linkedin_url' => null, 'postings_url' => 'https://www.expresspros.com/job-seekers/search-jobs' ],
            [ 'name' => 'FatCat Remote', 'slug' => 'fatcat-remote', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://fatcatremote.com/', 'phone' => null, 'email' => null, 'linkedin_url' => null, 'postings_url' => null ],
            [ 'name' => 'Frontline Source Group', 'slug' => 'frontline-source-group', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Dallas', 'state_id' => 44, 'zip' => null, 'country_id' => 237, 'founded' => 2004, 'link' => 'https://www.frontlinesourcegroup.com/technology-it.html', 'phone' => '(214) 760-7700', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/frontline-source-group/', 'postings_url' => 'https://jobs.frontlinesourcegroup.com/' ],
            [ 'name' => 'Frontline Source Group Holdings', 'slug' => 'frontline-source-group-holdings', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '2001 Ross Ave Suite #700-161', 'street2' => null, 'city' => 'Dallas', 'state_id' => 44, 'zip' => '75201', 'country_id' => 237, 'founded' => 2010, 'link' => 'https://www.frontlinesourcegroupholdings.com/', 'phone' => '(214) 742-1300', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/frontline-source-group-holdings/', 'postings_url' => 'https://jobs.dfwhr.com/' ],
            [ 'name' => 'Genuent', 'slug' => 'genuent', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://www.genuent.com/', 'phone' => '(844) 693-3947', 'email' => null, 'linkedin_url' => null, 'postings_url' => 'https://www.inspyrsolutions.com/job-search/#opportunities' ],
            [ 'name' => 'Go Carpathian', 'slug' => 'go-carpathian', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://gocarpathian.com/', 'phone' => '', 'email' => 'hello@gocarpathian.com', 'linkedin_url' => 'https://gocarpathian.com/', 'postings_url' => null ],
            [ 'name' => 'GoGloby', 'slug' => 'gogloby', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => '8 The Green, Ste. R', 'street2' => null, 'city' => 'Dover', 'state_id' => 8, 'zip' => '19901', 'country_id' => 237, 'founded' => null, 'link' => 'https://gogloby.com/', 'phone' => '(617) 555-0108', 'email' => 'hr@gogloby.com', 'linkedin_url' => null, 'postings_url' => null ],
            [ 'name' => 'Hays', 'slug' => 'hays', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'London', 'state_id' => null, 'zip' => null, 'country_id' => 234, 'founded' => null, 'link' => 'https://www.hays.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/hays/', 'postings_url' => 'https://www.hays.com/job-search' ],
            [ 'name' => 'Haystack', 'slug' => 'haystack', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Newcastle upon Tyne', 'state_id' => null, 'zip' => null, 'country_id' => 234, 'founded' => 2021, 'link' => 'https://haystackapp.io/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/wearehaystack/', 'postings_url' => 'https://haystackapp.io/tech-talent' ],
            [ 'name' => 'Hire Resolve', 'slug' => 'hire-resolve', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => '4343 N Scottsdale Road, Suite 150', 'street2' => null, 'city' => 'Scottsdale', 'state_id' => 3, 'zip' => '85251', 'country_id' => 237, 'founded' => null, 'link' => 'https://hireresolve.us/', 'phone' => '(80) 530-3705', 'email' => 'arizona@hireresolve.us', 'linkedin_url' => null, 'postings_url' => null ],
            [ 'name' => 'Insight Global', 'slug' => 'insight-global', 'primary' => 1, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Atlanta', 'state_id' => 11, 'zip' => null, 'country_id' => 237, 'founded' => 2001, 'link' => 'https://www.linkedin.com/company/insight-global/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/insight-global/', 'postings_url' => 'https://insightglobal.com/jobs/' ],
            [ 'name' => 'Motion Recruitment', 'slug' => 'motion-recruitment', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '185 Dartmouth St., Suite 1105', 'street2' => null, 'city' => 'Boston', 'state_id' => 22, 'zip' => '02116', 'country_id' => 237, 'founded' => 1989, 'link' => 'https://motionrecruitment.com/', 'phone' => '(617) 266-6200', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/jobspring-partners/', 'postings_url' => 'https://motionrecruitment.com/tech-jobs' ],
            [ 'name' => 'Kelly Services', 'slug' => 'kelly-services', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Troy', 'state_id' => 23, 'zip' => null, 'country_id' => 237, 'founded' => 1946, 'link' => 'https://www.kellyservices.com/', 'phone' => '(800) KELLY-01', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/kellyservices/', 'postings_url' => 'https://www.mykelly.com/' ],
            [ 'name' => 'Kforce', 'slug' => 'kforce', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => '1150 Assembly Drive, Suite 500', 'street2' => null, 'city' => 'Tampa', 'state_id' => 10, 'zip' => '33607', 'country_id' => 237, 'founded' => 1962, 'link' => 'https://www.kforce.com/', 'phone' => '(877) 453-6723', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/kforce/', 'postings_url' => 'https://www.kforce.com/find-work/search-jobs/' ],
            [ 'name' => 'LaSalle Network', 'slug' => 'lasalle-network', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => '200 N LaSalle St', 'street2' => null, 'city' => 'Chicago', 'state_id' => 14, 'zip' => '60601', 'country_id' => 237, 'founded' => 1998, 'link' => 'https://www.thelasallenetwork.com/', 'phone' => '(312) 419-1700​', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/lasalle-network/', 'postings_url' => null ],
            [ 'name' => 'LHH', 'slug' => 'lhh', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Jacksonville', 'state_id' => 10, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://www.lhh.com/', 'phone' => null, 'email' => null, 'linkedin_url' => null, 'postings_url' => 'https://www.lhh.com/en-us/search-jobs' ],
            [ 'name' => 'Lucas Group', 'slug' => 'lucas-group', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Los Angeles', 'state_id' => 5, 'zip' => null, 'country_id' => 237, 'founded' => 1970, 'link' => 'https://www.kornferry.com/about-us/our-story/lucas-group', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/lucas-group/', 'postings_url' => 'https://www.kornferry.com/careers/candidates' ],
            [ 'name' => 'Major, Lindsey, & Africa', 'slug' => 'major-lindsey-and-africa', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => '7437 Race Rd', 'street2' => null, 'city' => 'Hanover', 'state_id' => 21, 'zip' => '21076', 'country_id' => 237, 'founded' => 1982, 'link' => 'https://careers.mlaglobal.com/', 'phone' => '(877) 482-1010', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/major-lindsey-africa/', 'postings_url' => 'https://careers.mlaglobal.com/us/en' ],
            [ 'name' => 'Manpower', 'slug' => 'manpower', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => 1948, 'link' => 'https://www.manpower.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/manpower-/', 'postings_url' => 'https://www.manpower.com/en/search' ],
            [ 'name' => 'MarketSource', 'slug' => 'marketsource', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '11700 Great Oaks Way, Suite 100', 'street2' => null, 'city' => 'Alpharetta', 'state_id' => 11, 'zip' => '30022', 'country_id' => 237, 'founded' => 1975, 'link' => 'https://www.marketsource.com/', 'phone' => '(770) 674-5000', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/marketsource-inc/', 'postings_url' => 'https://applyatmarketsource-msc.icims.com/jobs/search' ],
            [ 'name' => 'Mondo', 'slug' => 'mondo', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'New York', 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => 2000, 'link' => 'https://mondo.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/mondo/', 'postings_url' => 'https://mondo.com/get-hired/' ],
            [ 'name' => 'On Assignment, Inc.', 'slug' => 'on-assignment-inc', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => 33, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://onassignments.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/onassignments/', 'postings_url' => null ],
            [ 'name' => 'PDS Tech', 'slug' => 'pds-tech', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://pdstech.com/', 'phone' => null, 'email' => null, 'linkedin_url' => null, 'postings_url' => 'https://www.pdstech.com/job-search' ],
            [ 'name' => 'Pearl Talent', 'slug' => 'pearl-talent', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'New York', 'state_id' => 33, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://www.pearltalent.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/pearltalent/', 'postings_url' => 'https://www.pearltalent.com/remote-jobs-directory' ],
            [ 'name' => 'Pinnacle Group', 'slug' => 'pinnacle-group', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => '10670 N. Central Expy, Suite 600', 'street2' => null, 'city' => 'Dallas', 'state_id' => 44, 'zip' => '75231', 'country_id' => 237, 'founded' => 1996, 'link' => 'https://www.pinnacle1.com/', 'phone' => '(214) 740-2424', 'email' => 'mspinquiries@pinnacle1.com', 'linkedin_url' => null, 'postings_url' => 'https://jobs.pinnacle1.com/' ],
            [ 'name' => 'PrideStaff', 'slug' => 'pridestaff', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '7535 North Palm Avenue, Suite 101', 'street2' => null, 'city' => 'Fresno', 'state_id' => 5, 'zip' => '93711', 'country_id' => 237, 'founded' => 1978, 'link' => 'https://www.pridestaff.com/', 'phone' => '(800) 774-3316', 'email' => 'info@pridestaff.com', 'linkedin_url' => 'https://www.linkedin.com/company/pridestaff/', 'postings_url' => 'https://jobs.pridestaff.com/' ],
            [ 'name' => 'Staffmark', 'slug' => 'staffmark', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '191 Rosa Parks Street, 10th Floor', 'street2' => null, 'city' => 'Cincinnati', 'state_id' => 36, 'zip' => '45202', 'country_id' => 237, 'founded' => null, 'link' => 'https://staffmark.com/', 'phone' => '(866) 765-7544', 'email' => 'AskHR@staffmarkgroup.com', 'linkedin_url' => 'https://www.linkedin.com/company/staffmark/', 'postings_url' => null ],
            [ 'name' => 'Remote People', 'slug' => 'remote-people', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => '85 Broad St', 'street2' => null, 'city' => 'New York', 'state_id' => 33, 'zip' => '10004', 'country_id' => 237, 'founded' => null, 'link' => 'https://remotepeople.com/', 'phone' => null, 'email' => null, 'linkedin_url' => null, 'postings_url' => null ],
            [ 'name' => 'ResourceMFG', 'slug' => 'resourcemfg', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Atlanta', 'state_id' => 11, 'zip' => null, 'country_id' => 237, 'founded' => 1996, 'link' => 'https://www.resourcemfg.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/resourcemfg/', 'postings_url' => 'https://www.resourcemfg.com/jobs/' ],
            [ 'name' => 'RightStone', 'slug' => 'rightstone', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '6029 Belt Line Rd, Suite 260', 'street2' => null, 'city' => 'Plano', 'state_id' => 44, 'zip' => '75254', 'country_id' => 237, 'founded' => 1996, 'link' => 'https://www.rightstone.com/', 'phone' => '(972) 895-2555', 'email' => 'info@rightstone.com', 'linkedin_url' => 'https://www.linkedin.com/company/rightstone/', 'postings_url' => 'https://jobs.rightstone.com/' ],
            [ 'name' => 'Signature Consultants', 'slug' => 'signature-consultants', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Fort Lauderdale', 'state_id' => 10, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://www.sigconsult.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/signature-consultants/', 'postings_url' => 'https://dexian.com/jobs/' ],
            [ 'name' => 'SNI Companies', 'slug' => 'sni-companies', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '7751 Belfort Parkway, Suite 150', 'street2' => null, 'city' => 'Jacksonville', 'state_id' => 10, 'zip' => '32256', 'country_id' => 237, 'founded' => null, 'link' => 'https://www.snicompanies.com/', 'phone' => '(877) 875-4764', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/sni-companies/', 'postings_url' => 'https://www.snicompanies.com/jobs/' ],
            [ 'name' => 'Solomon Page', 'slug' => 'solomon-page', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '260 Madison Ave', 'street2' => null, 'city' => 'New York', 'state_id' => 33, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://solomonpage.com/', 'phone' => '(212) 403-6100', 'email' => null, 'linkedin_url' => null, 'postings_url' => 'https://opportunities.solomonpage.com/' ],
            [ 'name' => 'Sparks Group', 'slug' => 'sparks-group', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '77 Upper Rock Circle, Suite 101', 'street2' => null, 'city' => 'Rockville', 'state_id' => 21, 'zip' => '20850', 'country_id' => 237, 'founded' => null, 'link' => 'https://sparksgroupinc.com/', 'phone' => '(301) 279-2300', 'email' => null, 'linkedin_url' => null, 'postings_url' => 'https://jobs.sparksgroupinc.com/jobs' ],
            [ 'name' => 'Spherion', 'slug' => 'spherion', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Atlanta', 'state_id' => 11, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://www.spherion.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/spherion/', 'postings_url' => 'https://www.spherion.com/job-seekers/' ],
            [ 'name' => 'Synergis', 'slug' => 'synergis', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '1105 Lakewood Parkway, Suite 190', 'street2' => null, 'city' => 'Alpharetta', 'state_id' => 11, 'zip' => '30009', 'country_id' => 237, 'founded' => 1997, 'link' => 'https://www.synergishr.com/', 'phone' => '(770) 346-7200', 'email' => 'contact@synergishr.com', 'linkedin_url' => 'https://www.linkedin.com/company/synergis/', 'postings_url' => null ],
            [ 'name' => 'Synergy Staffing', 'slug' => 'synergy-staffing', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://www.synergystaffing.com/', 'phone' => null, 'email' => null, 'linkedin_url' => null, 'postings_url' => 'https://www1.jobdiva.com/portal/' ],
            [ 'name' => 'Systemart , LLC', 'slug' => 'systemart-llc', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '140 Littleton Road, Suite 303', 'street2' => null, 'city' => 'Parsippany', 'state_id' => 31, 'zip' => null, 'country_id' => 237, 'founded' => 1991, 'link' => 'https://www.systemart.com/', 'phone' => '(973) 917-4848+R44', 'email' => 'info@systemart.com', 'linkedin_url' => 'https://www.linkedin.com/company/systemart-llc/', 'postings_url' => 'https://systemart.com/careers/' ],
            [ 'name' => 'TEK Inspirations LLC', 'slug' => 'tek-inspirations-llc', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Frisco', 'state_id' => 44, 'zip' => null, 'country_id' => 237, 'founded' => 2014, 'link' => 'https://www.tekinspirations.com/', 'phone' => '(469) 518-9454', 'email' => 'info@tekinspirations.com', 'linkedin_url' => null, 'postings_url' => null ],
            [ 'name' => 'TEKSystems', 'slug' => 'teksystems', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => '7437 Race Road', 'street2' => null, 'city' => 'Hanover', 'state_id' => 21, 'zip' => '21076', 'country_id' => 237, 'founded' => 1983, 'link' => 'https://www.teksystems.com/', 'phone' => '(410) 540-7700', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/teksystems/', 'postings_url' => null ],
            [ 'name' => 'The Judge Group', 'slug' => 'the-judge-group', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://www.judge.com/', 'phone' => null, 'email' => null, 'linkedin_url' => null, 'postings_url' => 'https://www.judge.com/jobs/' ],
            [ 'name' => 'The Select Group', 'slug' => 'the-select-group', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '5540 Centerview Dr, Ste 204', 'street2' => 'PMB 29053', 'city' => 'Raleigh', 'state_id' => 34, 'zip' => '27606-8012', 'country_id' => 237, 'founded' => null, 'link' => 'https://www.selectgroup.com/', 'phone' => null, 'email' => 'info@selectgroup.com', 'linkedin_url' => null, 'postings_url' => null ],
            [ 'name' => 'Toptal', 'slug' => 'toptal', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => 2010, 'link' => 'https://www.toptal.com/', 'phone' => null, 'email' => 'support@toptal.com', 'linkedin_url' => 'https://www.linkedin.com/company/toptal/', 'postings_url' => null ],
            [ 'name' => 'TRC Staffing Services', 'slug' => 'trc-staffing-services', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://www.trcstaffing.com/', 'phone' => '(770) 392-1411', 'email' => null, 'linkedin_url' => null, 'postings_url' => 'https://www.trctalent.com/job_seekers/' ],
            [ 'name' => 'Trinity Park Talent', 'slug' => 'trinity-park-talent', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'founded' => 2019, 'link' => 'https://www.trinityparktalent.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/trinity-park-talent/', 'postings_url' => null ],
            [ 'name' => 'UnitedCode', 'slug' => 'unitedcode', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '8911 North Capital of Texas Highway', 'street2' => 'Suite 4200 #1151', 'city' => 'Austin', 'state_id' => 44, 'zip' => '78759', 'country_id' => 237, 'founded' => null, 'link' => 'https://unitedcode.net/', 'phone' => '(512) 706-9943', 'email' => 'info@unitedcode.net', 'linkedin_url' => 'https://www.linkedin.com/company/unitedcodeinc/', 'postings_url' => 'https://unitedcode.net/career/' ],
            [ 'name' => 'Vaco', 'slug' => 'vaco', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Brentwood', 'state_id' => 43, 'zip' => null, 'country_id' => 237, 'founded' => null, 'link' => 'https://www.vaco.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/vaco/', 'postings_url' => null ],
            [ 'name' => 'Vbeyond Corporation', 'slug' => 'vbeyond-corporation', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => 'Amwell Commons', 'street2' => '390 Amwell Road, Bldg #1, Suite #107', 'city' => 'Hillsborough', 'state_id' => 31, 'zip' => '08844', 'country_id' => 237, 'founded' => 2006, 'link' => 'https://www.vbeyond.com/', 'phone' => '(908) 854-0425', 'email' => 'usa@vbeyond.com', 'linkedin_url' => 'https://www.linkedin.com/company/vbeyond-corporation/', 'postings_url' => 'https://www.vbeyond.com/usa-openings/' ],
            [ 'name' => 'Volt', 'slug' => 'volt', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => '1455 Lincoln Parkway East', 'street2' => '8th Floor', 'city' => 'Atlanta', 'state_id' => 11, 'zip' => '30346', 'country_id' => 237, 'founded' => 1950, 'link' => 'https://www.volt.com', 'phone' => '(714) 921-8800', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/volt/', 'postings_url' => 'https://jobs.volt.com/' ],
            [ 'name' => 'Yoh, A Day & Zimmermann Company', 'slug' => 'yoh-a-day-and-zimmermann-cCompany', 'primary' => 0, 'national' => 1, 'international' => 0, 'street' => '1835 Market Street', 'street2' => null, 'city' => 'Philadelphia', 'state_id' => 39, 'zip' => '19103', 'country_id' => 237, 'founded' => 1940, 'link' => 'https://www.yoh.com', 'phone' => '(215) 656-2650', 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/yoh-a-day-&-zimmermann-company/', 'postings_url' => 'https://jobs.yoh.com/#/jobs' ],
            [ 'name' => 'CareerCircle', 'slug' => 'careercircle', 'primary' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Hanover', 'state_id' => 21, 'zip' => null, 'country_id' => 237, 'founded' => 2018, 'link' => 'https://www.careercircle.com/', 'phone' => null, 'email' => null, 'linkedin_url' => 'https://www.linkedin.com/company/careercircle/', 'postings_url' => 'https://www.careercircle.com/jobs' ],
        ];

        foreach ($data as $i=>$row) {
            echo PHP_EOL . $i . ') ' . $row['name'];

            $row['created_at'] = date('Y-m-d H:i:s');;
            $row['updated_at'] = date('Y-m-d H:i:s');;

            DB::connection('career_db')->table('recruiters')->insert($row);
        }

        echo PHP_EOL . 'Migration file complete.';
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
