<?php

use App\Models\Career\JobBoard;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $data = [
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 9, 'name' => 'Actalent', 'slug' => 'actalent', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.actalentservices.com/', 'linkedin_url' => 'https://www.linkedin.com/company/actalentservices/', 'jobs_url' => 'https://www.actalentservices.com/en/careers', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 1, 'specialties' => 'Engineering|Science|Talent Solutions|Services' ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 10, 'name' => 'Addison Group', 'slug' => 'addison-group', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => '225 W Randolph, Suite 1900', 'street2' => null, 'city' => 'Chicago', 'state_id' => 14, 'zip' => '60606', 'country_id' => 237, 'link' => 'https://www.addisongroup.com/', 'linkedin_url' => 'https://www.linkedin.com/groups/2508146/', 'jobs_url' => 'https://addisongroup.com/jobs/', 'phone' => '(312) 424-0300', 'email' => 'mediarelations@addisongroup.com', 'recruiter_industry_id' => null, 'specialties' => 'Information Technology|Services' ],
            [ 'primary' => 0, 'founded' => 1996, 'recruiter_id' => 11, 'name' => 'Adecco', 'slug' => 'adecco', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.adeccousa.com/', 'linkedin_url' => 'https://www.linkedin.com/company/adecco/', 'jobs_url' => 'https://www.adecco.com/en-us/job-search', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Workforce solutions|HR services|Human resources|Staffing|Recruiting|Recruitment' ],
            [ 'primary' => 0, 'founded' => 1983, 'recruiter_id' => 12, 'name' => 'Aerotek', 'slug' => 'aerotek', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => '7301 Parkway Drive South', 'street2' => null, 'city' => 'Hanover', 'state_id' => 21, 'zip' => '21703', 'country_id' => 237, 'link' => 'https://www.aerotek.com/', 'linkedin_url' => 'https://www.linkedin.com/company/aerotek/', 'jobs_url' => 'https://jobs.aerotek.com/us/en', 'phone' => '(410) 694-5100', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Recruiting|Workforce Management|Staffing Agency|Job Agency|Workforce Solutions|Light Industrial|Skilled Trades|Construction|Facilities|Maintenance|Manufacturing|Production|Warehouse|Distribution|Aviation|Logistics|Automotive|Preventative Maintenance|Asset Optimization|Energy|Life Sciences|Automation|Robotics' ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 13, 'name' => 'Akkodis', 'slug' => 'akkodis', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.akkodis.com/', 'linkedin_url' => 'https://www.linkedin.com/company/akkodis/', 'jobs_url' => 'https://www.akkodis.com/en-us/careers/job-results', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 6, 'specialties' => null ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 14, 'name' => 'Allegis Group', 'slug' => 'allegis-group', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.allegisgroup.com/', 'linkedin_url' => null, 'jobs_url' => 'https://careers-allegisgroup.icims.com/jobs/search', 'phone' => null, 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 15, 'name' => 'Apex Systems', 'slug' => 'apex-systems', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '4400 Cox Road, Suite 200', 'street2' => null, 'city' => 'Glen Allen', 'state_id' => 47, 'zip' => '23060', 'country_id' => 237, 'link' => 'https://www.apexsystems.com', 'linkedin_url' => 'https://www.linkedin.com/company/apex-systems/', 'jobs_url' => 'https://www.apexsystems.com/search-results-usa', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 6, 'specialties' => 'Workforce Solutions|Consulting Services|Career Resources|IT Services' ],
            [ 'primary' => 0, 'founded' => 1964, 'recruiter_id' => 16, 'name' => 'AppleOne Employment Services', 'slug' => 'appleone-employment-services', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Glendale', 'state_id' => 5, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.appleone.com/', 'linkedin_url' => 'https://www.linkedin.com/company/appleone/', 'jobs_url' => 'https://www.appleone.com/CareerSearch/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Temporary Staffing|Direct Hire Staffing|Temp-to-Hire Staffing|Project Staffing|Managed Services|Government Staffing Solutions|Careers|Employment Agency|Career Counseling|Staffing|Hiring|Recruiting|Job Posting|Staffing Solutions|Social Recruiting|Finance' ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 18, 'name' => 'Aston Carter', 'slug' => 'aston-carter', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Hanover', 'state_id' => 21, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.astoncarter.com/', 'linkedin_url' => 'https://www.linkedin.com/company/aston-carter/', 'jobs_url' => 'https://careers.astoncarter.com/us/en', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Accounting and Finance|Business Support|Strategy|Change & Transformation|Operations|Banking and Financial Services|Administrative|Human Resources|Talent Acquisition|Procurement|Supply Chain' ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 19, 'name' => 'Beacon Hill Staffing Group', 'slug' => 'beacon-hill-staffing-group', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '20 Ashburton Pl', 'street2' => null, 'city' => 'Boston', 'state_id' => 22, 'zip' => '02108', 'country_id' => 237, 'link' => 'https://bhsg.com/', 'linkedin_url' => null, 'jobs_url' => 'https://bhsg.com/jobs/', 'phone' => '(617) 326-4000', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Staffing|Recruiting|Professional Services|Consulting Solutions' ],
            [ 'primary' => 0, 'founded' => 1989, 'recruiter_id' => 20, 'name' => 'Elwood Staffing', 'slug' => 'elwood-staffing', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '4111 Central Avenue', 'street2' => null, 'city' => 'Cincinnati', 'state_id' => 36, 'zip' => '47203', 'country_id' => 237, 'link' => 'https://www.elwoodstaffing.com/', 'linkedin_url' => 'https://www.linkedin.com/company/belflex-staffing-network/about/', 'jobs_url' => 'https://www.elwoodstaffing.com/jobsearch/', 'phone' => '(812) 372-6200', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Flexible staffing solutions|Temporary/Contract Personnel|Contingent Workforce Management|Peak Season/Heavy Volume Staffing|Direct Hire|Recruitment Process Outsourcing|Light Industrial Staffing Solutions' ],
            [ 'primary' => 0, 'founded' => 2000, 'recruiter_id' => 22, 'name' => 'Brooksource', 'slug' => 'brooksource', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '6215 N College Ave.', 'street2' => null, 'city' => 'Indianapolis', 'state_id' => 15, 'zip' => '46220', 'country_id' => 237, 'link' => 'https://www.brooksource.com/', 'linkedin_url' => 'https://www.linkedin.com/company/brooksource/', 'jobs_url' => 'https://jobs.brooksource.com/jobs/', 'phone' => '(317) 475-0079', 'email' => null, 'recruiter_industry_id' => 6, 'specialties' => 'Application Development|Project Management|Business Analysis|Quality Assurance|Network & System Infrastructure|Database Development|Database Administration|Enterprise Resource Planning|Systems Integration|Technology Planning|Staff Augmentation|recruiting|staffingProfessional Services|Workforce Transformation|IT Consulting|Microsoft Partner|AWS Services|Salesforce|Cloud Journey|Application Integration|Data Analytics|Security Application Development|Tableau|Google Cloud|Snowflake|Information Technology|Staffing Services|IT Infrastructure|Cybersecurity|Enterprise Applications|Digital Experience|Design Engineering|Electrical Engineering|Mechanical Engineering|Embdedded Engineering' ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 23, 'name' => 'CodeImpact B.V.', 'slug' => 'codeimpact-bv', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => 'Teggert 140', 'street2' => null, 'city' => 'Voerendaal', 'state_id' => null, 'zip' => '6367XR ', 'country_id' => 156, 'link' => 'https://codeimpact.nl/', 'linkedin_url' => null, 'jobs_url' => 'https://codeimpact.nl/nl/jobs/', 'phone' => '+3 (185) 225-D90504', 'email' => 'info@codeimpact.nl', 'recruiter_industry_id' => null, 'specialties' => null ],
            [ 'primary' => 0, 'founded' => 1996, 'recruiter_id' => 24, 'name' => 'Collabera', 'slug' => 'collabera', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Basking Ridge', 'state_id' => 31, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.collabera.com/', 'linkedin_url' => 'https://www.linkedin.com/company/collabera/', 'jobs_url' => 'https://collabera.com/job-search/', 'phone' => '(973) 889-5200', 'email' => ' info@collabera.com', 'recruiter_industry_id' => 5, 'specialties' => 'Total Talent Solutions|Tech Consulting Services|Advisory and Implementation|Direct Hire Recruitment|Software Engineering Solutions|Platform Modernization and Integration|Data Modernization|Customized Training and Talent Development|Project-Based Services|Talent Development|Cloud Enablement and Migration' ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 25, 'name' => 'CSS Tec', 'slug' => 'css-tec', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '1400 N. Providence Rd', 'street2' => 'Building 2, Suite 1205', 'city' => 'Media', 'state_id' => 29, 'zip' => null, 'country_id' => 237, 'link' => 'http://www.css-tec.com', 'linkedin_url' => 'https://www.linkedin.com/company/css-tec/', 'jobs_url' => 'https://careers.css-tec.com/', 'phone' => '(610) 565-4300', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Applications|Data Analytics|Digitial|Quality Assurance|Testing|Infrastructure and Support|PMO|IT Staffing|Technical Staffing' ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 26, 'name' => 'DataTeams', 'slug' => 'datateams', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Bengaluru, Karnataka', 'state_id' => null, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.datateams.ai/', 'linkedin_url' => 'https://www.linkedin.com/company/data-teams/', 'jobs_url' => 'https://datateams.zohorecruit.in/jobs/Careers', 'phone' => '+91 (974) 200-Q166911', 'email' => 'connect@datateams.ai', 'recruiter_industry_id' => 6, 'specialties' => null ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 27, 'name' => 'DISYS', 'slug' => 'disys', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => '8270 Greensboro Drive, Suite 1000', 'street2' => null, 'city' => 'McLean', 'state_id' => 47, 'zip' => '22102', 'country_id' => 237, 'link' => 'https://www.disys.com/', 'linkedin_url' => 'https://www.linkedin.com/company/disys/', 'jobs_url' => 'https://dexian.com/jobs/', 'phone' => '(703) 752-7900', 'email' => '', 'recruiter_industry_id' => 6, 'specialties' => 'Information Technology|Information Technology Services|Staffing|Recruiting|Project Consulting|BPO|RPO|Payrolling|Non-IT Staffing|Professional Staffing|Recruiting for Recruiters (R4R)|Clinical Staffing|Scientific Staffing|Engineering Staffing|Managed Services|Financial Staffing|Creative Staffing|Insurance Staffing|IT Staffing|Mortgage Staffing|Admin/Clerical Staffing' ],
            [ 'primary' => 0, 'founded' => 1998, 'recruiter_id' => 28, 'name' => 'Diversant LLC', 'slug' => 'diversant-llc', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => '1455 Lincoln Parkway East, 8th Floor', 'street2' => null, 'city' => 'Atlanta', 'state_id' => 11, 'zip' => '30346', 'country_id' => 237, 'link' => 'https://innovasolutions.com/', 'linkedin_url' => 'https://www.linkedin.com/company/diversant-llc/', 'jobs_url' => 'https://innovasolutions.com/', 'phone' => '(770) 493-5588', 'email' => null, 'recruiter_industry_id' => 6, 'specialties' => 'Business|Application Services|Data Sciences|Cloud Enablement|Artificial Intelligence|Machine Learning|Intelligent Process Automation|Consulting Services|Healthcare Business Solutions|Talent Solutions|Workforce Management Solutions|Digital Transformation|Product Engineering Services' ],
            [ 'primary' => 0, 'founded' => 2020, 'recruiter_id' => 30, 'name' => 'Emergent Staffing', 'slug' => 'emergent-staffing', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'St. Paul', 'state_id' => 24, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.emergentstaffing.net/', 'linkedin_url' => 'https://www.linkedin.com/company/emergent-staffing/', 'jobs_url' => 'https://www.emergentstaffing.net/job-seekers/open-jobs/', 'phone' => '(612) 217-747', 'email' => 'hello@emergentstaffing.net', 'recruiter_industry_id' => 8, 'specialties' => 'IT Staffing Services|IT Recruiting|IT Permanent Placement|Staff Augmentation|IT Temporary Talent|Recruitment Process Outsourcing' ],
            [ 'primary' => 0, 'founded' => 1997, 'recruiter_id' => 31, 'name' => 'Employbridge', 'slug' => 'employbridge', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '1845 Satellite Blvd, Suite 300', 'street2' => null, 'city' => 'Duluth', 'state_id' => 11, 'zip' => '30097', 'country_id' => 237, 'link' => 'https://www.employbridge.com/', 'linkedin_url' => 'https://www.linkedin.com/company/employbridge/', 'jobs_url' => 'https://www.employbridge.com/job-search', 'phone' => '(888) 381-7248', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Recruitment|Manufacturing|Professional|Logistics|Distribution|Drivers|Energy|Financial|Medical|Accounting|Staffing|Hiring' ],
            [ 'primary' => 0, 'founded' => 1978, 'recruiter_id' => 32, 'name' => 'Epitec', 'slug' => 'epitec', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => '26555 Evergreen Rd., Suite 1700', 'street2' => null, 'city' => 'Southfield', 'state_id' => 23, 'zip' => '48076', 'country_id' => 237, 'link' => 'https://epitec.com/', 'linkedin_url' => 'https://www.linkedin.com/company/epitec/', 'jobs_url' => 'https://epitec.com/jobs-at-epitec/', 'phone' => '(248) 353-6800', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'IT Staffing and Consulting|Engineering|Professional Staffing|Finance and Accounting|Administrative|Automotive|Consumer Products|Government|Healthcare|Insurance|Manufacturing|Contract|Direct Hire|Executive Search|Statement of Work|IT|Accounting|Finance|Sales|Marketing|Professional Services|Automotive|Oil and Gas|Technology|Transportation|Utilities|Recruiting|Employer of Record' ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 33, 'name' => 'Experis', 'slug' => 'experis', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Milwaukee', 'state_id' => 50, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.experis.com/', 'linkedin_url' => 'https://www.linkedin.com/company/experis/', 'jobs_url' => 'https://www.experis.com/en/search', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 6, 'specialties' => 'IT|Technology|AI|Business Transformation|Software and Cloud Engineering|Strategy and Transformation|DevOps and DevSecOps|Quality Assurance and Engineering|Data and Anatlytics|Service Management|Tech Talent' ],
            [ 'primary' => 0, 'founded' => 1983, 'recruiter_id' => 34, 'name' => 'Express Employment Professionals - Irvine, CA', 'slug' => 'express-employment-professionals-irvine-ca', 'local' => 1, 'regional' => 0, 'national' => 0, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Irvine', 'state_id' => 5, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.expresspros.com/IrvineCA', 'linkedin_url' => 'https://www.linkedin.com/company/express-irvine-ca/', 'jobs_url' => 'https://www.expresspros.com/us-california-irvine/job-seekers/job-openings', 'phone' => '(949) 583-7400', 'email' => '', 'recruiter_industry_id' => 8, 'specialties' => 'Skilled Trades Staffing|Light Industrial Staffing|Commercial Staffing|Professional Staffing|Professional Recruiting' ],
            [ 'primary' => 0, 'founded' => 2004, 'recruiter_id' => 36, 'name' => 'Frontline Source Group', 'slug' => 'frontline-source-group', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Dallas', 'state_id' => 44, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.frontlinesourcegroup.com/technology-it.html', 'linkedin_url' => 'https://www.linkedin.com/company/frontline-source-group/', 'jobs_url' => 'https://jobs.frontlinesourcegroup.com/', 'phone' => '(214) 760-7700', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Temporary Staffing|Staffing Agency|Recruiting|Staffing|Accounting|Finance|Technology IT|Human Resources HR|Administrative|Customer Service|Engineering|Oil & Gas|Accounting Recruiters|IT Staffing|Call Center|executive recruiter|Executive Staffing|professional services|Grocery|Life Sciences|Legal|Dental' ],
            [ 'primary' => 0, 'founded' => 2010, 'recruiter_id' => 37, 'name' => 'Frontline Source Group Holdings', 'slug' => 'frontline-source-group-holdings', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '2001 Ross Ave Suite #700-161', 'street2' => null, 'city' => 'Dallas', 'state_id' => 44, 'zip' => '75201', 'country_id' => 237, 'link' => 'https://www.frontlinesourcegroupholdings.com/', 'linkedin_url' => 'https://www.linkedin.com/company/frontline-source-group-holdings/', 'jobs_url' => 'https://jobs.dfwhr.com/', 'phone' => '(214) 742-1300', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => null ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 38, 'name' => 'Genuent', 'slug' => 'genuent', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.genuent.com/', 'linkedin_url' => null, 'jobs_url' => 'https://www.inspyrsolutions.com/job-search/#opportunities', 'phone' => '(844) 693-3947', 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            [ 'primary' => 0, 'founded' => 2020, 'recruiter_id' => 39, 'name' => 'Go Carpathian', 'slug' => 'go-carpathian', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'link' => 'https://gocarpathian.com/', 'linkedin_url' => 'https://www.linkedin.com/company/go-carpathian-recruiting/', 'jobs_url' => null, 'phone' => null, 'email' => 'hello@gocarpathian.com', 'recruiter_industry_id' => 4, 'specialties' => null ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 41, 'name' => 'Hays', 'slug' => 'hays', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'London', 'state_id' => null, 'zip' => null, 'country_id' => 234, 'link' => 'https://www.hays.com/', 'linkedin_url' => 'https://www.linkedin.com/company/hays/', 'jobs_url' => 'https://www.hays.com/job-search', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Recruitment|Staffing solutions|Resourcing|Career transition|Recruitment Process Outsourcing (RPO)|Onboarding|contract recruitment|Contracting jobs|Hiring|Recruiting|Workforce management|Managed Service Programme' ],
            [ 'primary' => 0, 'founded' => 2021, 'recruiter_id' => 42, 'name' => 'Haystack', 'slug' => 'haystack', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Newcastle upon Tyne', 'state_id' => null, 'zip' => null, 'country_id' => 234, 'link' => 'https://haystackapp.io/', 'linkedin_url' => 'https://www.linkedin.com/company/wearehaystack/', 'jobs_url' => 'https://haystackapp.io/tech-talent', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => null ],
            [ 'primary' => 0, 'founded' => 2001, 'recruiter_id' => 44, 'name' => 'Insight Global', 'slug' => 'insight-global', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Atlanta', 'state_id' => 11, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.linkedin.com/company/insight-global/', 'linkedin_url' => 'https://www.linkedin.com/company/insight-global/', 'jobs_url' => 'https://insightglobal.com/jobs/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 1, 'specialties' => 'Consulting|Talent Services|Staffing|International Staffing' ],
            [ 'primary' => 0, 'founded' => 1989, 'recruiter_id' => 45, 'name' => 'Motion Recruitment', 'slug' => 'motion-recruitment', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '185 Dartmouth St., Suite 1105', 'street2' => null, 'city' => 'Boston', 'state_id' => 22, 'zip' => '02116', 'country_id' => 237, 'link' => 'https://motionrecruitment.com/', 'linkedin_url' => 'https://www.linkedin.com/company/jobspring-partners/', 'jobs_url' => 'https://motionrecruitment.com/tech-jobs', 'phone' => '(617) 266-6200', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'technology jobs|IT jobs|developer jobs|engineering jobs|software jobs|networking jobs|open source jobs|job search|job postings|Boston|New York|Philadelphia|Washington|Los Angeles|San Francisco|San Jose|Orange County|Silicon Valley' ],
            [ 'primary' => 0, 'founded' => 1946, 'recruiter_id' => 46, 'name' => 'Kelly Services', 'slug' => 'kelly-services', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Troy', 'state_id' => 23, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.kellyservices.com/', 'linkedin_url' => 'https://www.linkedin.com/company/kellyservices/', 'jobs_url' => 'https://www.mykelly.com/', 'phone' => '(800) KELLY-01', 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            [ 'primary' => 0, 'founded' => 1962, 'recruiter_id' => 47, 'name' => 'Kforce', 'slug' => 'kforce', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => '1150 Assembly Drive, Suite 500', 'street2' => null, 'city' => 'Tampa', 'state_id' => 10, 'zip' => '33607', 'country_id' => 237, 'link' => 'https://www.kforce.com/', 'linkedin_url' => 'https://www.linkedin.com/company/kforce/', 'jobs_url' => 'https://www.kforce.com/find-work/search-jobs/', 'phone' => '(877) 453-6723', 'email' => null, 'recruiter_industry_id' => 6, 'specialties' => 'Finance & Accounting|Technology|Healthcare|Communication' ],
            [ 'primary' => 0, 'founded' => 1998, 'recruiter_id' => 48, 'name' => 'LaSalle Network', 'slug' => 'lasalle-network', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => '200 N LaSalle St', 'street2' => null, 'city' => 'Chicago', 'state_id' => 14, 'zip' => '60601', 'country_id' => 237, 'link' => 'https://www.thelasallenetwork.com/', 'linkedin_url' => 'https://www.linkedin.com/company/lasalle-network/', 'jobs_url' => 'https://www.thelasallenetwork.com/job-search/', 'phone' => '(312) 419-1700​', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Staffing|Recruiting|Accounting and Finance|Technology|Administrative|Call Center|Human Resources|Executive Search|Sales|Supply Chain|Healthcare Revenue Cycle|Marketing|Management Resources' ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 49, 'name' => 'LHH', 'slug' => 'lhh', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Jacksonville', 'state_id' => 10, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.lhh.com/', 'linkedin_url' => 'https://www.linkedin.com/company/lhhworldwide/', 'jobs_url' => 'https://www.lhh.com/en-us/search-jobs', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 4, 'specialties' => 'Leadership Development|Change Management|Employee Engagement|Recruitment|Workforce Advisory|Career Management & Mobility|Workforce Insights' ],
            [ 'primary' => 0, 'founded' => 1970, 'recruiter_id' => 50, 'name' => 'Lucas Group', 'slug' => 'lucas-group', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Los Angeles', 'state_id' => 5, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.kornferry.com/about-us/our-story/lucas-group', 'linkedin_url' => 'https://www.linkedin.com/company/lucas-group/', 'jobs_url' => 'https://www.kornferry.com/careers/candidates', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Recruiting|Consulting' ],
            [ 'primary' => 0, 'founded' => 1982, 'recruiter_id' => 51, 'name' => 'Major, Lindsey, & Africa', 'slug' => 'major-lindsey-and-africa', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => '7437 Race Rd', 'street2' => null, 'city' => 'Hanover', 'state_id' => 21, 'zip' => '21076', 'country_id' => 237, 'link' => 'https://careers.mlaglobal.com/', 'linkedin_url' => 'https://www.linkedin.com/company/major-lindsey-africa/', 'jobs_url' => 'https://careers.mlaglobal.com/us/en', 'phone' => '(877) 482-1010', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Permanent Placement|Partner|Associate|General Counsel|Corporate Counsel|Law Firm Management|New Market Entry|Legal Staffing|Executive Coaching|Maturity Assessment|Interim Legal Talent|Alternative Legal Service Provider' ],
            [ 'primary' => 0, 'founded' => 1948, 'recruiter_id' => 52, 'name' => 'Manpower', 'slug' => 'manpower', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.manpower.com/', 'linkedin_url' => 'https://www.linkedin.com/company/manpower-/', 'jobs_url' => 'https://www.manpower.com/en/search', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Interim Recruitment|Permanent Recruitment|Workforce Management|Contingent Recruitment|Workforce Trends|Hiring|Employment|Staffing|Recruiting|Career Guidance' ],
            [ 'primary' => 0, 'founded' => 1975, 'recruiter_id' => 53, 'name' => 'MarketSource', 'slug' => 'marketsource', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '11700 Great Oaks Way, Suite 100', 'street2' => null, 'city' => 'Alpharetta', 'state_id' => 11, 'zip' => '30022', 'country_id' => 237, 'link' => 'https://www.marketsource.com/', 'linkedin_url' => 'https://www.linkedin.com/company/marketsource-inc/', 'jobs_url' => 'https://applyatmarketsource-msc.icims.com/jobs/search', 'phone' => '(770) 674-5000', 'email' => null, 'recruiter_industry_id' => 1, 'specialties' => 'Sales Solutions|Outsourced Sales Teams|Sales Team Training|Go To Market Expertise|Contact Center|Inside Sales|Field Sales|Retail Sales|Account Management|Channel Sales|Customer Care|Patient Engagement|Assisted Sales|Retail Brand Advocacy|Auto F&I Development|Recall|Direct Sales|Customer Engagement Center|Repair Optimization and Compliance' ],
            [ 'primary' => 0, 'founded' => 2000, 'recruiter_id' => 54, 'name' => 'Mondo', 'slug' => 'mondo', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'New York', 'state_id' => null, 'zip' => null, 'country_id' => 237, 'link' => 'https://mondo.com/', 'linkedin_url' => 'https://www.linkedin.com/company/mondo/', 'jobs_url' => 'https://mondo.com/get-hired/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'IT Staffing|Tech Staffing|Digital Marketing Staffing' ],
            [ 'primary' => 0, 'founded' => 1977, 'recruiter_id' => 56, 'name' => 'PDS Tech Commercial, Inc.', 'slug' => 'pds-tech-commercial-inc', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Irving', 'state_id' => 44, 'zip' => null, 'country_id' => 237, 'link' => 'https://pdstech.com/', 'linkedin_url' => 'https://www.linkedin.com/company/pds-tech/', 'jobs_url' => 'https://www.pdstech.com/job-search', 'phone' => '(800) 270-4737', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Recruiting|Staffing|Contingent Staffing Services|Engineering Services|Hiring Veterans|Maritime|Skilled Trades|Aviation|Aerospace|Energy Staffing|Veteran Staffing|Manufacturing' ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 57, 'name' => 'Pearl Talent', 'slug' => 'pearl-talent', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'New York', 'state_id' => 33, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.pearltalent.com/', 'linkedin_url' => 'https://www.linkedin.com/company/pearltalent/', 'jobs_url' => 'https://www.pearltalent.com/remote-jobs-directory', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => null ],
            [ 'primary' => 0, 'founded' => 1996, 'recruiter_id' => 58, 'name' => 'Pinnacle Group', 'slug' => 'pinnacle-group', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => '10670 N. Central Expy, Suite 600', 'street2' => null, 'city' => 'Dallas', 'state_id' => 44, 'zip' => '75231', 'country_id' => 237, 'link' => 'https://www.pinnacle1.com/', 'linkedin_url' => null, 'jobs_url' => 'https://jobs.pinnacle1.com/', 'phone' => '(214) 740-2424', 'email' => 'mspinquiries@pinnacle1.com', 'recruiter_industry_id' => null, 'specialties' => null ],
            [ 'primary' => 0, 'founded' => 1978, 'recruiter_id' => 59, 'name' => 'PrideStaff', 'slug' => 'pridestaff', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '7535 North Palm Avenue, Suite 101', 'street2' => null, 'city' => 'Fresno', 'state_id' => 5, 'zip' => '93711', 'country_id' => 237, 'link' => 'https://www.pridestaff.com/', 'linkedin_url' => 'https://www.linkedin.com/company/pridestaff/', 'jobs_url' => 'https://jobs.pridestaff.com/', 'phone' => '(800) 774-3316', 'email' => 'info@pridestaff.com', 'recruiter_industry_id' => 8, 'specialties' => 'temporary|temporary-to-hire|temp|direct hire|recruiter|staffing|recruiting|career development|resume|accounting|finance|light industrial|b2b|employment|jobs|management' ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 60, 'name' => 'Staffmark', 'slug' => 'staffmark', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '191 Rosa Parks Street, 10th Floor', 'street2' => null, 'city' => 'Cincinnati', 'state_id' => 36, 'zip' => '45202', 'country_id' => 237, 'link' => 'https://staffmark.com/', 'linkedin_url' => 'https://www.linkedin.com/company/staffmark/', 'jobs_url' => 'https://www.linkedin.com/company/staffmark/', 'phone' => '(866) 765-7544', 'email' => 'AskHR@staffmarkgroup.com', 'recruiter_industry_id' => 8, 'specialties' => 'Accounting and Finance|Administrative and Office|Call Center|Electronics|Engineering|Health Care and Medical Office|Industrial|Information Technology|Legal|Logistics|Mortgage and Transportation' ],
            [ 'primary' => 0, 'founded' => 1996, 'recruiter_id' => 62, 'name' => 'ResourceMFG', 'slug' => 'resourcemfg', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Atlanta', 'state_id' => 11, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.resourcemfg.com/', 'linkedin_url' => 'https://www.linkedin.com/company/resourcemfg/', 'jobs_url' => 'https://www.resourcemfg.com/jobs/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Manufacturing|Staffing|Workforce Management|Employment' ],
            [ 'primary' => 0, 'founded' => 1996, 'recruiter_id' => 63, 'name' => 'RightStone', 'slug' => 'rightstone', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '6029 Belt Line Rd, Suite 260', 'street2' => null, 'city' => 'Plano', 'state_id' => 44, 'zip' => '75254', 'country_id' => 237, 'link' => 'https://www.rightstone.com/', 'linkedin_url' => 'https://www.linkedin.com/company/rightstone/', 'jobs_url' => 'https://jobs.rightstone.com/', 'phone' => '(972) 895-2555', 'email' => 'info@rightstone.com', 'recruiter_industry_id' => 8, 'specialties' => null ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 64, 'name' => 'Signature Consultants', 'slug' => 'signature-consultants', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Fort Lauderdale', 'state_id' => 10, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.sigconsult.com/', 'linkedin_url' => 'https://www.linkedin.com/company/signature-consultants/', 'jobs_url' => 'https://dexian.com/jobs/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Information Technology|Application Development|Web Development|Staffing and Consulting|ERP/SAP' ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 65, 'name' => 'SNI Companies', 'slug' => 'sni-companies', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '7751 Belfort Parkway, Suite 150', 'street2' => null, 'city' => 'Jacksonville', 'state_id' => 10, 'zip' => '32256', 'country_id' => 237, 'link' => 'https://www.snicompanies.com/', 'linkedin_url' => 'https://www.linkedin.com/company/sni-companies/', 'jobs_url' => 'https://www.snicompanies.com/jobs/', 'phone' => '(877) 875-4764', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Finance|Accounting|Tax|Financial Services|Technology|Legal|Banking|Staffing|Recruiting' ],
            [ 'primary' => 0, 'founded' => 1990, 'recruiter_id' => 66, 'name' => 'Solomon Page', 'slug' => 'solomon-page', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '260 Madison Ave', 'street2' => null, 'city' => 'New York', 'state_id' => 33, 'zip' => null, 'country_id' => 237, 'link' => 'https://solomonpage.com/', 'linkedin_url' => 'https://www.linkedin.com/company/solomon-page-group/', 'jobs_url' => 'https://opportunities.solomonpage.com/', 'phone' => '(212) 403-6000', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Temporary Staffing|Contract Staffing|Temp-to-Perm|Direct Hire|Executive Search|Retained Search|Contingent Search|Accounting|Financial Services|Administrative|Clinical Research|Creative|Marketing|Fashion|Beauty|Healthcare|Human Resources|Hospitality|Legal|Technology|Engineering' ],
            [ 'primary' => 0, 'founded' => 2008, 'recruiter_id' => 67, 'name' => 'Sparks Group', 'slug' => 'sparks-group', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '77 Upper Rock Circle, Suite 101', 'street2' => null, 'city' => 'Rockville', 'state_id' => 21, 'zip' => '20850', 'country_id' => 237, 'link' => 'https://sparksgroupinc.com/', 'linkedin_url' => 'https://www.linkedin.com/company/sparks-group1/', 'jobs_url' => 'https://jobs.sparksgroupinc.com/jobs', 'phone' => '(301) 279-2300', 'email' => null, 'recruiter_industry_id' => 9, 'specialties' => null ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 68, 'name' => 'Spherion', 'slug' => 'spherion', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Atlanta', 'state_id' => 11, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.spherion.com/', 'linkedin_url' => 'https://www.linkedin.com/company/spherion/', 'jobs_url' => 'https://www.spherion.com/job-seekers/', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Administrative Talent Staffing|Temporary Staffing|Light Industrial|Recruiting for Full Time Employees|Clerical Staffing|Temp-To-Hire' ],
            [ 'primary' => 0, 'founded' => 1997, 'recruiter_id' => 69, 'name' => 'Synergis', 'slug' => 'synergis', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '1105 Lakewood Parkway, Suite 190', 'street2' => null, 'city' => 'Alpharetta', 'state_id' => 11, 'zip' => '30009', 'country_id' => 237, 'link' => 'https://www.synergishr.com/', 'linkedin_url' => 'https://www.linkedin.com/company/synergis/', 'jobs_url' => 'https://www.synergishr.com/search-jobs/', 'phone' => '(770) 346-7200', 'email' => 'contact@synergishr.com', 'recruiter_industry_id' => 8, 'specialties' => 'Workforce Management Solutions|Recruitment Services|Contract Staffing|Payroll Services|Vendor Management|Project Management Support|Learning & Development Talent|IT & Technical Staffing|Contingent Workforce Strategy' ],
            [ 'primary' => 0, 'founded' => 2007, 'recruiter_id' => 70, 'name' => 'Synergy Staffing', 'slug' => 'synergy-staffing', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => 'Pittsburgh', 'state_id' => 39, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.synergystaffing.com/', 'linkedin_url' => 'https://www.linkedin.com/company/synergystaffing/', 'jobs_url' => 'https://www1.jobdiva.com/portal/', 'phone' => '(412) 904-5300', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Information Technology Recruiting|Professionals Recruiting|recruiting|technology|staffing|career matching|candidate placement' ],
            [ 'primary' => 0, 'founded' => 1999, 'recruiter_id' => 71, 'name' => 'Systemart , LLC', 'slug' => 'systemart--llc', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '140 Littleton Road, Suite 303', 'street2' => null, 'city' => 'Parsippany', 'state_id' => 31, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.systemart.com/', 'linkedin_url' => 'https://www.linkedin.com/company/systemart-llc/', 'jobs_url' => 'https://systemart.com/careers/', 'phone' => '(973) 917-4848', 'email' => 'info@systemart.com', 'recruiter_industry_id' => 8, 'specialties' => 'Software Development|BPO|Staffing (IT|Engineering|Finance|HR|Healthcare)|Web & Mobile Applications|Remote Infrastructure Support|Risk Management|Professional Placement|Finance & Accounting|BI & Analytic|HRM (Human Resource Management)|Cloud Applications|Application Data Migration|Temporary Staffing|Workforce Business Solution|Minority Business Enterprise|Staff Augmentation Service|Staffing Services|Recruitment Agency|Recruitment Services|Staffing Agency|RPO services' ],
            [ 'primary' => 0, 'founded' => 1970, 'recruiter_id' => 74, 'name' => 'The Judge Group', 'slug' => 'the-judge-group', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Wayne', 'state_id' => 39, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.judge.com/', 'linkedin_url' => 'https://www.linkedin.com/company/the-judge-group/', 'jobs_url' => 'https://www.judge.com/jobs/', 'phone' => '(800) 650-0035', 'email' => null, 'recruiter_industry_id' => 1, 'specialties' => 'Technology Solutions|Talent Solutions|Learning Solutions|IT Recruiting|Consulting|Executive Search|Direct Hire|IT Staffing|Recruiting|Engineering Staffing|Healthcare Staffing|IT Executive Search|Information Technology Staffing|Professional Staffing|IT Consulting|Food and Beverage Manufacturing|Permanent Placement|Healthcare Consulting|Training|Information Technology' ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 77, 'name' => 'TRC Staffing Services', 'slug' => 'trc-staffing-services', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => null, 'street2' => null, 'city' => null, 'state_id' => null, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.trcstaffing.com/', 'linkedin_url' => null, 'jobs_url' => 'https://www.trctalent.com/job_seekers/', 'phone' => '(770) 392-1411', 'email' => null, 'recruiter_industry_id' => null, 'specialties' => null ],
            [ 'primary' => 0, 'founded' => null, 'recruiter_id' => 79, 'name' => 'UnitedCode', 'slug' => 'unitedcode', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '8911 North Capital of Texas Highway', 'street2' => 'Suite 4200 #1151', 'city' => 'Austin', 'state_id' => 44, 'zip' => '78759', 'country_id' => 237, 'link' => 'https://unitedcode.net/', 'linkedin_url' => 'https://www.linkedin.com/company/unitedcodeinc/', 'jobs_url' => 'https://unitedcode.net/career/', 'phone' => '(512) 706-9943', 'email' => 'info@unitedcode.net', 'recruiter_industry_id' => 7, 'specialties' => 'Engineering Skills Vetting|Talent Acquisition|Soft and Hard Skills Testing|IT Staff Augmentation|Nearshore Staffing|Offshore Staffing|Global Talent Sourcing|Technical Recruiting|HR Software|Tech Recruiting Tools|Contract |Contract-to-hire|Full-time developers hiring support|Software Developers |Dedicated Developers Team|Remote Engineering Teams|Software Development Outsourcing|Software Developers Team Scaling|Engineering Recruitment|Developer Hiring' ],
            [ 'primary' => 0, 'founded' => 2006, 'recruiter_id' => 81, 'name' => 'Vbeyond Corporation', 'slug' => 'vbeyond-corporation', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => 'Amwell Commons', 'street2' => '390 Amwell Road, Bldg #1, Suite #107', 'city' => 'Hillsborough', 'state_id' => 31, 'zip' => '08844', 'country_id' => 237, 'link' => 'https://www.vbeyond.com/', 'linkedin_url' => 'https://www.linkedin.com/company/vbeyond-corporation/', 'jobs_url' => 'https://www.vbeyond.com/usa-openings/', 'phone' => '(908) 854-0425', 'email' => 'usa@vbeyond.com', 'recruiter_industry_id' => 8, 'specialties' => 'Recruitment Process Outsourcing (RPO)|IT Staffing|Executive Search and Hiring|Training and Development|Recruiting and Staffing|Employer Branding|Diversity and Inclusion|human resources|digital|diversity|rpo|executive search|c suite' ],
            [ 'primary' => 0, 'founded' => 1950, 'recruiter_id' => 82, 'name' => 'Volt', 'slug' => 'volt', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => '1455 Lincoln Parkway East', 'street2' => '8th Floor', 'city' => 'Atlanta', 'state_id' => 11, 'zip' => '30346', 'country_id' => 237, 'link' => 'https://www.volt.com', 'linkedin_url' => 'https://www.linkedin.com/company/volt/', 'jobs_url' => 'https://jobs.volt.com/', 'phone' => '(714) 921-8800', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Staffing|Direct Placement|RPO|Payroll Services|Managed Services|Engineering|Accounting|Finance|IT|Administrative|Professional|Industrial' ],
            [ 'primary' => 0, 'founded' => 1940, 'recruiter_id' => 83, 'name' => 'Yoh, A Day & Zimmermann Company', 'slug' => 'yoh-a-day-and-zimmermann-company', 'local' => 0, 'regional' => 0, 'national' => 1, 'international' => 0, 'street' => '1835 Market Street', 'street2' => null, 'city' => 'Philadelphia', 'state_id' => 39, 'zip' => '19103', 'country_id' => 237, 'link' => 'https://www.yoh.com', 'linkedin_url' => 'https://www.linkedin.com/company/yoh-a-day-&-zimmermann-company/', 'jobs_url' => 'https://jobs.yoh.com/#/jobs', 'phone' => '(215) 656-2650', 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Consulting|Staffing|Workforce Solutions' ],
            [ 'primary' => 0, 'founded' => 2018, 'recruiter_id' => 84, 'name' => 'CareerCircle', 'slug' => 'careercircle', 'local' => 0, 'regional' => 0, 'national' => 0, 'international' => 1, 'street' => null, 'street2' => null, 'city' => 'Hanover', 'state_id' => 21, 'zip' => null, 'country_id' => 237, 'link' => 'https://www.careercircle.com/', 'linkedin_url' => 'https://www.linkedin.com/company/careercircle/', 'jobs_url' => 'https://www.careercircle.com/jobs', 'phone' => null, 'email' => null, 'recruiter_industry_id' => 8, 'specialties' => 'Staffing|Recruiting|Upskill|Career|Community|Employment|CareerSkill' ],
        ];

        for ($i=0; $i<count($data); $i++) {
            $data[$i]['created_at'] = date('Y-m-m H:i:s');
            $data[$i]['updated_at'] = date('Y-m-m H:i:s');

            DB::connection('career_db')->table('job_boards')->insert($data[$i]);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
